### ISSUE TITLE
Shutdown doesn't quit headless_shell

### ISSUE THREAD

**Issue by kmanley** [chromedp/chromedp#101] opened 2017-08-05 16:38 UTC
Repro case below. Shutdown does not seem to shut down headless_shell, so the Wait hangs.

```go
package main

import (
	"context"
	"log"
	cdp "github.com/knq/chromedp"
	"github.com/knq/chromedp/runner"
)

func main() {
	var err error

	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	log.Println("starting headless_shell")
	c, err := cdp.New(ctxt, cdp.WithLog(log.Printf),
		cdp.WithRunnerOptions(runner.Headless("/home/kevin/Downloads/headless_shell/headless_shell", 8222)))
	if err != nil {
		log.Fatal(err)
	}

	log.Println("shutting down...")
	err = c.Shutdown(ctxt)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("waiting for headless_shell to exit...")
	err = c.Wait()
	if err != nil {
		log.Fatal(err)
	}

	log.Println("done")
}
```

**Comment by pwaller** [comment] 2017-08-09 13:55
I think this is a duplicate of #81.

**Comment by kmanley** [comment] 2017-08-09 13:57
@pwaller thx

**Comment by mvdan** [comment] 2019-02-21 23:17
Duplicate of https://github.com/chromedp/chromedp/issues/81.

**Closed by mvdan** 2019-02-21 23:17 UTC
