### ISSUE TITLE
Evaluating js function: encountered an undefined value

### ISSUE THREAD

**Issue by GAZ082** [chromedp/chromedp#658] opened 2020-07-09 20:43 UTC
#### What versions are you running?

<pre>
github.com/chromedp/chromedp v0.5.3
Google Chrome 83.0.4103.116
go version go1.14.4 linux/amd64
</pre>

#### What did you do? Include clear steps.
1. Go to the website.
2. Login.
3. Wait page to load.
4. chromedp.EvaluateAsDevTools("Submit('EX');", &x),

#### What did you expect to see?
A file should download.

#### What did you see instead?
`encountered an undefined value`

Code snippet:

```
	err := chromedp.Run(ctx,
		page.SetDownloadBehavior("allow").WithDownloadPath("/home/xxx/projects/website/"),
		chromedp.Navigate("https://xxxx/Login.aspx"),
		chromedp.WaitVisible("footer", chromedp.ByID),
		chromedp.SendKeys("#ctl00_cphBarra_login_UserName", "xxx", chromedp.ByID),
		chromedp.SendKeys("#ctl00_cphBarra_login_Password", "xxxx", chromedp.ByID),
		chromedp.Click("ctl00_cphBarra_login_Login"),
		chromedp.WaitVisible("footer", chromedp.ByID),
		chromedp.Navigate("https://xxxx/dddd"),
		chromedp.WaitVisible("footer", chromedp.ByID),
		chromedp.Sleep(5*time.Second),
		chromedp.EvaluateAsDevTools("Submit('EX');", &x),
	)
```

Also tried:
`chromedp.Click("#TablaBotones > tbody > tr > td:nth-child(4)", chromedp.ByJSPath),` 
which is the element that has attached the JS function but does not work (the JS is called on a `onmouseup` event tho, could not find something similar in chromedp).

Calling the function in the console works, even in the Chrome window chromedp opens (i'm not using headless for testing).

Any tips? I'd hate to go to the nodejs way.

Thanks!

**Comment by leafney** [comment] 2021-04-01 01:56
look at this #526

**Comment by ZekeLu** [comment] 2021-05-08 18:16
As @leafney pointed out, this is a duplicate of #526.

Apply the changes in #816, you can address the issue like this:

```diff
-chromedp.EvaluateAsDevTools("Submit('EX');", &x),
+chromedp.EvaluateAsDevTools("Submit('EX');", nil),
```

**Closed** 2021-05-10 07:08 UTC
