### ISSUE TITLE
Latest release of headless-shell results in "connection reset error"

### ISSUE THREAD

**Issue by owenwaller** [chromedp/chromedp#1476] opened 2024-06-09 16:06 UTC
Hi,

Over on the [`vugu`](https://github.com/vugu/vugu) project we've been using chromedp and especially the `headless-shell` docker image for quite some time without issue.

But, we are now seeing a `connection reset by peer` panic on the `latest` docker image - 

https://hub.docker.com/layers/chromedp/headless-shell/latest/images/sha256-ad31eaad2eefc3639095bf1df0d2276b1426c3371c013f3b8e0cefbf80e042a9?context=explore

With a index digest of:

sha256:6e154f5b3c2a83826b66401555e5af6b22b160ea64b1fc7646ab3390a5fe2b56

This image was pushed approx 14hrs ago (at the time of writing) so circa 03:00 UTC on 8th June 2024 

The panic looks like this:

```
--- FAIL: Test001Simple (0.00s)
panic: Get "http://localhost:9222/json/version": read tcp [::1]:54302->[::1]:9222: read: connection reset by peer [recovered]
	panic: Get "http://localhost:9222/json/version": read tcp [::1]:54302->[::1]:9222: read: connection reset by peer

goroutine 6 [running]:
testing.tRunner.func1.2({0xa53440, 0xc000195530})
	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1634 +0x377
panic({0xa53440?, 0xc000195530?})
	/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:770 +0x132
github.com/vugu/vugu/testing/chromedp.MustChromeCtx.func1()
	/home/runner/work/vugu/vugu/testing/chromedp/chromedp.go:28 +0x176
github.com/vugu/vugu/testing/chromedp.MustChromeCtx()
	/home/runner/work/vugu/vugu/testing/chromedp/chromedp.go:37 +0x13
github.com/vugu/vugu/wasm-test-suite/test-001-simple.Test001Simple(0xc0000d6b60)
	/home/runner/work/vugu/vugu/wasm-test-suite/test-001-simple/main_test.go:25 +0x53
testing.tRunner(0xc0000d6b60, 0xb2f9c8)
	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1742 +0x390
FAIL	github.com/vugu/vugu/wasm-test-suite/test-001-simple	0.007s
FAIL
```

Where the code that generates the panic is this:

```
func MustChromeCtx() (context.Context, context.CancelFunc) {

	debugURL := func() string {
		resp, err := http.Get("http://localhost:9222/json/version")
		if err != nil {
			panic(err) // <----------- panic connection reset by peer here!
		}

		var result map[string]interface{}

		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			panic(err)
		}
		return result["webSocketDebuggerUrl"].(string)
	}()

	// t.Log(debugURL)

	allocCtx, _ := chromedp.NewRemoteAllocator(context.Background(), debugURL)
	// defer cancel()

	ctx, _ := chromedp.NewContext(allocCtx) // , chromedp.WithLogf(log.Printf))
	// defer cancel()
	ctx, cancel := context.WithTimeout(ctx, 60*time.Second)
	// defer cancel()

	return ctx, cancel
}
```

The code has been working previously and we've not made a change to this code in many months. So there's no change in our side that could impact this.

You can see an example of the failure on [this Github Actions](https://github.com/vugu/vugu/actions/runs/9432853503/job/25983177210?pr=287) build.

I can rule out are code completely by using docker and curl directly like this:

```
$ docker run -d -t -p 9222:9222 --name vugu-chromedp chromedp/headless-shell # note no docker networking to eliminate that as the github action does that.
c2732b28cd04e3f902a4566a9a98050f73464bbccce13dcb4b6f9b94a825470d
$ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS                                       NAMES
c2732b28cd04   chromedp/headless-shell   "/headless-shell/hea…"   17 seconds ago   Up 16 seconds   0.0.0.0:9222->9222/tcp, :::9222->9222/tcp   vugu-chromedp
$ curl -v http://localhost:9222/json/version
*   Trying 127.0.0.1:9222...
* Connected to localhost (127.0.0.1) port 9222 (#0)
> GET /json/version HTTP/1.1
> Host: localhost:9222
> User-Agent: curl/7.88.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Which looks to me like the Dockerfile entry point has crashed i.e. The container is listening on port 9222 but crashes when it processing a connection.

I am assuming that if the `curl` command had worked, I'd see a block of JSON returned and the connection closed normally.

If it's any help if I start the container with the `--debug` option I am seeing this:

```
 docker --debug run -p 9222:9222 --name vugu-chromedp chromedp/headless-shell

DevTools listening on ws://127.0.0.1:9222/devtools/browser/4a2bf258-e169-42b0-9360-02c9542c9087
[0609/153453.027959:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Has anyone any idea what has changed and how to fix this?

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.3
$ google-chrome --version # m machine has chromium installed....
$ chromium --version
Chromium 125.0.6422.112 snap
$ go version
go version go1.22.3 linux/amd64
```

Many thanks.

**Comment by owenwaller** [comment] 2024-06-13 15:12
Hi,

Just to update this I am still seeing the same behaviour on the latest release (12th June?). 
I've tested again with docker + curl to eliminate our the `vugu` codebase.

The new index digest for the release I've just tried (which still fails) is:

```
sha256:e1ddb28c48f57052bc0261849ea06a3d1ef568facccb0de75b3b29a9975db6f7
```

Owen

**Comment by kenshaw** [comment] 2024-06-13 21:05
@owenwaller I just tried on `latest`, `dev`, and `beta` tags (`amd64` platform) and it works just fine. Are you using the `arm64` platform? I can try later today with `arm64`, but as far as I can tell the `docker.io/chromedp/headless-shell` image is working just fine.

**Comment by bradleypeabody** [comment] 2024-06-14 18:38
It looks like the port 9222 listener was changed in version `126.0.6478.26` to listen on localhost (127.0.0.1) instead of all IP addresses.  This appears to be what is causing the issue.  You can see it clearly here by using the `ss` command to compared to the prior version `125.0.6422.142`

Older version `125.0.6422.142`:
```
% docker run -d -t --name chromedp-125.0.6422.142 chromedp/headless-shell:125.0.6422.142
3a6a08350bacde695944e820d40d5b514fa21f0401c65fbb71f33a4038e13190
% docker exec -it chromedp-125.0.6422.142 bash -c 'apt -qq update && apt install -qq -y iproute2 > /dev/null 2>&1 && ss -a | grep 9222'
All packages are up to date.
tcp   LISTEN    0      10           0.0.0.0:9222                     0.0.0.0:*
```

Next version: `126.0.6478.26`
```
 % docker run -d -t --name chromedp-126.0.6478.26 chromedp/headless-shell:126.0.6478.26
3bdfdcffc80096afd0b9b6649b1a96a0dd3a45d6b63ab83d8154082fd193536f
% docker exec -it chromedp-126.0.6478.26 bash -c 'apt -qq update && apt -qq install -y iproute2 > /dev/null 2>&1 && ss -a | grep 9222'
All packages are up to date.
tcp   LISTEN    0      10         127.0.0.1:9222                     0.0.0.0:*
```

**Comment by owenwaller** [comment] 2024-06-14 18:59
@kenshaw 

Re: @bradleypeabody comment above,

The `chromedp/headless-shell` should be listening on the network broadcast address i.e. all IP's.

The reason is you (as the container author) have no idea how the container will be networked. So you don't know the number of NICs, or the IP range of the network on each NIC or the type of each network attached to each NIC i.e. some networks might be only between containers via a `docker network create` or bridged between the container host and the container using the default bridge.

This can't be fixed to `127.0.0.1` aka `localhost`

As far as I am aware `127.0.0.1` refers to the container, not the host that the container is running on. The later is known as `host` - docker will insert this host name in the containers `/etc/hosts` with an IP if the hosts external IP address.

Owen

**Comment by kenshaw** [comment] 2024-06-14 21:49
First, I tested on `arm64`, and all three images works just fine.

This is very much likely a configuration issue with `docker` vs `podman`. Note that the container image listens specifically on 0.0.0.0:

```Dockerfile
ENTRYPOINT [ "/headless-shell/headless-shell", "--no-sandbox", "--use-gl=angle", "--use-angle=swiftshader", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
```

If you've changed/overwritten the entrypoint with your image, then it might be you're missing the `--remote-debugging-address` parameter. Additionally, I have seen `docker` introduce weird firewall rules and other problems.

Could you please try using the raw `headless-shell` image, and do the following:

```sh
$ curl -v http://127.0.0.1:9222/json/version
*   Trying 127.0.0.1:9222...
* Connected to 127.0.0.1 (127.0.0.1) port 9222
> GET /json/version HTTP/1.1
> Host: 127.0.0.1:9222
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Security-Policy:frame-ancestors 'none'
< Content-Length:408
< Content-Type:application/json; charset=UTF-8
< 
{
   "Browser": "Chrome/126.0.6478.57",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.57 Safari/537.36",
   "V8-Version": "12.6.228.16",
   "WebKit-Version": "537.36 (@97c46667f6c5c85244ca7cfa0b42e35bf4055d3b)",
   "webSocketDebuggerUrl": "ws://127.0.0.1:9222/devtools/browser/e6ff408b-1ce3-4071-8bc7-58a3b2d91b22"
}
* Connection #0 to host 127.0.0.1 left intact
```

Please also check that executing/running `curl` on the container (yes, you will need to install it via `apt` first), is able to produce the above output. If it is, and you're not able to do it from the container host, then the problem entirely lies with `docker`.

On a separate note, I would suggest migrating to `podman` when you're able to, as I've seen an increasing number of these kinds of issues with `docker` on many different container images.

**Comment by owenwaller** [comment] 2024-06-15 11:58
@kenshaw 

Thanks for that. 

For the avoidance of any doubt, we don't change the `headless-shell` image at all. 
So the `docker` commands (see my comments above) are against the unmodified image we pull from docker hub.

My version of docker is:
```
$ docker version
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:22 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
@bradleypeabody docker wil lbe different as he's on MacOS.

I haven't upgraded docker in many many many months.

Everything was fine for us until the release of the (circa) 12th.

And if we back date, as Brad shows, then it works again.

With Docker can you repeat what I've done, asn see if you see the same issue?

Regards

Owen

**Comment by kenshaw** [comment] 2024-06-15 12:48
@owenwaller No, I do all development on Linux. I will test though on MacOS and Windows, usually.

**Comment by matt0x6F** [comment] 2024-06-15 19:16
@kenshaw I was attempting to get headless shell up and running and ran into this.

I believe @bradleypeabody is correct. Even if I provide `--remote-debugging-address=0.0.0.0` the container listens on `127.0.0.1` for `latest`. When I use version `125.0.6422.142` it listens on the broadcast address (0.0.0.0).

**Comment by kenshaw** [comment] 2024-06-17 10:14
I haven't used Docker for over 2 years now, and am unlikely to install it again. It's fairly easy to switch to `podman`, and I would highly encourage you to do so.

**Comment by owenwaller** [comment] 2024-06-17 10:37
@kenshaw Sorry, but, that is not an option for us.

Setting aside `vugu` I have other closed source projects that use the `headless-shell` for testing. Switching those to `podman` is simply not an option. I have sound commercial/infrastructure/security etc. constraints that I have to work within.

From a `vugu` perspective, and speaking in a personal capacity not as a project contributor, the only dependency we ask of `vugu` contributors is that they have `docker` installed. All of the external tools we need to test `vugu` then run in a series of containers. This gives us platform independence as we have to build and test on Windows, MacOS, Linux, BSD etc. The tools we rely on, in particular the `tinygo` compiler suite are difficult to install locally. It's not reasonable (in my view) to expect a contributor to  install, update and maintain all of the tools needed to test `vugu` locally. By picking an image we can also ensure that we are using the latest versions of those tools. That's why the `vugu` build process uses the images.

I appreciate your view on `docker` but, like it or loath it, it is the dominate tool in this area. That is why `vugu` depends on `docker` and not `podman`. `vugu` contributors are much more likely to have `docker` installed already. ` docker` is the tool that the majority of the `headless-shell` user base are going to be using, 

And as I said it's been working fine with `docker` until the update of circa June 12th. I've not updated docker in that period but `headless-shell` has changed.

Having a container image that only functions correctly with `podman` and not `docker` would in my view be very unusual.

Owen

**Comment by kenshaw** [comment] 2024-06-17 10:41
@owenwaller I'm unable to reproduce this issue. I have tried multiple tags, and they all work. Please feel free to debug and let me know what the issue is, and I'll be happy to make the changes accordingly. Closing this for now. Please reopen when you have something that is reproducible. Thanks.

**Closed by kenshaw** 2024-06-17 10:41 UTC
