### ISSUE TITLE
How to use rich text editor？

### ISSUE THREAD

**Issue by ChenSee** [chromedp/chromedp#750] opened 2021-02-04 03:21 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
go version go1.14.5 darwin/amd64
</pre>

#### What did you do? Include clear steps.
How should rich text editor operate automatically? I can't use sendkeys properly.

#### What did you expect to see?
Can operate rich text editor automatically.

**Comment by ZekeLu** [comment] 2021-04-11 03:09
Take a look at this example: https://github.com/chromedp/chromedp/issues/789#issuecomment-817239348 . It's for https://draftjs.org/. But it should work for most rick editors.

**Comment by ZekeLu** [comment] 2021-04-27 08:35
Closing as a duplicate of #789.

Feel free to reopen this issue if I'm mistaken. Thanks!

**Closed by ZekeLu** 2021-04-27 08:35 UTC
