### ISSUE TITLE
Question about iframes

### ISSUE THREAD

**Issue by tigp** [chromedp/chromedp#103] opened 2017-08-09 01:51 UTC
@kenshaw May I ask you is it possible to access iframes, send keys, click on buttons, etc..? And what is the best way to do it?
Thank you for the great work btw.

**Comment by yogesh-desai** [comment] 2017-09-11 14:39
@cleancodeninja: Please check issue #72  It is similar with more information.

**Comment by ZetaChow** [comment] 2018-08-28 06:11
https://github.com/chromedp/chromedp/issues/212#issuecomment-416462733

**Comment by mvdan** [comment] 2019-02-20 11:49
Closing as a duplicate of #72; let's keep track of the iframe issues there.

**Closed by mvdan** 2019-02-20 11:49 UTC
