### ISSUE TITLE
Chrome shows an error popup with a restore button at a second time when specifying user data directory and non-headless mode

### ISSUE THREAD

**Issue by miyajan** [chromedp/chromedp#504] opened 2019-11-01 02:29 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.1
$ google-chrome --version
Google Chrome 77.0.3865.120
$ go version
go version go1.12.6 linux/amd64
</pre>

#### What did you do? Include clear steps.

I wrote a code like below.

```go
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	dir := "/tmp/chromedp-test"

	opts := []chromedp.ExecAllocatorOption{
		chromedp.UserDataDir(dir),
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
	}
	allocCtx, allocCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer allocCancel()

	taskCtx, taskCancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer taskCancel()

	if err := chromedp.Run(taskCtx); err != nil {
		panic(err)
	}

	time.Sleep(10 * time.Second)
}
```

Then, I executed it twice.

```bash
$ go run main.go
$ go run main.go
```

#### What did you expect to see?

A blank window is displayed and nothing happens for 10 seconds with no error.

#### What did you see instead?

At the second time, there is a popup which shows an error message "Chrome didn't shut down correctly." with a restore button.

![Screenshot from 2019-11-01 11-19-57](https://user-images.githubusercontent.com/945853/67998061-44be5c00-fc9a-11e9-89a0-42b4271062dd.png)

**Comment by mvdan** [comment] 2019-11-06 22:10
This is a duplicate of https://github.com/chromedp/chromedp/issues/472; right now, the cancel functions kill the browser without giving it a chance to close gracefully, which is why you're seeing that warning.

**Closed by mvdan** 2019-11-06 22:10 UTC

**Comment by miyajan** [comment] 2020-03-31 05:12
@mvdan I tried `chromedp.Cancel` with chromedp v0.5.3, but I couldn't resolve this issue.

```
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 80.0.3987.149
$ go version
go version go1.12.1 darwin/amd64
```

I wrote the code like below.

```
package main

import (
	"context"
	"github.com/chromedp/chromedp"
	"log"
	"time"
)

func main() {
	dir := "/tmp/chromedp-test"

	opts := []chromedp.ExecAllocatorOption{
		chromedp.UserDataDir(dir),
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
	}
	allocCtx, allocCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer allocCancel()

	taskCtx, taskCancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer taskCancel()

	if err := chromedp.Run(taskCtx); err != nil {
		panic(err)
	}

	time.Sleep(10 * time.Second)
	err := chromedp.Cancel(taskCtx)
	if err != nil {
		panic(err)
	}
}
```

Then, I executed it twice.

```
$ go run main.go
$ go run main.go
```

The `chromedp.Cancel` returned no errors, but there was the popup with the restore button at the second run.

Puppeteer doesn't cause this issue. Puppeteer seems to kill the browser's process when the user data directory is specified.

https://github.com/puppeteer/puppeteer/blob/33f1967072e07824c5bf6a8c1336f844d9efaabf/lib/Launcher.js#L116-L152

puppeteer/puppeteer#839 and puppeteer/puppeteer#1028 seem to be related issues.

**Comment by miyajan** [comment] 2020-03-31 09:16
> Puppeteer seems to kill the browser's process when the user data directory is specified.

Sorry, this is my mistake. Puppeteer seems to kill the browser's process when the user data directory is **not** specified. Puppeteer calls `Browser.close` when the user data directory is specified.
