### ISSUE TITLE
How do I know if the browser is down or disconnected

### ISSUE THREAD

**Issue by getong2186** [chromedp/chromedp#1018] opened 2022-02-18 06:31 UTC
Hello!  When I use “chromedp.NewRemoteAllocator” to remote the browser that has been started , how do I know if the browser is closed or disconnected, like puppeteer's “browser.on('disconnected', () = >; {...do  something}); ” ，Because I want to use Chromedp to listen for browser state.
Thank you very much

**Comment by ZekeLu** [comment] 2022-02-18 09:15
Duplicate of #1004?

**Comment by getong2186** [comment] 2022-02-18 10:04
Thank you

**Closed** 2022-02-18 10:23 UTC
