### ISSUE TITLE
assignment mismatch: 8 variables but css.GetMatchedStylesForNode(nodes[0].NodeID).Do returns 9 values

### ISSUE THREAD

**Issue by super-l** [chromedp/chromedp#1138] opened 2022-08-19 03:47 UTC
go build
# github.com/chromedp/chromedp
C:\Users\Administrator\go1.18.2\pkg\mod\github.com\chromedp\chromedp@v0.8.2\query.go:1139:33: assignment mismatch: 8 variables but css.GetMatchedStylesForNode(nodes[0].NodeID).Do returns 9 values

```
// old code
// MatchedStyle is an element query action that retrieves the matched style information
// for the first element node matching the selector.
func MatchedStyle(sel interface{}, style **css.GetMatchedStylesForNodeReturns, opts ...QueryOption) QueryAction {
	if style == nil {
		panic("style cannot be nil")
	}

	return QueryAfter(sel, func(ctx context.Context, execCtx runtime.ExecutionContextID, nodes ...*cdp.Node) error {
		if len(nodes) < 1 {
			return fmt.Errorf("selector %q did not return any nodes", sel)
		}

		var err error
		ret := &css.GetMatchedStylesForNodeReturns{}
		ret.InlineStyle, ret.AttributesStyle, ret.MatchedCSSRules,ret.PseudoElements, ret.Inherited, ret.InheritedPseudoElements, ret.CSSKeyframesRules, err = css.GetMatchedStylesForNode(nodes[0].NodeID).Do(ctx)
		if err != nil {
			return err
		}

		*style = ret

		return nil
	}, opts...)
}
```

```
// new code
// MatchedStyle is an element query action that retrieves the matched style information
// for the first element node matching the selector.
func MatchedStyle(sel interface{}, style **css.GetMatchedStylesForNodeReturns, opts ...QueryOption) QueryAction {
	if style == nil {
		panic("style cannot be nil")
	}

	return QueryAfter(sel, func(ctx context.Context, execCtx runtime.ExecutionContextID, nodes ...*cdp.Node) error {
		if len(nodes) < 1 {
			return fmt.Errorf("selector %q did not return any nodes", sel)
		}

		var err error
		ret := &css.GetMatchedStylesForNodeReturns{}
		ret.InlineStyle, ret.AttributesStyle, ret.MatchedCSSRules,ret.PseudoElements, ret.Inherited, ret.InheritedPseudoElements, ret.CSSKeyframesRules, **ret.ParentLayoutNodeID**, err = css.GetMatchedStylesForNode(nodes[0].NodeID).Do(ctx)
		if err != nil {
			return err
		}

		*style = ret

		return nil
	}, opts...)
}
```

**Comment by ZekeLu** [comment] 2022-08-19 09:06
Duplicate of #1126. Please upgrade to `v0.8.4`.

**Closed** 2022-08-19 11:05 UTC
