### ISSUE TITLE
 chromedp.RunResponse does not take iframe navigation into account

### ISSUE THREAD

**Issue by delanne** [chromedp/chromedp#983] opened 2021-12-17 16:05 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ go version
go version go1.17.1 linux/amd64
```

#### What did you do? Include clear steps.

```go
// Command headers is a chromedp example demonstrating how to add extra HTTP
// headers to browser requests.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/chromedp"
)

const indexHTML = `<!DOCTYPE html>
<html>
<body>
<h2>Foo Bar</h2>
<a id="link" href="end.html">This is some text in a paragraph.</a>
</body>
</html>
`

const endHTML = `<!DOCTYPE html>
<html>
<body>
<p id="end">end</p>
</body>
</html>
`

const iframeHTML = `
<!DOCTYPE html>
	<html>
		<head>
			<title></title>
			<style type="text/css">
				body {
					margin: 0;
					padding: 0;
					border: none;
				}
				iframe {
					width: 100%;
					height: 100vh;
				}
			</style>
		</head>
		<body>
			<iframe width="100%" height="100%" src="index.html">
			</iframe>
		</body>
	</html>
`

func main() {
	port := flag.Int("port", 8544, "port")
	flag.Parse()

	// run server
	go httpServer(fmt.Sprintf(":%d", *port))

	// create context
	ctx, cancel := chromedp.NewContext(context.Background()) //chromedp.WithDebugf(log.Printf),

	defer cancel()

	pages := []string{"index.html", "iframe.html"}

	for _, page := range pages {
		nodes := []*cdp.Node{}
		fmt.Println("Browsing page: ", page)
		actions := []chromedp.Action{
			chromedp.Navigate(fmt.Sprintf("http://localhost:%d/%s", *port, page)),
			chromedp.Nodes("#link", &nodes)}
		// run task list
		err := chromedp.Run(ctx, actions...)
		if err != nil {
			log.Fatal(err)
		}

		link := nodes[0]
		fmt.Println("Send Click on Node ", link.NodeID)
		_, err = chromedp.RunResponse(ctx, chromedp.MouseClickNode(link))

		actions = []chromedp.Action{
			chromedp.Nodes("#end", &nodes)}
		fmt.Println("Get End item")
		err = chromedp.Run(ctx, actions...)
		if err != nil {
			log.Fatal(err)
		}
		PrintNode(nodes[0])
	}
}

//  is a simple HTTP server that displays the passed headers in the html.
func httpServer(addr string) error {
	mux := http.NewServeMux()
	mux.HandleFunc("/index.html", func(res http.ResponseWriter, req *http.Request) {
		buf, err := json.MarshalIndent(req.Header, "", "  ")
		if err != nil {
			http.Error(res, err.Error(), http.StatusInternalServerError)
			return
		}
		fmt.Fprintf(res, indexHTML, string(buf))
	})
	mux.HandleFunc("/iframeHTML.html", func(res http.ResponseWriter, req *http.Request) {
		buf, err := json.MarshalIndent(req.Header, "", "  ")
		if err != nil {
			http.Error(res, err.Error(), http.StatusInternalServerError)
			return
		}
		fmt.Fprintf(res, indexHTML, string(buf))
	})
	mux.HandleFunc("/end.html", func(res http.ResponseWriter, req *http.Request) {
		buf, err := json.MarshalIndent(req.Header, "", "  ")
		if err != nil {
			http.Error(res, err.Error(), http.StatusInternalServerError)
			return
		}
		fmt.Fprintf(res, endHTML, string(buf))
	})
	return http.ListenAndServe(addr, mux)
}

// PrintNode is for debugging purpose //
func PrintNode(node *cdp.Node) {
	fmt.Printf("\nNodeID\t\t:%d\n", node.NodeID.Int64())
	fmt.Printf("ParentID\t\t: %d\n", node.ParentID.Int64())
	fmt.Printf("BackendNodeID\t\t: %d\n", node.BackendNodeID.Int64())
	fmt.Printf("NodeType\t\t: %s\n", node.NodeType.String())
	fmt.Printf("NodeName\t\t: %s\n", node.NodeName)
	fmt.Printf("LocalName\t\t: %s\n", node.LocalName)
	fmt.Printf("NodeValue\t\t: %s\n", node.NodeValue)
	fmt.Printf("ChildNodeCount\t\t: %d\n", node.ChildNodeCount)
	fmt.Printf("Children\t\t: %v\n", node.Children)
	fmt.Printf("Attributes\t\t: %v\n", node.Attributes)
	fmt.Printf("DocumentURL\t\t: %v\n", node.DocumentURL)
	fmt.Printf("BaseURL\t\t: %v\n", node.BaseURL)
	fmt.Printf("PublicID\t\t: %v\n", node.PublicID)
	fmt.Printf("SystemID\t\t: %v\n", node.SystemID)
	fmt.Printf("InternalSubset\t\t: %v\n", node.InternalSubset)
	fmt.Printf("XMLVersion\t\t: %v\n", node.XMLVersion)
	fmt.Printf("Name\t\t: %v\n", node.Name)
	fmt.Printf("Value\t\t: %v\n", node.Value)
	fmt.Printf("PseudoType\t\t: %v\n", node.PseudoType)
	fmt.Printf("ShadowRootType\t\t: %s\n", node.ShadowRootType.String())
	fmt.Printf("FrameID\t\t: %v\n", node.FrameID)
	fmt.Printf("ContentDocument  \t\t: %v\n", node.ContentDocument)
	fmt.Printf("ShadowRoots\t\t: %v\n", node.ShadowRoots)
	fmt.Printf("TemplateContent\t\t: %v\n", node.TemplateContent)
	fmt.Printf("PseudoElements\t\t: %v\n", node.PseudoElements)
	fmt.Printf("DistributedNodes\t\t: %v\n", node.DistributedNodes)
	fmt.Printf("IsSVG\t\t: %v\n", node.IsSVG)
	fmt.Printf("Parent\t\t: %v\n", node.Parent)
	fmt.Printf("State\t\t: %v\n", node.State.String())
	fmt.Printf("FullXPath\t\t: %s\n", node.FullXPath())
	fmt.Printf("FullXPathByID\t\t: %s\n", node.FullXPathByID())
	fmt.Printf("PartialXPath\t\t: %s\n", node.PartialXPath())
	fmt.Printf("PartialXPathByID\t\t: %s\n", node.PartialXPathByID())
	fmt.Printf("\n")
}
```

#### What did you expect to see?
 - When using chromedp.Nodes with chromedp.RunResponse on a Node in a iframe, chromedp.RunResponse wait for ever (missing even ? or maybe it doesn't track the iframe change ?) 

with the code provided I expect to see:
```
Browsing page:  index.html
Send Click on Node  11
Get End item [...]
Browsing page:  iframe.html
Send Click on Node  XX
Get End item [...]
```
#### What did you see instead?

with the code provided I see:
```
Browsing page:  index.html
Send Click on Node  11
Get End item [...]
Browsing page:  iframe.html
```

**Comment by ZekeLu** [comment] 2021-12-18 04:12
@delanne Thank you for reporting the issue!

There is something wrong in your code, but the reported issue is valid. I have created a new demo based on yours to show the issue (appended to the end of this comment).

But based on the doc and the implementation, it seems that the behavior is by design.

First, the doc says it's for page navigation:

> RunResponse is an alternative to Run which can be used with a list of actions that trigger a **page navigation**, such as clicking on a link or button.
>
> RunResponse will run the actions and block **until a page loads**, returning the HTTP response information for its HTML document. This can be useful to wait for the **page** to be ready, or to catch 404 status codes, for example.
> 
> Note that if the actions trigger multiple navigations, only the first is used. And if the actions trigger no navigations at all, RunResponse will block until the context is cancelled.

Second, the implementation requires that the navigation is for the top frame (see line 513 and line 525 below):

https://github.com/chromedp/chromedp/blob/093d306142f96202a711665369247a2f8227600e/chromedp.go#L510-L527

**Demo to show the issue**:

```go
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/chromedp"
)

func main() {
	port := flag.Int("port", 8544, "port")
	flag.Parse()

	// run server
	go httpServer(fmt.Sprintf(":%d", *port))

	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var iframes []*cdp.Node
	if err := chromedp.Run(ctx,
		chromedp.Navigate(fmt.Sprintf("http://localhost:%d/iframe.html", *port)),
		chromedp.Nodes("iframe", &iframes, chromedp.ByQuery),
	); err != nil {
		log.Fatal(err)
	}
	log.Println("Click and wait for the iframe navigation to finish.")
	ctx, cancel = context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	if _, err := chromedp.RunResponse(ctx,
		chromedp.Click("#link", chromedp.ByQuery, chromedp.FromNode(iframes[0])),
	); err != nil {
		log.Fatal(err)
	}
}

func httpServer(addr string) error {
	mux := http.NewServeMux()
	mux.HandleFunc("/index.html", func(res http.ResponseWriter, req *http.Request) {
		fmt.Fprint(res, indexHTML)
	})
	mux.HandleFunc("/iframe.html", func(res http.ResponseWriter, req *http.Request) {
		fmt.Fprint(res, iframeHTML)
	})
	return http.ListenAndServe(addr, mux)
}

const indexHTML = `<!DOCTYPE html>
<html>
<body>
<h2>Foo Bar</h2>
<a id="link" href="end.html">This is some text in a paragraph.</a>
</body>
</html>
`

const iframeHTML = `
<!DOCTYPE html>
	<html>
		<head>
			<title></title>
			<style type="text/css">
				body {
					margin: 0;
					padding: 0;
					border: none;
				}
				iframe {
					width: 100%;
					height: 100vh;
				}
			</style>
		</head>
		<body>
			<iframe width="100%" height="100%" src="index.html">
			</iframe>
		</body>
	</html>
`
```

**Comment by ZekeLu** [comment] 2022-02-06 04:33
The behavior is by design and won't be changed. Closing.

**Closed by ZekeLu** 2022-02-06 04:33 UTC

**Comment by charleslana** [comment] 2023-10-10 12:20
> @delanne Thank you for reporting the issue!
> 
> There is something wrong in your code, but the reported issue is valid. I have created a new demo based on yours to show the issue (appended to the end of this comment).
> 
> But based on the doc and the implementation, it seems that the behavior is by design.
> 
> First, the doc says it's for page navigation:
> 
> > RunResponse is an alternative to Run which can be used with a list of actions that trigger a **page navigation**, such as clicking on a link or button.
> > RunResponse will run the actions and block **until a page loads**, returning the HTTP response information for its HTML document. This can be useful to wait for the **page** to be ready, or to catch 404 status codes, for example.
> > Note that if the actions trigger multiple navigations, only the first is used. And if the actions trigger no navigations at all, RunResponse will block until the context is cancelled.
> 
> Second, the implementation requires that the navigation is for the top frame (see line 513 and line 525 below):
> 
> https://github.com/chromedp/chromedp/blob/093d306142f96202a711665369247a2f8227600e/chromedp.go#L510-L527
> 
> **Demo to show the issue**:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"flag"
> 	"fmt"
> 	"log"
> 	"net/http"
> 	"time"
> 
> 	"github.com/chromedp/cdproto/cdp"
> 	"github.com/chromedp/chromedp"
> )
> 
> func main() {
> 	port := flag.Int("port", 8544, "port")
> 	flag.Parse()
> 
> 	// run server
> 	go httpServer(fmt.Sprintf(":%d", *port))
> 
> 	// create context
> 	ctx, cancel := chromedp.NewContext(context.Background())
> 	defer cancel()
> 
> 	var iframes []*cdp.Node
> 	if err := chromedp.Run(ctx,
> 		chromedp.Navigate(fmt.Sprintf("http://localhost:%d/iframe.html", *port)),
> 		chromedp.Nodes("iframe", &iframes, chromedp.ByQuery),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> 	log.Println("Click and wait for the iframe navigation to finish.")
> 	ctx, cancel = context.WithTimeout(ctx, 3*time.Second)
> 	defer cancel()
> 	if _, err := chromedp.RunResponse(ctx,
> 		chromedp.Click("#link", chromedp.ByQuery, chromedp.FromNode(iframes[0])),
> 	); err != nil {
> 		log.Fatal(err)
> 	}
> }
> 
> func httpServer(addr string) error {
> 	mux := http.NewServeMux()
> 	mux.HandleFunc("/index.html", func(res http.ResponseWriter, req *http.Request) {
> 		fmt.Fprint(res, indexHTML)
> 	})
> 	mux.HandleFunc("/iframe.html", func(res http.ResponseWriter, req *http.Request) {
> 		fmt.Fprint(res, iframeHTML)
> 	})
> 	return http.ListenAndServe(addr, mux)
> }
> 
> const indexHTML = `<!DOCTYPE html>
> <html>
> <body>
> <h2>Foo Bar</h2>
> <a id="link" href="end.html">This is some text in a paragraph.</a>
> </body>
> </html>
> `
> 
> const iframeHTML = `
> <!DOCTYPE html>
> 	<html>
> 		<head>
> 			<title></title>
> 			<style type="text/css">
> 				body {
> 					margin: 0;
> 					padding: 0;
> 					border: none;
> 				}
> 				iframe {
> 					width: 100%;
> 					height: 100vh;
> 				}
> 			</style>
> 		</head>
> 		<body>
> 			<iframe width="100%" height="100%" src="index.html">
> 			</iframe>
> 		</body>
> 	</html>
> `
> ```

This example no longer works in 2023, has anyone managed to click inside an iframe? in 2023, it doesn't work.

**Comment by ZekeLu** [comment] 2023-10-13 15:37
The demo is used to show that "chromedp.RunResponse does not take iframe navigation into account" and this behavior is by design.
