### ISSUE TITLE
No resource with given identifier found (-32000)

### ISSUE THREAD

**Issue by mydsuo** [chromedp/chromedp#1130] opened 2022-08-02 08:07 UTC
```go
 func listenNetWork(traceid string, timeoutCtx context.Context) {
	chromedp.ListenTarget(timeoutCtx, func(event interface{}) {
		switch event.(type) { 
		case *network.EventResponseReceived:
			res := event.(*network.EventResponseReceived)
			go ProcessResponse(traceid, timeoutCtx, res)
		}
	})
}

func ProcessResponse(traceid string, timeoutCtx context.Context, r *network.EventResponseReceived) {
	resbody := ""
	p := network.GetResponseBody(r.RequestID)
	c := chromedp.FromContext(timeoutCtx)
	body, errb := p.Do(cdp.WithExecutor(timeoutCtx, c.Target))
	if errb == nil {
		fmt.Println(string(body))
	} else {
		fmt.Println(errb.Error()) 
	} 
}
```

想通过上面的代码获取到请求响应的内容，大部分请求的响应内容body可以获取到，偶尔会报 No resource with given identifier found (-32000)，这个是什么原因呢，要怎么才能不报错

**Comment by ZekeLu** [comment] 2022-08-02 09:18
As stated by the message, there is not resource with the given request id. The message is returned from the browser:

https://github.com/chromium/chromium/blob/4c9e0cda7743d1140936644eab69437cfc10f3fa/third_party/blink/renderer/core/inspector/inspector_network_agent.cc#L2152

I don't know what will lead to this error. The good first step is to log the request when the error occurs.

**Comment by ZekeLu** [comment] 2022-08-28 00:54
Closing since no enough information is provided and the issue is not actionable.

**Closed by ZekeLu** 2022-08-28 00:54 UTC
Labels: needs info

**Comment by oshellhahaha** [comment] 2022-12-14 15:00
一样遇到了

**Comment by ZekeLu** [comment] 2022-12-15 01:17
@oshellhahaha Can you provide a demo to show the issue?

**Comment by xzvwang** [comment] 2023-02-13 10:00
I also met this case:
In my case, I listen `network.EventResponseReceived` and identify request the url i need and record this request id use variable `reqId`.
Then listen `network.EventLoadingFinished` to get response by `network.GetResponseBody(reqId).Do(ctx)` and i got error: `No resource with given identifier found (-32000)`.

**Comment by ZekeLu** [comment] 2023-02-13 11:01
@xzvwang Can you provide a self-contained, executable demo?

**Comment by leafney** [comment] 2023-07-13 07:58
I have the same problem.
After testing, I found that if the request method is `OPTIONS` , the response data is empty, or `Content-Length = 0`, `GetResponseBody` will appear `No resource with given identifier found (-32000)`  error.
