### ISSUE TITLE
Error while unmarshaling network messages

### ISSUE THREAD

**Issue by Comradin** [chromedp/chromedp#453] opened 2019-08-19 07:44 UTC
Hello,

I am trying to analyze the resource usage of a website with the help of the chromedp library. When enabling the network domain I get corrupt json messages.

From my go.mod file the versions I am using are:
github.com/chromedp/cdproto v0.0.0-20190429085128-1aa4f57ff2a9
github.com/chromedp/chromedp v0.3.1

A short example of my code:
```
func main() {
  cpctx, cancel := chromedp.NewContext(ctx,
  		     chromedp.WithDebugf(devToolHandler))
  defer cancel()

  err := chromedp.Run(cpctx,
           network.Enable(),
           chromedp.Navigate(baseUrl.String()),
             ...
         )
}

// The handler being used in the context
func devToolHandler(s string, is ...interface{}) {
	/*
	   Uncomment the following line to have a log of the events
	   log.Printf(s, is...)
	*/
	/*
	   We need this to be on a separate gorutine
	   otherwise we block the browser and we don't receive messages
	*/
	go func() {
		for _, elem := range is {
			var msg cdproto.Message
			// The CDP messages are sent as strings so we need to convert them back
			err := json.Unmarshal([]byte(fmt.Sprintf("%s", elem)), &msg)
			// possible source of empty msg!!!!!!!!!!!!!
			if err != nil {
				log.Println(err)
				log.Printf("Faulty element:\n%v\n", fmt.Sprintf("%s", elem))
			}

			msgChan <- msg
		}
	}()
}
```

Some examples of those corrupt messages 
The message has been cut off inside the targetid field:
```
2019/08/16 11:27:14 unexpected end of JSON input
2019/08/16 11:27:14 Faulty element:
{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"12C28C69BFC88E78A8BD2AA83AB2D475","message":"{\"method\":\"Network.loadingFinished\",\"params\":{\"requestId\":\"1000030524.136\",\"timestamp\":180150.31724,\"encodedDataLength\":31389,\"shouldReportCorbBlocking\":false}}","targetId":"6296FD1F8C4D089
```

An example message from the network domain, this time the error occures after the targetId:
```
2019/08/16 11:27:14 invalid character 'a' after top-level value
2019/08/16 11:27:14 Fautly element:
{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"12C28C69BFC88E78A8BD2AA83AB2D475","message":"{\"method\":\"Network.loadingFinished\",\"params\":{\"requestId\":\"1000030524.95\",\"timestamp\":180150.112695,\"encodedDataLength\":23093,\"shouldReportCorbBlocking\":false}}","targetId":"6296FD1F8C4D08988ADD6EC222A30C3F"}}ary.com/flyby/t_thumbOWP/15584289868777.png\",\"status\":200,\"statusText\":\"\",\"headers\":{\"date\":\"Fri, 16 Aug 2019 09:27:14 GMT\",\"via\":\"1.1 varnish\",\"age\":\"1301358\",<CUTOFF>}}
```

It is like the beginning of the URL is missing in all these messages. Note, that the end of the message is complete, I have cut off the rest of the line to shorten the message a bit.

First I did some experiments with the EnableParams (WithMaxTotalBufferSizes) until I realized that there are filters by message size so that overly large messages won't hit my code.

I guess either I have made some mistake with the setup of my chromedp.NewContext() or there is a bug when the slice of interfaces for `is` is being created. I tracked the call chain into the chromedp conn.go file Read() func. 

To me the observed behaviour could be explained by two buffers are copied into a third and the first overwrites parts of the second?

Kind regards,
Marcus

**Comment by mvdan** [comment] 2019-08-19 08:32
Can you please re-run your program with `-race`? If a race is detected, is it caused by chromedp, or your code?

**Comment by Comradin** [comment] 2019-08-19 13:57
Thanks for the quick answer, I reran my code with -race now.
I even did last Friday, but looks like I overlooked the error message. Or I did ran the tests with -race which do not interact with the browser. Nevertheless I overlooked the detected race.

Here comes the trace from the error:
```
go run -race main.go
==================
WARNING: DATA RACE
Read at 0x00c000114200 by goroutine 16:
  runtime.slicecopy()
      /usr/lib/go/src/runtime/slice.go:197 +0x0
  fmt.(*fmt).pad()
      /usr/lib/go/src/fmt/print.go:79 +0x11a
  fmt.(*fmt).fmtBs()
      /usr/lib/go/src/fmt/format.go:353 +0x86
  fmt.(*pp).fmtBytes()
      /usr/lib/go/src/fmt/print.go:491 +0xd51
  fmt.(*pp).printArg()
      /usr/lib/go/src/fmt/print.go:686 +0x698
  fmt.(*pp).doPrintf()
      /usr/lib/go/src/fmt/print.go:1016 +0x31c
  fmt.Sprintf()
      /usr/lib/go/src/fmt/print.go:214 +0x73
  main.devToolHandler.func1()
      /home/marcus/git/netsecured/tooling/chrome-resolver/cmd/chromedp-network-intercept/main.go:35 +0x13f

Previous write at 0x00c000114200 by goroutine 14:
  syscall.Read()
      /usr/lib/go/src/internal/race/race.go:49 +0x9b
  internal/poll.(*FD).Read()
      /usr/lib/go/src/internal/poll/fd_unix.go:165 +0x1a5
  net.(*netFD).Read()
      /usr/lib/go/src/net/fd_unix.go:202 +0x65
  net.(*conn).Read()
      /usr/lib/go/src/net/net.go:177 +0xa1
  net.(*TCPConn).Read()
      <autogenerated>:1 +0x69
  io.(*LimitedReader).Read()
      /usr/lib/go/src/io/io.go:448 +0xc7
  github.com/gobwas/ws/wsutil.(*Reader).Read()
      /home/marcus/go/pkg/mod/github.com/gobwas/ws@v1.0.2/wsutil/reader.go:98 +0xb2
  bytes.(*Buffer).ReadFrom()
      /usr/lib/go/src/bytes/buffer.go:207 +0x164
  github.com/chromedp/chromedp.(*Conn).bufReadAll()
      /home/marcus/go/pkg/mod/github.com/chromedp/chromedp@v0.4.0/conn.go:90 +0xcb
  github.com/chromedp/chromedp.(*Conn).Read()
      /home/marcus/go/pkg/mod/github.com/chromedp/chromedp@v0.4.0/conn.go:115 +0x197
  github.com/chromedp/chromedp.(*Browser).run.func1()
      /home/marcus/go/pkg/mod/github.com/chromedp/chromedp@v0.4.0/browser.go:254 +0x11f

Goroutine 16 (running) created at:
  main.devToolHandler()
      /home/marcus/git/netsecured/tooling/chrome-resolver/cmd/chromedp-network-intercept/main.go:31 +0x60
  github.com/chromedp/chromedp.(*Conn).Read()
      /home/marcus/go/pkg/mod/github.com/chromedp/chromedp@v0.4.0/conn.go:120 +0x5ae
  github.com/chromedp/chromedp.(*Browser).run.func1()
      /home/marcus/go/pkg/mod/github.com/chromedp/chromedp@v0.4.0/browser.go:254 +0x11f

Goroutine 14 (running) created at:
  github.com/chromedp/chromedp.(*Browser).run()
      /home/marcus/go/pkg/mod/github.com/chromedp/chromedp@v0.4.0/browser.go:247 +0xfc
```

Your impression was correct, there is a data race. I can eliminate this when I comment the range loop in my devToolHandler function. Even tough I do not fully understand this error. The slice of interfaces `is ...interface{}` only ever has one item per function call.

**Comment by mvdan** [comment] 2019-11-27 14:12
I think the right solution here would be: if you want to use a goroutine in the logf callback, any values you want to use asynchronously need to be copied entirely. That is, you cannot use some of the shared memory later, as otherwise you end up with data races.

This issue is a bit old, and there's a data race involved which means it's not clear to me that there's something we can fix. I'm closing it for now, but feel free to open another issue if you have a particular suggestion on what we could fix.

**Closed by mvdan** 2019-11-27 14:12 UTC
