### ISSUE TITLE
Can't launch secondary profile

### ISSUE THREAD

**Issue by Thucydide3** [chromedp/chromedp#912] opened 2021-09-09 17:33 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ g
93.0.4577.63
$ go version
go version go1.17 windows/amd64
```

#### What did you do? Include clear steps.

```package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
opts := append(chromedp.DefaultExecAllocatorOptions[:],
		//chromedp.UserDataDir(``),
		chromedp.UserDataDir(`DIR`),
		chromedp.Flag("profile-directory", "PROFILE N"),
		chromedp.Flag("disable-extensions", false),
		chromedp.Flag("headless", false),
		chromedp.Flag("enable-automation", true),
		chromedp.Flag("new-window", true),
	)
	actx, erro := chromedp.NewExecAllocator(context.Background(), opts...)
	if erro != nil {
		log.Println(erro)
	}
	ctx, cancel := chromedp.NewContext(actx)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	err := chromedp.Run(ctx,
		chromedp.Navigate(`URL`),
)
if err != nil {
		log.Fatal(err)
	}
}

```

#### What did you expect to see?
I expected chrome to open in the profile defined and access the URL

#### What did you see instead?
It opened chrome with the right profile but on an about:blank page.
I get the error "chrome failed to start: Ouverture dans une session de navigateur existante" (which tranlates to "Opening in an existing browser session")
Same result on the default profile.
But it works when no profile is defined: an anonymous window opens and goes through the steps.

**Comment by ZekeLu** [comment] 2021-09-10 04:55
I have reproduced the issue. The original error message is:

>  chrome failed to start:
> Opening in existing browser session.

I guess that's because you already have a browser running with the same `user-data-dir`. So a new browser instance won't be started. Instead, it opens a new window (or new  tab?) in the existing browser session.

Closing all the browser instances before running this app should address the issue.

BTW, the second return value of `chromedp.NewExecAllocator` is not an error. It's a instance of `context.CancelFunc`.

**Comment by Thucydide3** [comment] 2021-09-10 07:27
Ah you're right, I have to close all the sessions, but for all the users, not just the profile I have to use, and it works.
That's going to complicate things at bit but at least it's launching.
Thank you for our answer and thank you for catching my mistake on chromedp.NewExecAllocator.

**Comment by ZekeLu** [comment] 2021-09-10 11:14
>  I have to close all the sessions, but for all the users, not just the profile I have to use

Yeah, that's how Chrome works.  We can observe this behavior with these steps (tested on my Ubuntu only):

1. Start a chrome instance: `google-chrome`
2. Start another one:  `google-chrome --remote-debugging-port=0 --profile-directory=pn`. The output in the  terminal is `Opening in existing browser session.` and the remote debugging is not enabled.
3. Start one more: `google-chrome --remote-debugging-port=0 --profile-directory=pn --user-data-dir=/tmp/chrome-test`. The output in  the terminal is `DevTools listening on ws://127.0.0.1:38319/devtools/browser/...`. Remote debugging is enabled in this case.

There is nothing more to do here. So closing.

**Closed by ZekeLu** 2021-09-10 11:14 UTC
