### ISSUE TITLE
can't be install as v0.8.1

### ISSUE THREAD

**Issue by iepngs** [chromedp/chromedp#1064] opened 2022-05-06 02:32 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.1
$ google-chrome --version
98.0.4758.102
$ go version
go version go1.13.5 windows/amd64
```

#### What did you do? Include clear steps.
PS C:\Users\admin\Desktop\spider> go mod init spider
PS C:\Users\admin\Desktop\spider> go get github.com/chromedp/chromedp
..\..\go\pkg\mod\github.com\chromedp\chromedp@v0.8.1\emulate.go:5:2: found packages device (device.go) and main (gen.go) in C:\Users\admin\go\pkg\mod\github.com\chromedp\chromedp@v0.8.1\device
..\..\go\pkg\mod\github.com\chromedp\chromedp@v0.8.1\input.go:9:2: import "github.com/chromedp/chromedp/kb" is a program, not an importable package

package can't be install

**Comment by ZekeLu** [comment] 2022-05-06 03:04
Closing as duplicate of #1062.

BTW,  go1.13.5 is too old.

**Closed by ZekeLu** 2022-05-06 03:04 UTC
