### ISSUE TITLE
window.showOpenFilePicker() This will ever be implemented in chromedp?

### ISSUE THREAD

**Issue by mx1234567mx** [chromedp/chromedp#1364] opened 2023-10-02 06:55 UTC
Do I understand correctly that now there is no way to use the functions listed below to automate opening dialogs, passing values to them and getting results?

window.showOpenFilePicker()
window.showSaveFilePicker()
window.showDirectoryPicker()

Is it possible to hope that this will ever be implemented in chromedp?

**Comment by ZekeLu** [comment] 2023-10-03 06:36
Closing as a duplicate of #528.

**Closed** 2023-10-03 06:36 UTC
