### ISSUE TITLE
Cannot convert expression of type 'map[string]interface{}' to type 'Headers'

### ISSUE THREAD

**Issue by blue2018** [chromedp/chromedp#696] opened 2020-09-13 07:02 UTC
github.com/chromedp/chromedp  0.5.3
google-chrome  85.0.4183.102
go version 1.15.2

When i run the example for headers（https://github.com/chromedp/examples/blob/master/headers/main.go）, it showed the following message：
"Cannot convert expression of type 'map[string]interface{}' to type 'Headers' "
Any solution？Thanks a lot！

**Comment by ryanerwin** [comment] 2020-11-02 00:54
FYI, this works fine for me...

```
# Chromium v86...
 ~/go1.15.2/src/github.com/chromedp/examples > master $ chromium --version
Chromium 86.0.4240.111 snap

# Go v1.15.2 (also worked fine on v1.13.8)
 ~/go1.15.2/src/github.com/chromedp/examples > master $ go1.15.2 run ./headers/main.go 

2020/11/02 07:51:13 

received headers: { 
"Accept": [ "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ], 
"Accept-Encoding": [ "gzip, deflate, br" ], 
"Accept-Language": [ "en-US" ], 
"Connection": [ "keep-alive" ], 
"Sec-Fetch-Dest": [ "document" ], 
"Sec-Fetch-Mode": [ "navigate" ], 
"Sec-Fetch-Site": [ "none" ], 
"Sec-Fetch-User": [ "?1" ], 
"Upgrade-Insecure-Requests": [ "1" ], 
"User-Agent": [ "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4240.111 Safari/537.36" ], 
"X-Header": [ "my request header" ] }
```

Note I'm on Ubuntu 20.04... Perhaps it's an OS specific issue?

**Comment by blue2018** [comment] 2020-11-02 01:54
> FYI, this works fine for me...
> 
> ```
> # Chromium v86...
>  ~/go1.15.2/src/github.com/chromedp/examples > master $ chromium --version
> Chromium 86.0.4240.111 snap
> 
> # Go v1.15.2 (also worked fine on v1.13.8)
>  ~/go1.15.2/src/github.com/chromedp/examples > master $ go1.15.2 run ./headers/main.go 
> 
> 2020/11/02 07:51:13 
> 
> received headers: { 
> "Accept": [ "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ], 
> "Accept-Encoding": [ "gzip, deflate, br" ], 
> "Accept-Language": [ "en-US" ], 
> "Connection": [ "keep-alive" ], 
> "Sec-Fetch-Dest": [ "document" ], 
> "Sec-Fetch-Mode": [ "navigate" ], 
> "Sec-Fetch-Site": [ "none" ], 
> "Sec-Fetch-User": [ "?1" ], 
> "Upgrade-Insecure-Requests": [ "1" ], 
> "User-Agent": [ "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4240.111 Safari/537.36" ], 
> "X-Header": [ "my request header" ] }
> ```
> 
> Note I'm on Ubuntu 20.04... Perhaps it's an OS specific issue?

It is possible, I tested it on win10 system~_~

**Comment by ysmood** [comment] 2020-11-02 05:16
@blue2018 I wonder if you have the same problem with rod:

https://github.com/go-rod/rod/blob/master/lib/examples/compare-chromedp/headers/main.go

If you can reproduce it with rod, then I think I may help to figure out why.

**Comment by ysmood** [comment] 2020-11-02 05:20
@ryanerwin I can confirm the same issue on mac 10.15.7, golang 1.15, chrome 86.0.4240.111.

**Comment by ZekeLu** [comment] 2021-02-08 12:36
There was an issue in the `github.com/chromedp/cdproto/network` package, and it has been fixed in this [commit](https://github.com/chromedp/cdproto/commit/82dd5aea4c2632bc151af34551b999438b5d08db#diff-03e3126d453d7bebfce9118897e3b6f3ce8db01442ab14022040f36aba43534a). 

Here is the change in that commit:

```diff
diff --git a/network/types.go b/network/types.go
index d6fa0e8..b677377 100644
--- a/network/types.go
+++ b/network/types.go
@@ -202,7 +202,7 @@ func (t *ErrorReason) UnmarshalJSON(buf []byte) error {
 // Headers request / response headers as keys / values of JSON object.
 //
 // See: https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Headers
-type Headers easyjson.RawMessage
+type Headers map[string]interface{}
```

It's very likely that the error is caused by this issue. Please confirm it by checking the source code of `network/types.go` in the `github.com/chromedp/cdproto` module on your machine. You can find out the location of the source code with the `go list` command.

```shell
$ cd headers
$ go list -f '{{.Dir}}' github.com/chromedp/cdproto/network
~/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20210104223854-2cc87dae3ee3/network
$ grep 'type Headers ' ~/go/pkg/mod/github.com/chromedp/cdproto@v0.0.0-20210104223854-2cc87dae3ee3/network/types.go
type Headers map[string]interface{}
```

**Comment by ZekeLu** [comment] 2021-04-27 08:31
chromedp@0.5.3 depends on github.com/chromedp/cdproto@v0.0.0-20200116234248-4da64dd111ac, which has this issue. And the issue has been fixed in https://github.com/chromedp/cdproto/commit/82dd5aea4c2632bc151af34551b999438b5d08db.

**Closed by ZekeLu** 2021-04-27 08:31 UTC
