### ISSUE TITLE
call chromedp.Text with chromedp.AtLeast(0) will be hanged in goroutine sometimes

### ISSUE THREAD

**Issue by yjc173** [chromedp/chromedp#685] opened 2020-08-17 09:51 UTC
Hello everyone, when I call the following code in the goroutine, I find it will be blocked (Not certainly,but Easy to reproduce):

`chromedp.Text("#itemName", &strProductName, chromedp.AtLeast(0), chromedp.ByID).Do(ctx)`

![image](https://user-images.githubusercontent.com/23473645/90381474-04588f00-e0b0-11ea-9523-83fb07f739f8.png)

![image](https://user-images.githubusercontent.com/23473645/90381512-0e7a8d80-e0b0-11ea-9813-54b7f40d20d7.png)

![image](https://user-images.githubusercontent.com/23473645/90380404-9364a780-e0ae-11ea-8498-8f3f9b2ab48a.png)

This is a puzzling question,I spent a lot of time, but I can't solve this problem. My English is very poor, I am afraid that too many descriptions will mislead you, the complete project is on 
[https://github.com/yjc173/test-demo](https://github.com/yjc173/test-demo)

I hope someone can help me answer this question, thank you very much. @mvdan

**Comment by mvdan** [comment] 2020-08-17 09:58
Please don't ping me directly.

**Comment by yjc173** [comment] 2020-08-17 11:06
> Please don't ping me directly.

Sorry for the inconvenience.This is the first time I use the Issues function and I am not familiar with it,Apologize again for my recklessness.

**Comment by ZekeLu** [comment] 2021-05-06 08:55
@yjc173 There are quite a  lot of changes since `v0.5.3`. Can you have a test with the latest version?

If you can reproduce with the latest `chromedp`, please enable the debug log and share the log here. Thank you!

**Comment by ZekeLu** [comment] 2021-05-21 04:58
The image shows that there could be a deadlock or lock contention. I'm interested to look into this issue. I have tried several times, but can not reproduce the issue. And I found that it will send many requests to a public service for a single run. That's not what we should do. Since there is not a way to reproduce the issue reliably without sending many requests to a public service, I will close this issue for now.

**Comment by yjc173** [comment] 2021-05-27 02:29
> The image shows that there could be a deadlock or lock contention. I'm interested to look into this issue. I have tried several times, but can not reproduce the issue. And I found that it will send many requests to a public service for a single run. That's not what we should do. Since there is not a way to reproduce the issue reliably without sending many requests to a public service, I will close this issue for now.


![gotest](https://user-images.githubusercontent.com/23473645/119756286-e9843800-bed5-11eb-86f0-c8d72b665143.jpg)
Thank you so much for your help!!!
Adding this line of code seems to solve the problem,Thanks again for your help.

**Comment by yjc173** [comment] 2021-05-27 02:33
[image: gotest]
<https://user-images.githubusercontent.com/23473645/119756286-e9843800-bed5-11eb-86f0-c8d72b665143.jpg>
Thank you so much for your help!!!
Adding this line of code seems to solve the problem,Thanks again for your
help.

Zeke Lu ***@***.***> 于2021年5月21日周五 下午12:58写道：

**Comment by ZekeLu** [comment] 2021-05-27 03:13
@yjc173 Thanks for sharing the information. It's still hard to reproduce the issue.

Since you can reproduce the issue, do you like to debug it? the [pprof](https://golang.org/pkg/net/http/pprof/) tool may help in this case. We want to take a look at the holders of contended mutexes in this case.

**Closed** 2021-06-04 02:55 UTC
Labels: needs info
