### ISSUE TITLE
child process not reaped 

### ISSUE THREAD

**Issue by takakawa** [chromedp/chromedp#894] opened 2021-08-04 14:08 UTC
when running in docker after a while, there are many many process left defunct

![image](https://user-images.githubusercontent.com/6322274/128195566-f16d91ed-16af-4ce3-b1f8-4307ebfce341.png)

**Comment by ZekeLu** [comment] 2021-08-04 14:49
see #752

You can do two things to make it better:

1. specify the init process to reape the zombie processes: https://docs.docker.com/engine/reference/run/#specify-an-init-process
2. try to use a single browser instance and create new tabs in it

https://github.com/chromedp/chromedp/blob/40faabd665deb87f18010449cd7c86d0682bc491/chromedp_test.go#L112-L113

**Comment by ZekeLu** [comment] 2021-10-16 02:14
Closing as a duplicate of #752

**Closed by ZekeLu** 2021-10-16 02:14 UTC

**Comment by dpanic** [comment] 2024-01-26 00:30
I have the same problem.

I even did reaping my self
``` Go

func init() {
	// Setting up a channel to receive system signals
	sigs := make(chan os.Signal, 1)

	// Notify sigs channel on SIGCHLD
	signal.Notify(sigs, syscall.SIGCHLD)

	// Goroutine to handle received signals
	go func() {
		for {
			sig := <-sigs
			logger.Logger.Info("received signal",
				zap.String("signal", sig.String()),
			)

			if sig == syscall.SIGCHLD {
				// Reap zombie processes
				for {
					// Use Wait4 to reap child processes
					pid, err := syscall.Wait4(-1, nil, syscall.WNOHANG, nil)
					if err != nil {
						break
					}

					logger.Logger.Warn("reaped PROCESS",
						zap.Int("pid", pid),
					)
				}
			}
		}
	}()
}
```

I start Chrome in non headless mode this way:
``` Go

	opts := make([]chromedp.ExecAllocatorOption, 0)
	opts = append(opts, chromedp.DefaultExecAllocatorOptions[:]...)

	// Configure options for the Chrome browser instance.
	opts = append(opts,
		chromedp.CombinedOutput(log.Writer()),
		// chromedp.Flag("enable-logging", true),
		// chromedp.Flag("v", "1"),
		chromedp.DisableGPU,
		chromedp.NoDefaultBrowserCheck,
		chromedp.NoSandbox,
		chromedp.IgnoreCertErrors,
		chromedp.NoFirstRun,

		chromedp.Flag("hide-scrollbars", true),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("disable-blink-features", "AutomationControlled"),
		chromedp.Flag("disable-popup-blocking", false),
		chromedp.Flag("disable-web-security", true),
		chromedp.Flag("shm-size", "128m"),
		chromedp.Flag("safebrowsing-disable-auto-update", true),
		chromedp.Flag("safebrowsing-disable-download-protection", true),
		chromedp.Flag("allow-running-insecure-content", true),
		chromedp.Flag("mute-audio", true),

		chromedp.UserDataDir(dir),
	)

	// determine headless
	switch *r.Headless {
	case true:
		opts = append(opts, []chromedp.ExecAllocatorOption{
			chromedp.Flag("headless", true),
			chromedp.Flag("single-process", true),
		}...)

	case false:
		opts = append(opts, []chromedp.ExecAllocatorOption{
			chromedp.Flag("headless", false),
		}...)
	}
```
