### ISSUE TITLE
Screenshot misbehaves when using large scaling factors, such as on high-DPI screens

### ISSUE THREAD

**Issue by alai04** [chromedp/chromedp#191] opened 2018-05-21 15:54 UTC
I modified the simple example to saving a screenshot on github.com, and get a 1/2width 1/2height image like:
![screenshot](https://user-images.githubusercontent.com/1415027/40316201-235d8332-5d50-11e8-8104-71308e2bd9ce.png)
The screenshot should be:
<img width="573" alt="2018-05-21 11 46 43" src="https://user-images.githubusercontent.com/1415027/40316793-05a5125e-5d52-11e8-9f27-bda7a01e2738.png">

the code:
```
package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/chromedp"
)

func main() {
	var err error

	// create context
	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	// create chrome instance
	c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf))
	if err != nil {
		log.Fatal(err)
	}

	// run task list
	url := `https://github.com/`
	sel := `div.col-md-7.text-center.text-md-left`
	pngFile := "screenshot.png"
	err = c.Run(ctxt, screenshot(url, sel, pngFile))
	if err != nil {
		log.Fatal(err)
	}

	// shutdown chrome
	err = c.Shutdown(ctxt)
	if err != nil {
		log.Fatal(err)
	}

	// wait for chrome to finish
	err = c.Wait()
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("saved screenshot from `%s` (%s)", url, sel)
}

func screenshot(url, sel, file string) chromedp.Tasks {
	var buf []byte
	return chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.WaitVisible(sel, chromedp.ByQuery),
		chromedp.Screenshot(sel, &buf, chromedp.ByQuery),
		chromedp.ActionFunc(func(context.Context, cdp.Executor) error {
			return ioutil.WriteFile(file, buf, 0644)
		}),
	}
}
```
I am on macos 10.13.4 with Chrome Version 66.0.3359.181 (64-bit)
What's wrong? thx

**Comment by kenshaw** [comment] 2018-05-21 23:36
Are you perhaps using a 4k (or other high density) display? If its exactly 1/2 in each direction, it sounds to me like a scaling issue. The fix to that would be to change the scaling in Chrome. You might want to look at the `emulation` domain, specifically the `Emulation.setDeviceMetricsOverride` call. Again, I'm only shooting in the dark here -- I don't really have an easy way to test this, as I don't have a Mac that's new-ish enough.

Also, keep in mind I'm only taking a stab in the dark as to what the problem is. Another way to test this hypothesis would be to go into the system settings and force a non-scaled UI.

**Comment by alai04** [comment] 2018-05-22 01:58
Yes, my display is 2K(2560x1600).
I will try the ```Emulation.setDeviceMetricsOverride```

**Comment by figoxu** [comment] 2018-07-07 01:12
How To Import Emulation For "Emulation.setDeviceMetricsOverride"

**Comment by wuzuf** [comment] 2018-09-30 18:11
Hi, I stumbled on the same problem and managed to find a way, but it needs an update directly in chromedp. The trick is to use `window.devicePixelRatio`.

What I did locally is to patch this to get the DPI value from the browser (in `js.go`):
```
scrollJS = `(function(x, y) {
		window.scrollTo(x, y);
		return [window.scrollX, window.scrollY, window.devicePixelRatio];
	})(%d, %d)`
```

Then use it when cropping the PNG file returned by chrome (in `query.go`):

```
// crop to box model contents
cropped := imaging.Crop(img, image.Rect(
   (int(box.Margin[0])-pos[0])*pos[2], (int(box.Margin[1])-pos[1])*pos[2],
    (int(box.Margin[4])-pos[0])*pos[2], (int(box.Margin[5])-pos[1])*pos[2],
))
```

I will try when I find time to propose a PR. I don't have everything setup at the moment to properly run the tests.

**Comment by mvdan** [comment] 2019-04-23 17:42
@wuzuf are you still interested in sending a PR? To run the tests, all you need is having a somewhat recent version of Chrome installed. `go test` runs in about four seconds on my ultrabook. The PR should have a test as well.

**Comment by mvdan** [comment] 2019-05-07 17:03
Well, I don't have a Mac machine to test/debug this, and the issue seems to have stalled, so I'm closing for now. If anyone can reproduce this issue in master, even after using `Emulation.setDeviceMetricsOverride`, please open a new issue. Or even better, if you find a bug, send a PR.

**Comment by wuzuf** [comment] 2019-05-08 07:26
@mvdan sorry for not following up on this comment. Actually, the tests are failing on OSX (as far as I remember, some tests with "keys", it seems chrome on osx has different behaviors when you use arrows to navigate into a dropdowns). So I gave up, as I could not find an easy way to make the tests pass.
Note that I suspect this will happen on any laptop with high density display, but won't know for sure. Good to keep this issue in your mind for future reference...

**Comment by mvdan** [comment] 2019-05-08 07:56
Yes, some of the input tests fail on Mac sort of by design, but we don't have access to a reliable Mac machine (like on CI) to test this on.

And actually, I can reproduce this on my 2560x1440 laptop (at 1.5x dpi, 144) with the following program on master:

```
// +build ignore

package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background(),
		chromedp.WithLogf(log.Printf))
	defer cancel()

	// run task list
	url := `https://github.com/`
	sel := `div.col-md-7.text-center.text-md-left`
	pngFile := "screenshot.png"
	if err := chromedp.Run(ctx, screenshot(url, sel, pngFile)); err != nil {
		log.Fatal(err)
	}

	log.Printf("saved screenshot from `%s` (%s)", url, sel)
}

func screenshot(url, sel, file string) chromedp.Action {
	var buf []byte
	return chromedp.Tasks{
		chromedp.Navigate(url),
		chromedp.WaitVisible(sel, chromedp.ByQuery),
		chromedp.Screenshot(sel, &buf, chromedp.ByQuery),
		chromedp.ActionFunc(func(context.Context) error {
			return ioutil.WriteFile(file, buf, 0644)
		}),
	}
}
```

It also errors out on master initially; I had to tweak some of the float math to get it to output the cropped screenshot.

I can now reproduce this on Linux, so at least the bug is verified and I can debug it.

**Comment by mvdan** [comment] 2019-05-08 14:44
Ok, this is now properly fixed. Please test it. I carefully wrote a test to verify that this works on my machine, so I'm pretty confident that the original issue is fixed.

**Closed** 2019-05-08 14:43 UTC

**Comment by wuzuf** [comment] 2019-05-08 15:37
I can confirm your test passes on my macbook. And your option to use directly chrome is of course great.
I had dropped what I was trying to do with chromedp, now it makes me willing to try again. Thanks for the fix!

**Comment by tmm1** [comment] 2019-05-21 23:56
I'm using `chromedp.CaptureScreenshot()` and it still has this issue.

**Comment by wuzuf** [comment] 2019-05-22 05:48
@tmm1 if you share a way to reproduce your issue I can run it on my Mac to check.
On which OS/Go/chromedp versions are you?
