### ISSUE TITLE
SendKeys hangs and can't find input field that is clearly there

### ISSUE THREAD

**Issue by mschilli** [chromedp/chromedp#545] opened 2020-01-01 20:01 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.2
$ google-chrome --version
Google Chrome 78.0.3904.108
$ go version
go version go1.12.5 darwin/amd64
</pre>

#### What did you do? Include clear steps.

The main search page on duckduckgo.com features a text input field named "q":

```
<form id="search_form_homepage_top" class="search  search--home  js-search-form-top" name="x" method="POST" action="/html">
			<input class="search__input  js-search-input" type="text" autocomplete="off" name="q" tabindex="1" value="">
			<input class="search__button  js-search-button" type="submit" tabindex="2" value="S" />
			<input class="search__clear  empty  js-search-clear" type="button" tabindex="3" value="X" />
			<div class="search__hidden  js-search-hidden"></div>
		</form>
```
so let's try to use SendKeys() to paste text into it:

```
package main

import (
  "context"
  "github.com/chromedp/chromedp"
  "log"
)

func main() {
  ctx, cancel := chromedp.NewContext(
      context.Background(), chromedp.WithDebugf(log.Printf))
  defer cancel()

  sel := `//input[@name="q"]`
  tasks := chromedp.Tasks{
    chromedp.Navigate(
      "https://duckduckgo.com"),
    chromedp.WaitReady("body", chromedp.ByQuery),
    chromedp.SendKeys(sel, "waaah\n", chromedp.ByQuery),
    chromedp.WaitReady("body", chromedp.ByQuery),
  }

  err := chromedp.Run(ctx, tasks)
  if err != nil {
    panic(err)
  }
}
```

#### What did you expect to see?

The selector `//input[@name="q"]` should find the item.

#### What did you see instead?

Debug output indicates it's searching forever without finding it:

```
2020/01/01 12:58:48 -> {"id":143,"sessionId":"CF5A3F56D987CA6FEA082B76D810F060","method":"DOM.querySelector","params":{"nodeId":14,"selector":"//input[@name=\"q\"]"}}
2020/01/01 12:58:48 <- {"error":{"code":-32000,"message":"DOM Error while querying"},"id":143,"sessionId":"CF5A3F56D987CA6FEA082B76D810F060"}
```

This seems to be related to https://github.com/chromedp/chromedp/issues/540, hopefully this easily reproducable example helps to find the root cause.

**Comment by mvdan** [comment] 2020-01-06 05:20
`DOM Error while querying` should be giving you a clue here. Your syntax seems wrong for ByQuery, which *only* accepts CSS selectors.

`input[name="q"]` works for me. In your browser's console, you can see how `document.querySelector('input[name="q"]')` works, but it doesn't when it's fed your query selector.

Alternatively, if you really want to use the XPath syntax, you need to use `BySearch`, which is the default. There, I can see via the debug logs that `//input[@name="q"]` returns two nodes; I'm not sure why that's the case. The program gets stuck there. I haven't investigated further, since `ByQuery` works fine, but you can debug where the problem is if you want.

This is all documented in https://godoc.org/github.com/chromedp/chromedp#hdr-By_Options.

Admittedly, we could do a better job at not looping forever in the clear cases where a query has invalid syntax. It wouldn't make your original code work, but at least it would give you a somewhat useful error.

**Comment by mschilli** [comment] 2020-01-09 01:32
Thanks for the response! Looks like we have a two cases now:

1. input[name="q"] + ByQuery: works
2. //input[@name="q"] + BySearch: does not work (you're saying it finds two nodes, but it shouldn't, and I can't really make sense of the debug logs)

**Comment by mvdan** [comment] 2020-01-09 01:49
From the docs:

> BySearch is an element query option to select elements by the DOM.performSearch command. Works with both CSS and XPath queries. 

It really just sends your selector to https://godoc.org/github.com/chromedp/cdproto/dom#PerformSearch. So if it's doing something weird, you could poke at that. I'd also imagine that other Chrome devtools software like Puppeteer would get the same result.

You can also use https://godoc.org/github.com/chromedp/chromedp#Nodes to actually inspect the results the selector gets. `SendKeys` picks the first result, so my guess is that the node where one could actually send keys is the second result instead of the first.

**Comment by anschuh11** [comment] 2021-02-05 19:52
Hi,

I have the same issue in one of my Selenium scripts. But the error is not happening _all_ the time. Some runs are OK and then the next is failing with the error "{"code":-32000,"message":"DOM Error while querying"}"
I have to use Selenium IDE, because I need the SIDE file to integrate with another monitoring tool. So I cannot use Java or JavaScript :| 
Attached a screenshot from my script. 
Command 16 opens a new window in which I then try to enter the text and the ENTER key in the search field identified by the full xpath. It finds the search field in the "wait for element editable", but in the next step when I try to use sendKeys it fails. 

![Error_DOM_New_Window](https://user-images.githubusercontent.com/78618147/107081973-80ab6f80-67c1-11eb-851f-be73888a0389.png)

I'm quite new to Selenium and try to figure out how to debug this. But I'm a little bit out of ideas what to do with this. 

Thanks!
Andrea

**Comment by ZekeLu** [comment] 2021-05-14 10:38
@anschuh11 It seems that you came to the wrong place. Maybe you wanted to go to https://github.com/SeleniumHQ/selenium-ide.

The OP's issue should have been addressed. Closing.

**Closed by ZekeLu** 2021-05-14 10:38 UTC
