### ISSUE TITLE
Invalid parameters with fetch.ContinueRequest

### ISSUE THREAD

**Issue by nathankodilla** [chromedp/chromedp#1058] opened 2022-04-28 02:08 UTC
**What versions are you running?**
v0.7.8

```
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.8
$ google-chrome --version
98.0.4758.102
$ go version
go version go1.17.1 windows/amd64
```

**What did you do? Include clear steps.**
```go
chromedp.ListenTarget(ctx, func(ev interface{}) {
		switch ev := ev.(type) {
		case *fetch.EventRequestPaused:
			go func() {
				c := chromedp.FromContext(ctx)
				e := cdp.WithExecutor(ctx, c.Target)

				...

				var res []*fetch.HeaderEntry
				for k, v := range ev.Request.Headers {
					res = append(res, &fetch.HeaderEntry{Name: k, Value: fmt.Sprintf("%v", v)})
				}
				req := fetch.ContinueRequest(ev.RequestID).WithURL(ev.Request.URL).WithMethod(ev.Request.Method).WithHeaders(res).WithPostData(rawJson)

				if err := req.Do(e); err != nil {
					log.Printf("Failed to continue request: %v", err)
				}
			}()
		}
	})
```

**What did you expect to see?**

Request continues with provided parameters. The intent is to only modify the request body and then send along the request.

**What did you see instead?**

Invalid parameters. (-32602) error on req.Do(e). It does not spit out what is invalid parameter or if something is missing.

**Comment by ZekeLu** [comment] 2022-04-28 02:52
Duplicate of #719.

The body should be encoded as base64 string.

**Comment by nathankodilla** [comment] 2022-04-28 03:13
Thanks @ZekeLu . That got me past this error. However, the modified body is not actually being modified in the request. If I pop open the network tab in chrome and look at the request, the body is still the original body and not my new one. What else could I be doing wrong here?

(I have confirmed the modified body base64 encoded string is being put correctly into WithPostData)

**Comment by ZekeLu** [comment] 2022-04-28 04:55
Can you provide a simple reproducer?

**Closed** 2022-05-10 01:59 UTC

**Comment by ZekeLu** [comment] 2022-05-10 02:43
@nathankodilla I would like to get your feedback. Since you closed the issue, I assume that you have addressed the issue. Can you share the information? Thank you!
