### ISSUE TITLE
Some pages request to load more content, and the response time is too long, resulting in a long-time program jam

### ISSUE THREAD

**Issue by Mieiu** [chromedp/chromedp#951] opened 2021-11-17 06:43 UTC
How to set the response timeout of 5 seconds after requesting a page and take a screenshot directly without waiting for the page to load

代码：
package main
import (
	"context"
	"fmt"
	"io/ioutil"
	"log"
	"github.com/chromedp/chromedp"
)
func oo1() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()
	var buf []byte
	if err := chromedp.Run(ctx,
		chromedp.Navigate(`http://www.ou88.cn`),// or http://114.113.152.184/
		chromedp.FullScreenshot(&buf, 90),
	); err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("fullScreenshot.jpeg", buf, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote fullScreenshot.jpeg")
}

**Comment by ZekeLu** [comment] 2021-11-17 06:58
Closing as duplicate of #924.

**Closed by ZekeLu** 2021-11-17 06:58 UTC
