### ISSUE TITLE
‘chromedp/examples text’ Not work

### ISSUE THREAD

**Issue by lovelly** [chromedp/chromedp#480] opened 2019-10-05 07:08 UTC
#### What versions are you running?

<pre>
> go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.1.4-0.20190408165214-b481eeac5108
>go version
go version go1.13.1 windows/amd64
</pre>

#### What did you do? Include clear steps.
https://github.com/chromedp/examples/blob/master/text/main.go
in the example. go run main.go

#### What did you expect to see?
Get output

#### What did you see instead?
No output

**Comment by rof20004** [comment] 2019-10-05 18:31
Same problem here, did you get a solution?

**Comment by kenshaw** [comment] 2019-10-05 23:29
I'm not able to reproduce this. There's absolutely no output from this example? At minimum, if it doesn't work, there should be an error or some such. Please try updating to the latest version (I just pushed a new version with the most updated dependencies), and try again.

**Comment by rof20004** [comment] 2019-10-06 00:13
@kenshaw 

I tried to use the Text example and It freezes, I will try to reproduce a video and share here, tomorrow maybe or monday.

**Comment by kenshaw** [comment] 2019-10-06 04:19
Ok, let me know.

**Comment by mvdan** [comment] 2019-10-07 15:22
Works here as well, so we have no way to debug or reproduce.

**Comment by lovelly** [comment] 2019-10-08 02:21
When the domain name is invalid, or when the id selector does not hit, there is no output or error.

**Comment by rof20004** [comment] 2019-10-14 11:56
@kenshaw 

I tried the example and worked.

The URL I am trying to use is this: https://www.linkedin.com/company/visteon

I want to get the company name, but I saw that div id change always. Sometimes is ember61 than later change to ember62. I think chromedp not found the div id and stuck.

If you want to try, I need only to get the company name inside HTML.

I will share my code tonight.

Thanks :)

**Comment by JabinGP** [comment] 2019-10-15 13:39
@mvdan 
Hi,I got the same problem in macOS 10.13.6 and DeepinLinux 15.11, chromedp version is the latest 0.4.2

I tried the example and worked.

I want to get some error output,  i try to replace div id, but i can not got any output , it just stuck.

If the div id is exist in the html dom, chromedp will give me the right return,but I also want it can give me some error output  when the div id is not exist.

Here is my code

```go
// Command text is a chromedp example demonstrating how to extract text from a
// specific element.
package main

import (
	"context"
	"log"
	"strings"

	"github.com/chromedp/chromedp"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// run task list
	var res string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://golang.org/pkg/time/`),
		chromedp.Text(`#123`, &res, chromedp.NodeVisible, chromedp.ByID),
	)
	if err != nil {
		log.Fatal(err)
	}

	log.Println(strings.TrimSpace(res))
}
```

**Comment by rof20004** [comment] 2019-10-15 13:43
@JabinGP Thanks for share, I forgott to share my code, hehehe :)

I think is the same error.

**Comment by nsallis** [comment] 2019-10-29 16:10
The example has been updated. "#123" no longer exists on the page. They are now using #pkg-overview.

**Comment by mvdan** [comment] 2019-11-06 21:37
This issue is getting a bit off-topic; it still seems to me like the current example works, so I'm going to close the issue for now.

If you want to detect when a query doesn't work, use a timeout:

```
ctx := chromedp.New(...)
tctx, cancel := context.WithTimeout(ctx, time.Second)
if err := chromedp.Run(tctx, chromedp.Text(...)); err != nil {
    if tctx.Err() != nil {
        // we hit the timeout
    } else {
        // we hit some chromedp error
    }
}
```

**Closed by mvdan** 2019-11-06 21:37 UTC
Labels: needs info
