### ISSUE TITLE
Disable stacktraces when download error

### ISSUE THREAD

**Issue by nnguyent** [chromedp/chromedp#854] opened 2021-06-09 18:40 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.3
$ google-chrome --version
{
  "Browser": "Chrome/92.0.4515.40",
  "Protocol-Version": "1.3",
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.40 Safari/537.36",
  "V8-Version": "9.2.230.5",
  "WebKit-Version": "537.36 (@e9500a4e0a9e3de9322305a043cec3899b867507)",
  "webSocketDebuggerUrl": "ws://localhost:5000/devtools/browser/9a71a123-99d5-47b2-afbe-d9d934c3480f"
}
$ go version
go version go1.16.5 darwin/amd64
```

#### What did you do? Include clear steps.
I'm using chromedp to download file as #807. Sometime I got below events and its stacktrace:
- target.EventTargetCrashed{TargetID:"66AE3552BFAA2D0652816C6FC3C5383C", Status:"crashed", ErrorCode:5}
```
ERROR received error: target event: received crashed event &target.EventTargetCrashed{TargetID:"66AE3552BFAA2D0652816C6FC3C5383C", Status:"crashed", ErrorCode:5}
api/headless.(*headlessClient).downloadByTab.func2
	/app/internal/api/headless/client.go:327
github.com/chromedp/chromedp.runListeners
	/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/util.go:84
github.com/chromedp/chromedp.(*Target).run.func1
	/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/target.go:130
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```
- runtime.EventExceptionThrown{Timestamp:(*runtime.Timestamp)(0xc0004d56f8), ExceptionDetails:(*runtime.ExceptionDetails)(0xc0006eac00)}
```
ERROR received error: target event: received exception &runtime.EventExceptionThrown{Timestamp:(*runtime.Timestamp)(0xc0004d56f8), ExceptionDetails:(*runtime.ExceptionDetails)(0xc0006eac00)}
api/headless.(*headlessClient).downloadByTab.func2
	/app/internal/api/headless/client.go:324
github.com/chromedp/chromedp.runListeners
	/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/util.go:84
github.com/chromedp/chromedp.(*Target).run.func1
	/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/target.go:130
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```
- browser.EventDownloadProgress: &{GUID:21f93245-e834-4795-a32e-81ee17acc4c3 TotalBytes:4.639403e+06 ReceivedBytes:0 State:canceled}
```
ERROR received error: EventDownloadProgress:canceled
api/headless.(*headlessClient).downloadByTab.func2
	/app/internal/api/headless/client.go:338
github.com/chromedp/chromedp.runListeners
	/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/util.go:84
github.com/chromedp/chromedp.(*Target).run.func1
	/go/pkg/mod/github.com/chromedp/chromedp@v0.7.3/target.go:130
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

Source code:
```go
var errChan = make(chan error, 1)
var outputChan = make(chan int)

// create a new tab
tabCtx, tabCancel := context.WithTimeout(c.browserCtx, dTimeout)
tabCtx, tabCancel = chromedp.NewContext(tabCtx)
defer func() {
	close(errChan)
	close(outputChan)

	c.log.Infof("closing tab targetID: %s, sessionID: %s", chromedp.FromContext(tabCtx).Target.TargetID, chromedp.FromContext(tabCtx).Target.SessionID)

	tabCancel()
}()

chromedp.ListenTarget(tabCtx, func(ev interface{}) {
	switch ev := ev.(type) {
	case *cdpruntime.EventConsoleAPICalled:
		if ev.Type == "error" {
			errChan <- errors.Errorf("target event: received error %#v", ev)
		}

	case *cdpruntime.EventExceptionThrown:
		errChan <- errors.Errorf("target event: received exception %#v", ev)

	case *target.EventTargetCrashed:
		errChan <- errors.Errorf("target event: received crashed event %#v", ev)

	case *browser.EventDownloadProgress:
		if ev.State == browser.DownloadProgressStateCanceled {
			errChan <- errors.New(browser.DownloadProgressStateCanceled.String())
		}
	}
})

// Start download file
err = chromedp.Run(
	tabCtx,
	browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(dlDir).WithEventsEnabled(true),
	chromedp.Navigate(dlURL),
)
if err != nil && !strings.Contains(err.Error(), "net::ERR_ABORTED") {
	c.log.Errorf("failed to download file at URL %s. Error: %+v", dlURL, err)
	return err
}

c.log.Infof("created new tab targetID: %s, sessionID: %s", chromedp.FromContext(tabCtx).Target.TargetID, chromedp.FromContext(tabCtx).Target.SessionID)

// Start routine to observe downloaded files
go c.waitDownloadDone(tabCtx, dlDir, outputChan, errChan)

numDlFiles:=0
numErrDownloadProgressStateCanceled:=0
maxErrDownloadProgressStateCanceled:=1

Loop:
for {
	select {
	case <-tabCtx.Done():
		break Loop

	case numDlFiles = <-outputChan:
		break Loop	

	case err = <-errChan:
		c.log.Errorf("received error: %+v", err)
		if err.Error() == browser.DownloadProgressStateCanceled.String() && numErrDownloadProgressStateCanceled < maxErrDownloadProgressStateCanceled {
			err = chromedp.Run(tabCtx, chromedp.Stop())
			if err != nil {
				c.log.Errorf("failed to stop page. Error: %+v", err)
				break Loop
			}

			// Try to download again
			err = chromedp.Run(
				tabCtx,
				browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(dlDir).WithEventsEnabled(true),
				chromedp.Navigate(dlURL),
			)
			if err != nil && !strings.Contains(err.Error(), "net::ERR_ABORTED") {
				c.log.Errorf("failed to download file at URL %s after canceling. Error: %+v", dlURL, err)
				break Loop
			}

			numErrDownloadProgressStateCanceled++
		} else {
			tabCancel()
			break Loop
		}
	}
}
```

#### What did you expect to see?
I hope to skip stacktrace because I have no idea about it. Besides that, does anyone of you know why and what event target.EventTargetCrashed, ErrorCode:5, 9 happen?
I tried to find info in this [link]([https://chromedevtools.github.io/devtools-protocol/tot/Target/#event-targetCrashed]) but it isn't help.

**Comment by ZekeLu** [comment] 2021-06-10 02:02
> I hope to skip stacktrace

I guess you're using `github.com/pkg/errors` which adds stacktrace to the error. So you should check whether there is an option to turn it off or not use it where you don't need the stacktrace.

> why and what event target.EventTargetCrashed, ErrorCode:5, 9 happen?

The [CDP doc](https://chromedevtools.github.io/devtools-protocol/tot/Target/#event-targetCrashed) just says that `Target.targetCrashed` is **issued when a target has crashed**.

Try to turn on Chrome debug logging and see whether you can find more information from the logs:

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	// turn on logging for the browser
	// see https://support.google.com/chrome/a/answer/6271282
	chromedp.Flag("enable-logging", true),
	chromedp.Flag("v", "100"),
	// specify the data dir to store the debug logs.
	// Debug logs are stored in the user data directory as chrome_debug.log.
	// the file is overwritten every time Chrome restarts. So, if you have an
	// issue with the browser, check the log before you restart Chrome
	chromedp.UserDataDir("/path/to/data/dir"),
)
```

---

And there are some issues that you may want to fix:

1. `browser.SetDownloadBehavior` is browser-wide. You just need to call it once on `c.browserCtx`.
2. the parent context of `tabCtx` is a timeout context. It's possible that the previous tries use too much time and there is not enough time left for the next try (ignore this point if that's what you want).

**Comment by nnguyent** [comment] 2021-06-10 04:02
@ZekeLu: Thanks for pointing that out.

> I guess you're using github.com/pkg/errors which adds stacktrace to the error. So you should check whether there is an option to turn it off or not use it where you don't need the stacktrace.

Yes, I'm using it. I changed to ```fmt.Errorf``` to return an error and it doesn't happen. 

> The CDP doc just says that Target.targetCrashed is issued when a target has crashed.

After investigating, I think the error code maybe relating to signals but I didn't found any document to mention these error codes.
```go
SIGTRAP   = Signal(0x5)
SIGKILL   = Signal(0x9)
```

> Try to turn on Chrome debug logging and see whether you can find more information from the logs:
```
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	// turn on logging for the browser
	// see https://support.google.com/chrome/a/answer/6271282
	chromedp.Flag("enable-logging", true),
	chromedp.Flag("v", "100"),
	// specify the data dir to store the debug logs.
	// Debug logs are stored in the user data directory as chrome_debug.log.
	// the file is overwritten every time Chrome restarts. So, if you have an
	// issue with the browser, check the log before you restart Chrome
	chromedp.UserDataDir("/path/to/data/dir"),
)
```

Yes. I'm using the same options to create browser context, however I didn't find any clue for this symption.
```go
opts := []chromedp.ExecAllocatorOption{
	chromedp.ExecPath("/headless-shell/headless-shell"),
	chromedp.UserDataDir(chromedpDataDir),
	chromedp.Flag("enable-logging", true),
	chromedp.Flag("v", "100"),
	chromedp.NoFirstRun,
	chromedp.NoDefaultBrowserCheck,
	chromedp.Headless,
	chromedp.DisableGPU,
}

ctx, _ = chromedp.NewExecAllocator(context.Background(), opts...)
ctx, cancel = chromedp.NewContext(ctx, chromedp.WithLogf(c.log.Infof))

// Ensure browser and first tab is created
if err := chromedp.Run(ctx); err != nil {
cancel()
c.log.Fatal("failed to start browser:", err)
}
c.browserCtx = ctx
```

> 1. browser.SetDownloadBehavior is browser-wide. You just need to call it once on c.browserCtx.
The previous version, I used to ```page.SetDownloadBehavior``` but with Chrome/92.0.4515.40 and chromedp v0.7.3, it removed event ```page.EventDownloadProgress```. For that reason, I have to use ```browser.SetDownloadBehavior```. Do we have any option for tab context?

> 2. the parent context of tabCtx is a timeout context. It's possible that the previous tries use too much time and there is not enough time left for the next try (ignore this point if that's what you want).
Yeah, I set a long timeout and limit number of try for this case.

**Comment by ZekeLu** [comment] 2021-06-10 04:33
> what subdir and file to find clue for the symption?

`Default/chrome_debug.log`

> Do we have any option for tab context?

I think the answer is no as of now. But the CDP supports [BrowserContext](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext), which is an isolated incognito-alike session within a browser instance and is fast and cheap to create (see [playwright](https://playwright.dev/docs/core-concepts#browser-contexts)). That will make it possible. But I'm afraid `chromedp` does not support it yet. It's not a promise, but the support of `BrowserContext` is on my todo list.

**Comment by nnguyent** [comment] 2021-06-10 05:11
>what subdir and file to find clue for the symption?
Default/chrome_debug.log

Actually, I checked this file and all files in UserDataDir to know what happen, however, I don't find anything. 
For example:
```
 INFO ID:722260, created new tab targetID: B57541A2B958CA4710D1631B2A1ED886, sessionID: B748FA1F9B0461470C686C910EF04023
 INFO ID:201421, created new tab targetID: 8DACE787645F3352E753D9F20D963D61, sessionID: 5B6A073992EBCE5F76E090EB4432013A
 INFO ID:128976, created new tab targetID: AADEAE3B340A991550220A64C9749A16, sessionID: 3D3406AB48545E7FDD1166440440343B
 INFO ID:929382, created new tab targetID: 571BAE94AC432C78E5BF0FB84B675FF4, sessionID: 5DE4389E36602472CA5F66B5B9F86578
ERROR ID:722260, main routine is received error: received crashed event &target.EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61", Status:"crashed", ErrorCode:5}
ERROR ID:929382, main routine is received error: received crashed event &target.EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61", Status:"crashed", ErrorCode:5}
ERROR ID:201421, main routine is received error: received crashed event &target.EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61", Status:"crashed", ErrorCode:5}
ERROR ID:128976, main routine is received error: received crashed event &target.EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61", Status:"crashed", ErrorCode:5}
 INFO ID:722260, closing tab targetID: B57541A2B958CA4710D1631B2A1ED886, sessionID: B748FA1F9B0461470C686C910EF04023
 INFO ID:929382, closing tab targetID: 571BAE94AC432C78E5BF0FB84B675FF4, sessionID: 5DE4389E36602472CA5F66B5B9F86578
 INFO ID:201421, closing tab targetID: 8DACE787645F3352E753D9F20D963D61, sessionID: 5B6A073992EBCE5F76E090EB4432013A
 INFO ID:128976, closing tab targetID: AADEAE3B340A991550220A64C9749A16, sessionID: 3D3406AB48545E7FDD1166440440343B
```
Search in UserDataDir:
```
root@a461a39f48c4:/app/chromedp# grep -rin "B57541A2B958CA4710D1631B2A1ED886" .
root@a461a39f48c4:/app/chromedp# grep -rin "B748FA1F9B0461470C686C910EF04023" .
root@a461a39f48c4:/app/chromedp# grep -rin "8DACE787645F3352E753D9F20D963D61" .
root@a461a39f48c4:/app/chromedp# grep -rin "5B6A073992EBCE5F76E090EB4432013A" .
root@a461a39f48c4:/app/chromedp# grep -rin "AADEAE3B340A991550220A64C9749A16" .
root@a461a39f48c4:/app/chromedp# grep -rin "3D3406AB48545E7FDD1166440440343B" .
root@a461a39f48c4:/app/chromedp# grep -rin "571BAE94AC432C78E5BF0FB84B675FF4" .
root@a461a39f48c4:/app/chromedp# grep -rin "5DE4389E36602472CA5F66B5B9F86578" .
root@a461a39f48c4:/app/chromedp# grep -rin "crashed" .
root@a461a39f48c4:/app/chromedp#  
```

Another weird is crashed event target ID:8DACE787645F3352E753D9F20D963D61, it belong to ID:201421, but some how, other IDs received this crased event target ID.
```
ID:722260, targetID: B57541A2B958CA4710D1631B2A1ED886, received EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61"}
ID:929382, targetID: 571BAE94AC432C78E5BF0FB84B675FF4, received EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61"}
ID:128976, targetID: AADEAE3B340A991550220A64C9749A16, received EventTargetCrashed{TargetID:"8DACE787645F3352E753D9F20D963D61"}
```

**Comment by nnguyent** [comment] 2021-06-10 05:35
> I think the answer is no as of now. But the CDP supports BrowserContext, which is an isolated incognito-alike session within a browser instance and is fast and cheap to create (see playwright). That will make it possible. But I'm afraid chromedp does not support it yet. It's not a promise, but the support of BrowserContext is on my todo list.

hopefully it will arrive soon

**Comment by ZekeLu** [comment] 2021-06-10 05:39
Do you have a minimal reproducer? It's hard to guess what's wrong based on the current information.

**Comment by nnguyent** [comment] 2021-06-10 05:57
I don't have. I think it quite depend on remote server (I can't disclosure it) with multiple requeset on the same time. This is a reason I need a log to proof, or provide a clue for my colleague. The attached file is [chrome_debug.log](https://github.com/chromedp/chromedp/files/6628693/chrome_debug.log) with the above crashed.

**Comment by nnguyent** [comment] 2021-06-10 06:47
Another question, do I have to ```chromedp.Stop()``` before ```chromedp.Navigate()``` or just ```chromedp.Navigate()``` to try download again?

**Comment by ZekeLu** [comment] 2021-06-10 09:17
Understood.

I can not figure out what's wrong from the `chrome_debug.log` file. I have tried to crash the browser (see https://stackoverflow.com/questions/40367087/how-to-crash-chrome-browser) and my log doesn't contain any helpful information  too.

Regarding `chromedp.Stop()`, I don't think it makes sense to call it before `chromedp.Navigate()`.

**Comment by ZekeLu** [comment] 2021-06-12 11:03
I just found that the `ERROR` logs are sent to `stdout` (or `stderr`?), but not `chrome_debug.log`. That's very weird. Is it working as design? or do we pass the wrong options?  I'm not sure. I can not find any clue from the [doc](http://www.chromium.org/for-testers/enable-logging). Anyway, here is how to get the `ERROR` logs:

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	// --enable-logging and --v=100 are not required
	// redirect stdout and stderr to a writer
	chromedp.CombinedOutput(log.Writer()),
)
```

Here are the error messages for navigating to `chrome://crash`:

```
[0612/184601.570968:ERROR:command_buffer_proxy_impl.cc(123)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[0612/184603.664287:ERROR:render_frame_impl.cc(1386)] Intentionally crashing (with null pointer dereference) because user navigated to chrome://crash/
```

---

> Another weird is crashed event target ID:8DACE787645F3352E753D9F20D963D61, it belong to ID:201421, but some how, other IDs received this crased event target ID.

That's because `Chrome` will send crashed event to several targets. See the logs below. As the logs shown, maybe it's better to listen to the `Inspector.targetCrashed` event here.

```
2021/06/12 18:15:02 <- {"method":"Inspector.targetCrashed","params":{},"sessionId":"776B87F82AA831D0AC46A86E1946AB29"}
2021/06/12 18:15:02 <- {"method":"Target.targetCrashed","params":{"targetId":"501D110645952C3C55F6A7CCF09DB6E6","status":"crashed","errorCode":11}}
2021/06/12 18:15:02 <- {"method":"Target.targetCrashed","params":{"targetId":"501D110645952C3C55F6A7CCF09DB6E6","status":"crashed","errorCode":11},"sessionId":"C1BBE996A0E9B5A0E1ED105B112C44DA"}
2021/06/12 18:15:02 <- {"method":"Target.targetCrashed","params":{"targetId":"501D110645952C3C55F6A7CCF09DB6E6","status":"crashed","errorCode":11},"sessionId":"A27CB0A3BA8145208ED7AA8F41CD02D8"}
2021/06/12 18:15:02 <- {"method":"Target.targetCrashed","params":{"targetId":"501D110645952C3C55F6A7CCF09DB6E6","status":"crashed","errorCode":11},"sessionId":"776B87F82AA831D0AC46A86E1946AB29"}
```

**Comment by nnguyent** [comment] 2021-06-16 05:03
Thanks for looking out for me. I hope to see any proof of this symptom.

**Comment by ZekeLu** [comment] 2021-06-29 10:34
It seems that there is not more to do here. Closing. Feel free to reopen it if I'm wrong.

**Closed by ZekeLu** 2021-06-29 10:34 UTC
