### ISSUE TITLE
Click doesn't work different environments

### ISSUE THREAD

**Issue by abdul-creator** [chromedp/chromedp#1104] opened 2022-07-04 14:07 UTC
Using same chrome version on both environments.

#### code

```go
chromedp.Click("#Factory_Theme_wt20_block_wtAction_wtLoginButton", chromedp.NodeNotVisible),
```

on my local computer it works fine but when i use the same code in another environment it fails to click.

#### Html code

![image](https://user-images.githubusercontent.com/56550332/177171090-22ce4d62-faed-4ee8-a5d8-1edc7abd0a89.png)

Thanks for your help :)

**Comment by ZekeLu** [comment] 2022-07-04 14:14
There could be a few reasons. Please provide a minimal reproducer. At least, provide the url to the page in question.

**Comment by abdul-creator** [comment] 2022-07-11 20:16
@ZekeLu thanks for your response. Unfortunately I can't provide the url link. However I found the solution I made an API and call this API with another function that works fine.

**Comment by ZekeLu** [comment] 2022-07-12 08:46
Thanks for the information. Since this issue is not actionable, I'm going to close it.

**Closed by ZekeLu** 2022-07-12 08:46 UTC

**Comment by BlackSinny** [comment] 2022-11-03 15:33
can you show me your api code, this is helpful for me,thanks
