### ISSUE TITLE
Chromedp crashes when executing redirect javascript 

### ISSUE THREAD

**Issue by poweroftrue** [chromedp/chromedp#197] opened 2018-06-08 16:22 UTC
Hello @kenshaw 

Thank you for the awesome work! 

I'll be using Chromedp a lot in the coming months for detecting illegal & scam websites and your tool really helped!

I'll try to submit PRs with examples also some tools to help in the production (Docker-related)

I face an issue when I tried to execute some javascript that redirects the users to another page on the website 

When the redirect occurs I think Chromedp parser waited for the response and the response didn't complete or sent an invalid response:
```
unexpected end of JSON input
```

I did a workaround via adding a fake response in javascript to stop the parser
```go
// before
chromedp.Evaluate(`__someFunc();`, &res)
// after
chromedp.Evaluate(`__someFunc();1;`, &res)
```
But it didn't work: 
```
json: cannot unmarshal number into Go value of type string
```

So I just passed empty string and it worked!
```go
chromedp.Evaluate(`__someFunc();"";`, &res)
```

So am I using the wrong function or should I ignore the response somehow?

Thanks a lot 👍

**Comment by kenshaw** [comment] 2018-06-08 16:29
@poweroftrue please try `EvaluateAsDevTools` instead. `Evaluate` probably doesn't do what you think it does. Likely `__someFunc()` is causing an error, which you're silently discarding (effectively).

**Comment by poweroftrue** [comment] 2018-06-08 22:56
@kenshaw Thanks for the fast reply!

I did use that function already (I saw it via the repo GoDoc, nicely done documentation 👍 ) but it didn't work, I was looking for a function that doesn't wait for a reply.

I think when I executed the function in DevTools it started to print some logs and errors in the middle of that the redirect happens. 

Unfortunately, I couldn't screenshot that because of the phishing website has taken down.

**Comment by SimplySerenity** [comment] 2018-08-03 17:55
@poweroftrue I think the issue is that CDP tries to execute the JavaScript immediately. I've found that if the browser is busy doing something (loading another page, redirecting, etc) you'll get this error.

**Comment by mvdan** [comment] 2019-04-04 14:59
@poweroftrue are you still experiencing this issue? If so, could you please try the latest version from master?

**Comment by mvdan** [comment] 2019-04-13 00:57
Closing for now. Please feel free to reopen or file a new issue if you still experience this bug.

**Closed by mvdan** 2019-04-13 00:57 UTC
Labels: needs info
