### ISSUE TITLE
How to send CTRL + A?

### ISSUE THREAD

**Issue by smp12345** [chromedp/chromedp#716] opened 2020-11-19 09:45 UTC
How do I send key combinations?Such as CTRL + a

**Comment by ycd** [comment] 2020-12-01 08:30
Looks like a duplicate of #400, does this helps?

**Comment by clarkmcc** [comment] 2020-12-02 00:48
I tried the solution in #400, couldn't get it to work, I also tried:

```go
return chromedp.Run(ctx, chromedp.Click(selector),
	input.DispatchKeyEvent(input.KeyDown).WithModifiers(input.ModifierCtrl).WithKey("a"))
```

**Comment by kenshaw** [comment] 2021-01-07 03:27
Please note that with the CDP, one needs to synthesize the key down, key press, and key up events in order to "correctly" send a key event. Try using the `SendKeys` event that synthesizes this for you, or alternately copy/paste the `SendKeys` implementation and add modifiers that are held down. I realize that this seems like a "simple task", but the actual underlying protocol complicates this a bit, especially with the static/typesafe nature of Go. In this case, it's a bit too difficult to provide a "one size fits all" API that would work with every possible use case.

**Closed by kenshaw** 2021-01-07 03:27 UTC
