### ISSUE TITLE
chromedp hung up when query nodes by selector

### ISSUE THREAD

**Issue by willamboss** [chromedp/chromedp#1306] opened 2023-05-04 07:06 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$  112.0.5615.138
<!--replace this line with the output-->
$ go version go1.19.5 windows/amd64
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
var nodes []*cdp.Node
ctask, shot, err := CurrentScreenshot(task, ctx)
//查找确认按钮并且点击
err = chromedp.Run(ctx, chromedp.Nodes("//button[contains(text(), '确认')]", &nodes, chromedp.ByQueryAll))
```

#### What did you expect to see?

fast return when there is no node which I need

#### What did you see instead?

it block until context time exceed

here is the go stack 

```
github.com/chromedp/chromedp.sleepContext({0xfbabd8, 0xc0006f2390}, 0x4c4b40)
        C:/Users/86134/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/chromedp.go:746 +0xde
github.com/chromedp/chromedp.retryWithSleep({0xfbabd8, 0xc0006f2390}, 0x4c4b40, 0xc000528540)
        C:/Users/86134/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/chromedp.go:765 +0xd8
github.com/chromedp/chromedp.(*Selector).Do(0xc000078000, {0xfbabd8, 0xc0006f2390})
        C:/Users/86134/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/query.go:160 +0xf6
github.com/chromedp/chromedp.Tasks.Do({0xc0005289f0, 0x1, 0x1}, {0xfbabd8, 0xc0006f2390})
        C:/Users/86134/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/chromedp.go:724 +0xe2
github.com/chromedp/chromedp.Run({0xfbabd8, 0xc000510990}, {0xc0005289f0, 0x1, 0x1})
        C:/Users/86134/go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/chromedp.go:333 +0x1ac
```

**Comment by willamboss** [comment] 2023-05-04 07:18
![企业微信截图_16831846788307](https://user-images.githubusercontent.com/49120242/236136160-2d12ec31-25c7-4e3b-bca0-cbb98565916c.png)

**Comment by ZekeLu** [comment] 2023-05-04 08:22
> fast return when there is no node which I need

Pass in the option [chromedp.AtLeast(0)](https://pkg.go.dev/github.com/chromedp/chromedp#AtLeast) if you need this behavior.

**Comment by willamboss** [comment] 2023-05-04 10:20
if err != nil || len(ids) < s.exp {
			return false, nil
		}

if err!=nil  this still return (false,nil)


func retryWithSleep(ctx context.Context, d time.Duration, f func(ctx context.Context) (bool, error)) error {
	for {
		toStop, err := f(ctx)
		if toStop || err != nil {
			return err
		}
		err = sleepContext(ctx, d)
		if err != nil {
			return err
		}
	}
}
this method still can't exit

**Comment by ZekeLu** [comment] 2023-05-04 11:01
Can you provide a minimal reproducer?

> ths it works , I think the design is somewhat unreasonable.

I agree with you. But making no-try as a default option does not look good too. And we can not change the default behavior now.

**Comment by ZekeLu** [comment] 2023-05-04 11:02
> if err!=nil  this still return (false,nil)

What's the error? Looks like #1302.

**Comment by willamboss** [comment] 2023-05-04 13:28
这里有个复现错误的代码

`      url := "http://120.53.120.89:8880"

	opts := []chromedp.ExecAllocatorOption{
		chromedp.WindowSize(1920, 1080),
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.DisableGPU,
		chromedp.IgnoreCertErrors,
		chromedp.NoSandbox,
		//chromedp.Flag("disable-site-isolation-trials", true),
		//chromedp.Flag("disable-web-security", true),
		chromedp.Flag("disable-web-security", true),
		chromedp.Flag("incognito", true),
		chromedp.Flag("disable-extensions", true),
		chromedp.Flag("disable-default-apps", true),
		chromedp.Flag("disable-setuid-sandbox", true),
	}
	plat := runtime.GOOS
	if plat == "linux" {
		opts = append(opts, chromedp.Headless, chromedp.Flag("user-data-dir", "/tmp/"))
	}

	allocCtx, cancel := chromedp.NewExecAllocator(
		context.Background(),
		opts...,
	)
	defer cancel()

	timeoutCtx, timeoutCancel := context.WithTimeout(allocCtx, 20000*time.Second)
	defer timeoutCancel()
	taskCtx, cancel1 := chromedp.NewContext(timeoutCtx)
	defer cancel1()
	err := chromedp.Run(taskCtx, chromedp.Navigate(url))
	if err != nil {
		fmt.Printf("navigate error %v \n", err)
	}
	var nodes []*cdp.Node
	err = chromedp.Run(taskCtx, chromedp.Sleep(1*time.Second), chromedp.Nodes("*^$#@nonexistent-element", &nodes, chromedp.ByID))

	if err != nil {
		fmt.Printf("get input error %v\n", err)
	}
	fmt.Println(len(nodes))`

”*^$#@nonexistent-element“ 这个选择器单纯为了复现问题，这个进程跑起来的时候会一直卡住，直到context超时，这是不合理的，尝试一定次数就退出，才符合正常逻辑

**Comment by ZekeLu** [comment] 2023-05-04 14:40
If the error is caused by the invalid selector `*^$#@nonexistent-element`, then this is a known issue tracked by #1302. And there is a pending fix for it.

What causes the error in your real use case? Can you confirm that your real use case is caused by an invalid selector too? I want to make sure that the fix can cover your real use case too.

**Comment by willamboss** [comment] 2023-05-05 05:58
加了atLeast(0)后没有复现了，在查询的时候如果cdp返回了err信息立刻返回就行了，把错误交给用户处理，尽快处理吧

**Comment by ZekeLu** [comment] 2023-08-05 03:54
Duplicate of #1302.

**Closed by ZekeLu** 2023-08-05 03:54 UTC
