### ISSUE TITLE
Using chromedp with HTTPHandler in backend

### ISSUE THREAD

**Issue by GoLover** [chromedp/chromedp#359] opened 2019-05-25 08:18 UTC
#### What did you do? Include clear steps.
i want to use chromedp in backend
```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/chromedp/chromedp"
	"io/ioutil"
	"net/http"
	"time"
)

type userCred struct {
	Username string
	Password string
}
func tasks(cred userCred) chromedp.Tasks {
	username := `'` + cred.Username + `'`
	password := `'` + cred.Password + `'`
	var inter interface{}
	return chromedp.Tasks{
		chromedp.Navigate(`https://news.ycombinator.com/submit`),
		chromedp.Sleep(5 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('acct')[1].value =`+username, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('pw')[1].value =`+password, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.querySelector("input[value='create account']").click()`, &inter, chromedp.EvalAsValue),
	}
}
func hndlr (w http.ResponseWriter, r *http.Request) {
	body, _ := ioutil.ReadAll(r.Body)
	fmt.Println(string(body))
	var usrcrd userCred
	_ = json.Unmarshal(body,&usrcrd)
	ctx , _ := chromedp.NewContext(context.Background())
	err := chromedp.Run(ctx,tasks(usrcrd))
	if err != nil {
		fmt.Println(err) // Context canceled here
	}
	_,_ = fmt.Fprintf(w, "Fine")

}
func main() {
	http.HandleFunc("/",hndlr)
	http.ListenAndServe("0.0.0.0:8080",nil)
}
```

#### What did you expect to see?
i expect to work as well as when i use it in my CLI program.
#### What did you see instead?
it returns me an error as : context canceled

**Comment by mvdan** [comment] 2019-05-25 14:48
Please stop opening the same issue again. Duplicate of #353.

**Closed by mvdan** 2019-05-25 14:48 UTC
