### ISSUE TITLE
chromedp.Text not found html node will be block

### ISSUE THREAD

**Issue by 599259501** [chromedp/chromedp#664] opened 2020-07-16 12:40 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

**Comment by ZekeLu** [comment] 2021-05-06 01:45
This is by design. If it's possible that the element does not exist, a timeout context should be used to break the waiting (a timeout context should always be used!).

Closing as it works as intended.

**Closed by ZekeLu** 2021-05-06 01:45 UTC
