### ISSUE TITLE
 Chrome 66 crash on .Run()

### ISSUE THREAD

**Issue by linkonoid** [chromedp/chromedp#189] opened 2018-05-03 08:59 UTC
Chrome (from version 66.0.3359.117) crash work on .Run()
On the previous version 65.0.3325.181 work stable.

**Comment by Jbegley1995** [comment] 2018-05-15 13:16
Any news on this? It seems like this effects pools, when I try to allocate on my pool object it just gets a timeout waiting for initial target error. Is there any temporary fix, or anywhere I can start looking to figure out the problem?

**Comment by kenshaw** [comment] 2018-05-19 02:03
I would try using a different version of Chrome. This is possibly related to a recent change that required the `Host: ` header to be `localhost`.

**Comment by Jbegley1995** [comment] 2018-05-21 13:03
Does anyone know a good way to get another version of chrome on windows? They all seem hacky and I don't want to risk a virus or anything on my computer

**Comment by kenshaw** [comment] 2018-05-21 23:56
@Jbegley1995 I would try compiling it from source. If you could send more information from the actual crash output, I might be able to help debug the issue. Otherwise, there's simply too many other components involved (Windows, Chrome, Go, etc) that without some kind of process trace / output, it would be impossible to debug. There's a myriad number of ways that Chrome could be crashed -- a bad hard drive, for example, might cause Chrome or the OS to reap the process.

**Comment by linkonoid** [comment] 2018-05-22 09:44
Error is manifested on all Win32/64 compilation (conf Win7x64, Win10x32, Go v.10) - opens Chrome window and crash on timeout with from version 66.0.3359.117 on c.RLock() method (packet sync.RWMutex method .RLock() - no locks rw for reading... problem in pool).
In my case - a public project with not one users, so the additional distribution of Chrome, different from the delivery of Google is very problematic.
The proposed solution. Make it as in the project github.com\mkenney\go-chrome (test  code from project works in my alls configurations in non-visual Headless Chrome mode), i.e. enter the possibility in the code to explicitly set the launch configuration flags. I did not go into the details of your project, but think it's feasible in package runner.go

**Comment by mvdan** [comment] 2019-02-20 11:55
We weren't able to reproduce this issue. Since it's quite old and perhaps not related to chromedp, I'm going to close this for now. If you still have issues running a recent version of Chrome or Chromium, please file a new bug with lots of details about your system, the Chrome version, what program you're running, and what the entire terminal output is.

**Closed by mvdan** 2019-02-20 11:55 UTC

**Comment by linkonoid** [comment] 2019-02-22 06:42
All is well, the problem is no longer reproduced
