### ISSUE TITLE
SendKeys not working for login input

### ISSUE THREAD

**Issue by creedr** [chromedp/chromedp#212] opened 2018-07-11 14:04 UTC
Hello,
I'm wondering if anyone else has had this problem recently? I have a workflow where I am trying to login to a webpage, but the SendKeys is not working for the unique selector/xpath that I'm using. Not only is SendKeys not working, but Click isn't working when I try clicking on a link to the website's home page using a unique selector/xpath.  I'm wondering if it may be an issue with my version of Chrome (Version 67.0.3396.99 (Official Build) (64-bit)).  The log output is pretty verbose, and I haven't figured out what it's doing just yet.  I did have a similar issue the other day with a different website that had a popup after login where I couldn't get Click to press the close button.  Thanks!

Here's relevant part of what I'm trying to do...

```
const chasebankURL = "https://secure03a.chase.com/web/auth/dashboard#/dashboard/index/index"

func LoginChase() chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(chasebankURL),
		chromedp.Sleep(5 * time.Second),
		//chromedp.WaitVisible(`//*[@id="userId-input-field"]`),
                //chromedp.SendKeys(`//*[@id="userId-input-field`, chaseUsername),
		chromedp.Click(`//*[@id="logoHomepageLink"]/div`), //chaseUsername),
		chromedp.SendKeys(`#password-input-field`, chasePassword, chromedp.ByID),
		chromedp.Click(`//*[@id="signin-button"]`),
		chromedp.Sleep(10 * time.Second),
	}
}
```

**Comment by kenshaw** [comment] 2018-07-12 00:58
@creedr the issue here is that the login is contained within an `iframe`. Previously, `chromedp` (through some massaging) had been able to work with `iframe` child elements from the top frame. Since Chromium 64 (I think, not entirely sure on when the change was made), the Chromium security model has changed, and top level elements can no longer be manipulated in the same way. We've been rewriting `chromedp` to accommodate this change, as well as to fix all the other outstanding issues, and it should be ready soon. Until then, I'd suggest using an older version of Chrome until this gets fixed. Alternately, you can extract the `iframe`'s source location, browse to that directly, and then proceed with the login.

**Comment by kenshaw** [comment] 2018-07-12 01:01
@creedr for what it's worth, the "real" login page is `https://secure03a.chase.com/web/auth/?fromOrigin=https://secure03a.chase.com`. I actually have a Chase account, and checked this login ... it should work if you use this URL :-)

**Comment by radutopala** [comment] 2018-08-08 18:33
@kenshaw is there anything new on the `iframe` issue? Thx

**Comment by ZetaChow** [comment] 2018-08-28 06:09
### 1. set "disable-web-security" flag
`c, err := chromedp.New(ctxt, chromedp.WithLog(log.Printf), chromedp.WithRunnerOptions(runner.Flag("disable-web-security", true)))`

### 2. use "Evaluate" to run javascript handle iframe document.
```
chromedp.Tasks{
		chromedp.Navigate(loginURL),
		chromedp.WaitReady(`#iframeID`, chromedp.ByID),
		chromedp.Sleep(2 * time.Second),
	
chromedp.Evaluate(`document.getElementById('iframeID').contentWindow.document.getElementById('childNodeID').value=123`, val1),
	}
```

**Notice: The page in the iframe will load delay, so be sure to "chromedp.Sleep" for a few seconds.**

**Comment by arhuman** [comment] 2018-11-04 01:40
Same thing for me

```
        const SAVI_URL   = "http://custom.fleet-job.com/savifleet"


        return chromedp.Tasks{
                chromedp.Navigate(SAVI_URL),
                chromedp.WaitVisible(`#login`, chromedp.ByID),),
                chromedp.SendKeys(`#login`, SAVI_LOGIN, chromedp.ByID),
                chromedp.SendKeys(`#password`, SAVI_PASS, chromedp.ByID),
                chromedp.Click("#button", chromedp.ByID),
                chromedp.Sleep(1 * time.Second), // wait for animation to finish
        }

```

Sendkeys not working :-(

In the log the following output is repeated

```
2018/11/04 02:38:40 <- {"id":160,"method":"DOM.querySelector","params":{"nodeId":13,"selector":"#login"}}
2018/11/04 02:38:40 -> {"id":160,"result":{"nodeId":30}}
2018/11/04 02:38:40 <- {"id":161,"method":"DOM.getBoxModel","params":{"nodeId":30}}
2018/11/04 02:38:40 -> {"id":161,"result":{"model":{"content":[457,273.40625,626,273.40625,626,288.40625,457,288.40625],"padding":[457,272.40625,626,272.40625,626,289.40625,457,289.40625],"border":[455,270.40625,628,270.40625,628,291.40625,455,291.40625],"margin":[455,270.40625,628,270.40625,628,291.40625,455,291.40625],"width":173,"height":21}}}
2018/11/04 02:38:40 <- {"id":162,"method":"Runtime.evaluate","params":{"expression":"(function(a) {\n\t\treturn a[0].offsetParent !== null;\n\t})($x('/html[1]/body[1]/div[3]/div[1]/form[1]/div[1]/input[1]'))","objectGroup":"console","includeCommandLineAPI":true,"returnByValue":true}}
2018/11/04 02:38:40 -> {"id":162,"result":{"result":{"type":"boolean","value":false}}}
```

**Comment by mvdan** [comment] 2019-02-20 11:49
Closing as a duplicate of #72; let's keep track of the iframe issues there.

**Closed by mvdan** 2019-02-20 11:49 UTC
