### ISSUE TITLE
use chromedp in backend

### ISSUE THREAD

**Issue by GoLover** [chromedp/chromedp#353] opened 2019-05-22 08:29 UTC
#### What did you do?
I want to use chromedp in backend and write api for chromedp to do process login and information gathring from some website and return data collected.
I wrote route for each route of website and call chromedp.Run(...) with a global context that i created. but it's return context canceled error instead of gathered data.

main.go
```
func main() {
	anotherPackage.Ctx,_ = chromedp.NewContext(context.Background())
	http.HandleFunc("/api/getCaptcha",Routers.GetCaptchaLogin)
	http.HandleFunc("/api/login", RoutersLogin)
	http.HandleFunc("/api/fillForm", Routers.FillForm)
	http.HandleFunc("/api/secondCaptcha",Routers.GetSecondCaptcha)
	http.HandleFunc("/api/submitForm",Routers.SubmitSecondCaptcha)
	http.HandleFunc("/api/printFinal",Routers.PrintFinal)
	http.HandleFunc("/api/pressFinal",Routers.PressFinishBtn)
	_ = http.ListenAndServe("0.0.0.0:8080", nil)
```

anotherPackage.go with two sample function
```
package darmanTamin

import (
	"context"
	b64 "encoding/base64"
	"fmt"
	"github.com/chromedp/chromedp"
	"time"
)
var Ctx context.Context
func GetLoginCaptcha() (string,error) {
	var buf []byte
	err := chromedp.Run(Ctx, GetCaptchaLogin(&buf))
	if err != nil {
		fmt.Println(err)
	}
	return b64.StdEncoding.EncodeToString(buf) , err
}
func LoginProcess(prescSubmit *Models.PrescriptionSubmit) (string,error) {
	err := chromedp.Run(Ctx, FillLoginFields(*prescSubmit))
	var returnString string
	mctx, _ := context.WithTimeout(Ctx, 30*time.Second)
	err = chromedp.Run(mctx, FillCaptcha(prescSubmit.Captcha,&returnString))
	if err != nil {
		fmt.Println(err)
	}
	return returnString , err
}
```

**Comment by mvdan** [comment] 2019-05-22 09:22
Sorry, this isn't nearly enough information. I can't debug something that I can't run or reproduce.

**Comment by GoLover** [comment] 2019-05-22 09:50
```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/chromedp/chromedp"
	"io/ioutil"
	"net/http"
	"time"
)

type userCred struct {
	Username string
	Password string
}
func tasks(cred userCred) chromedp.Tasks {
	username := `'` + cred.Username + `'`
	password := `'` + cred.Password + `'`
	var inter interface{}
	return chromedp.Tasks{
		chromedp.Navigate(`https://news.ycombinator.com/submit`),
		chromedp.Sleep(5 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('acct')[1].value =`+username, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('pw')[1].value =`+password, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.querySelector("input[value='create account']").click()`, &inter, chromedp.EvalAsValue),
	}
}
func hndlr (w http.ResponseWriter, r *http.Request) {
	body, _ := ioutil.ReadAll(r.Body)
	fmt.Println(string(body))
	var usrcrd userCred
	_ = json.Unmarshal(body,&usrcrd)
	ctx , _ := chromedp.NewContext(context.Background())
	err := chromedp.Run(ctx,tasks(usrcrd))
	if err != nil {
		fmt.Println(err) // Context canceled here
	}
	_,_ = fmt.Fprintf(w, "Fine")

}
func main() {
	http.HandleFunc("/",hndlr)
	http.ListenAndServe("0.0.0.0:8080",nil)
}
```
for example this code returns error : `context canceled`

**Comment by mvdan** [comment] 2019-05-25 14:58
This is still not enough information for me to reproduce the issue. This program seems to take a POST request, so it needs to go along with a command like `curl` to send a request to reproduce the error.

**Comment by mvdan** [comment] 2019-05-25 14:58
In other words, please follow the very clear and explicit issue template.

**Comment by GoLover** [comment] 2019-05-26 08:16
curl -d "Username=mytest&Password=mytest" -X POST http://localhost:8080/

**Comment by mvdan** [comment] 2019-05-26 11:22
That's not a valid curl request. Your code does a json unmarshal, and errors in that line. You ignore the error, and the rest of the program just fails.

```
$ go run f.go
Username=mytest&Password=mytest
unexpected end of JSON input
```

Once again, provide **complete** instructions to reproduce the precise bug you're pointing at here. Otherwise this is just a waste of everyone's time.

**Comment by GoLover** [comment] 2019-05-26 11:30
you really don't want to solve the problem man :)

i have been edit my PoC 

```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/chromedp/chromedp"
	"io/ioutil"
	"net/http"
	"time"
)

type userCred struct {
	Username string
	Password string
}
func tasks(cred userCred) chromedp.Tasks {
	username := `'` + cred.Username + `'`
	password := `'` + cred.Password + `'`
	var inter interface{}
	return chromedp.Tasks{
		chromedp.Navigate(`https://news.ycombinator.com/submit`),
		chromedp.Sleep(5 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('acct')[1].value =`+username, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('pw')[1].value =`+password, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.querySelector("input[value='create account']").click()`, &inter, chromedp.EvalAsValue),
	}
}
func hndlr (w http.ResponseWriter, r *http.Request) {
	var usrcrd userCred
	usrcrd.Username = 'test';
	usrcrd.Password = 'test';
	ctx , _ := chromedp.NewContext(context.Background())
	err := chromedp.Run(ctx,tasks(usrcrd))
	if err != nil {
		fmt.Println(err) // Context canceled here
	}
	_,_ = fmt.Fprintf(w, "Fine")

}
func main() {
	http.HandleFunc("/",hndlr)
	http.ListenAndServe("0.0.0.0:8080",nil)
}
```

**Comment by mvdan** [comment] 2019-05-27 08:58
You're right, I don't want to fix your code, particularly since you're not willing to spend five minutes to give me steps to reproduce it. This time the code doesn't even compile.

I also spent the time to fix your code, and it still just prints `unexpected end of JSON input`, and no mention of any context error. So I'm closing.

Once again, if you're ready to provide complete steps to reproduce a bug, feel free to open a new issue.

**Closed by mvdan** 2019-05-27 08:58 UTC
Labels: needs info, question
