### ISSUE TITLE
the dynamic html cannot splash complete

### ISSUE THREAD

**Issue by crystal-lee** [chromedp/chromedp#942] opened 2021-11-05 10:09 UTC
If i donnot use  chromedp.Sleep , the dynamic html cannot splash complete。

how can i known the html complete.

I download many html , so cant use waitVisible by html element

Who can give me an idea?

```
if _, err := chromedp.RunResponse(ctx,
		chromedp.EmulateViewport(int64(Width), int64(Height)),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, _, _, err := page.Navigate(url).
				Do(ctx)
			return err
		}),
		//chromedp.Sleep(5 * time.Second),
		chromedp.OuterHTML(`//html`, &html),
	); err != nil {
		return "", err
	}
```

**Comment by ZekeLu** [comment] 2021-11-05 12:02
Is there a reason not to use `chromedp.Navigate`?

**Comment by crystal-lee** [comment] 2021-11-08 02:18
Its same, If i donnot use chromedp.Sleep, the html is not complete
```
var html = ``
	if err := chromedp.Run(ctx,
		chromedp.EmulateViewport(int64(Width), int64(Height)),
		chromedp.Navigate(url),
		//chromedp.Sleep(5 * time.Second),
		chromedp.OuterHTML(`//html`, &html),
	); err != nil {
		return "", err
	}
```

**Comment by ZekeLu** [comment] 2021-11-08 02:28
Please provide a self-contained reproducr.

**Comment by crystal-lee** [comment] 2021-11-08 02:37
that is the code and test, what should i do ?
```
package service

import (
	"context"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/cdproto/page"
)

var UserAgent = `Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`
var Width = 1280
var Height = 1920
var Timeout = time.Duration(10)

var Options = []chromedp.ExecAllocatorOption{
	chromedp.Flag("headless", true),
	chromedp.Flag("hide-scrollbars", true),
	chromedp.Flag("mute-audio", true),
	chromedp.Flag("disable-gpu", true),
	chromedp.Flag("disable-plugins", true),
	chromedp.Flag("no-sandbox", true),
	chromedp.Flag("ignore-certificate-errors", true),
	chromedp.Flag("blink-settings", "imagesEnabled=false"),
	chromedp.Flag("disable-features", "site-per-process,TranslateUI,BlinkGenPropertyTrees"),
	chromedp.UserAgent(UserAgent),
}

func Render(url string) (string, error) {
	//启动chrome的时候不检查默认浏览器
	chromedp.Flag("no-default-browser-check", true)

	//启动chrome 不适用沙盒, 性能优先
	chromedp.Flag("no-sandbox", true)

	//设置浏览器窗口尺寸,
	chromedp.WindowSize(Width, Height)

	//屏蔽 headlessChrome
	chromedp.Flag("headless", true)

	options := append(chromedp.DefaultExecAllocatorOptions[:], Options...)
	ctx1, cancel1 := chromedp.NewExecAllocator(context.Background(), options...)
	defer cancel1()

	ctx2, cancel2 := chromedp.NewContext(ctx1)
	defer cancel2()

	ctx, cancel := context.WithTimeout(ctx2, time.Second*Timeout)
	defer cancel()

	var html = ``
	/*if err := chromedp.Run(ctx,
		chromedp.EmulateViewport(int64(Width), int64(Height)),
		chromedp.Navigate(url),
		//chromedp.Sleep(5 * time.Second),
		chromedp.OuterHTML(`//html`, &html),
	); err != nil {
		return "", err
	}*/



	if _, err := chromedp.RunResponse(ctx,
		chromedp.EmulateViewport(int64(Width), int64(Height)),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, _, _, err := page.Navigate(url).
				Do(ctx)
			//err := chromedp.Navigate(url).Do(ctx)
			return err
		}),
		//chromedp.Sleep(5 * time.Second),
		chromedp.OuterHTML(`//html`, &html),
	); err != nil {
		return "", err
	}

	return html, nil
}

```
```
package service

import (
	"testing"
	"fmt"
)

func TestRender(t *testing.T) {
	if html, err := Render("https://wap.peopleapp.com/article/6345177/6345177"); err != nil {
		panic(err)
	}else {
		fmt.Println(html)
	}
}
```

**Comment by ZekeLu** [comment] 2021-11-08 03:33
> I download many html , so cant use waitVisible by html element

I think you understand that the DOM elements are manipulated by javascript code. And there is not way for the browser to tell whether the DOM is ready or not (it totally depends on the behavior of the javascript code and what you expect). In this situation, I think you have to implement the function for each source to tell whether the DOM is "ready". BTW, I think `WaitReady` is better than `WaitVisible`, and `Poll` is better than `WaitReady` in this case.

And please note that the following code does nothing:

```
	//启动chrome的时候不检查默认浏览器
	chromedp.Flag("no-default-browser-check", true)

	//启动chrome 不适用沙盒, 性能优先
	chromedp.Flag("no-sandbox", true)

	//设置浏览器窗口尺寸,
	chromedp.WindowSize(Width, Height)

	//屏蔽 headlessChrome
	chromedp.Flag("headless", true)
```

Since there is nothing more to do, I'm closing this issue.

**Closed by ZekeLu** 2021-11-08 03:33 UTC
