### ISSUE TITLE
Chromedp says node has children but none are there

### ISSUE THREAD

**Issue by angelo-at-webleaders** [chromedp/chromedp#1209] opened 2022-11-25 10:14 UTC
I got a list (ul) from a website and now I want to loop over the children and their text i.e.

    <ul>
      <li>
        <span>some text</span>
      </li>
      <li>
        <span>some text 2</span>
      </li>
      <li>
        <span>some text 3</span>
      </li>
      <li>
        <span>some text 4</span>
      </li>
    </ul>

When I print the outcome of the main node, it says ChildNodeCount:4 Children:[]. The childNodeCount is correct, but the children is empty and thus I cannot loop through the children to retrieve the text.

A page has multiple lists, so what I basically want is a list with "UL" elements so I can loop through each UL element, and within that UL element through its LI children.

Anyone knows what I am doing wrong?

    chromedp.Nodes(`.product-item__content ul.product-small-specs`, &specs, chromedp.AtLeast(0)),

Also a small side-question. If I have an slice of strings (URL's) and I would like to crawl them one-by-one. How would I do that? Or let me put it this way. If I got to page "A" and I find 20 links, how can I automatically check those links too and if there are links found visit those too?

**Comment by ZekeLu** [comment] 2022-11-25 10:52
Duplicate of #761

**Closed by ZekeLu** 2022-11-25 10:52 UTC
