### ISSUE TITLE
MouseClickNode not work  in headless

### ISSUE THREAD

**Issue by BlackSinny** [chromedp/chromedp#1192] opened 2022-11-03 16:19 UTC
## env
- chrome: Google Chrome 107.0.5304.87
- linux version 18.04.1-Ubuntu
- go version 1.17
- chromedp version v0.8.6
- chromedp headless env

## my problem 
- code
```golang
var buf1 []byte
err = chromedp.Run(ctx,
  chromedp.MouseClickNode(dznodes[0]),
  chromedp.Sleep(1*time.Second),
  chromedp.CaptureScreenshot(&buf1),
)
if err != nil {
  log.Println("run error：", err)
  return err
}
if err := ioutil.WriteFile("click.png", buf1, 0644); err != nil {
  log.Println("screen_shot_error：", err)
}

```
The out click.png,click action work normally , but i visit website ,click action not work yet....

**Comment by ZekeLu** [comment] 2022-11-03 16:33
Please provide a runnable self-contained demo. It's most likely that the website detects that the client is a headless browser and responses with a different content.

**Comment by BlackSinny** [comment] 2022-11-04 01:36
In what way should I confirm that this is the case，thanks

**Comment by ZekeLu** [comment] 2022-11-04 04:02
Too many things can make it fail. Here are some of them:

- #876
- #1097
- #1163
- #1069

I think the first step is to enable the debug log to see the CDP messages. See [chromedp.WithDebugf](https://pkg.go.dev/github.com/chromedp/chromedp#WithDebugf).

It seems that you can not share the url. So the issue is not actionable. I'm going to close it. Please reopen if you can provide a self-contained demo. Thank you!

**Closed** 2022-11-04 04:05 UTC
Labels: needs info
