### ISSUE TITLE
how to click an element in a frame

### ISSUE THREAD

**Issue by 380wmda999** [chromedp/chromedp#496] opened 2019-10-23 07:12 UTC
an element is in a frame not the top, how can I click it ??

**Comment by JILeXanDR** [comment] 2019-10-29 15:44
I'm also interested in this. As I temperary solution I'm doing in this way:
```
var messages interface{}
if err := chromedp.Evaluate(`Array.prototype.slice.call(top.frames['main'].frames['chat'].document.querySelector('#chat-channels div').querySelectorAll('p')).map(val => val.textContent)`, &messages).Do(ctx); err != nil {
    return nil, errors.Wrapf(err, "failed to retrieve chat messages")
}
```

As you can see here are a nested frames and it works fine for me. You can use `.click()`. But I want to refactor code in prefer of using high level API of library without JS hacks.

**Comment by 380wmda999** [comment] 2019-11-06 06:41
@JILeXanDR  the page seems not support js  .click() , so I need click api

**Comment by mvdan** [comment] 2019-11-25 11:57
Duplicate of #72.

**Closed by mvdan** 2019-11-25 11:57 UTC
