### ISSUE TITLE
Marshal event error when closing target

### ISSUE THREAD

**Issue by ag321123** [chromedp/chromedp#419] opened 2019-07-04 01:01 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

not running go modules. did go get june 29th

Google Chrome is up to date
Version 75.0.3770.100 (Official Build) (64-bit)

go version go1.11.5 darwin/amd64

#### What did you do? Include clear steps.

```
package main

import (
	"context"
	"fmt"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/cdproto/target"
)

func main() {

	// new browser, first tab
	ctx1, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// ensure the first tab is created
	if err := chromedp.Run(ctx1); err != nil {
	    panic(err)
	}

	// same browser, second tab
	ctx2, _ := chromedp.NewContext(ctx1)

	// ensure the second tab is created
	if err := chromedp.Run(ctx2); err != nil {
	    panic(err)
	}

	c1 := chromedp.FromContext(ctx1)
	c2 := chromedp.FromContext(ctx2)

	fmt.Printf("Same browser: %t\n", c1.Browser == c2.Browser)
	fmt.Printf("Same tab: %t\n", c1.Target == c2.Target)

	targets := ListTargets(&ctx1)

	err := CloseTarget(&ctx1, c1.Target.TargetID)
	if err != nil {
		fmt.Println(err)
	}

	targets = ListTargets(&ctx1)
	if len(targets) > 0 {
		err := Activate(&ctx1, targets[0])
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println("back from Activate")
	}
}

func CloseTarget(ctxt *context.Context, t target.ID) error {
  fmt.Println("CloseTarget: ", t.String())

  err := chromedp.Run(*ctxt, chromedp.ActionFunc(func(ctxt context.Context) error {
    ok, err := target.CloseTarget(t).Do(ctxt)
		fmt.Println("back from closetarget")
    if err != nil {
      return err
    }

    if !ok {
      fmt.Println("didn't close target: ", t.String())
    }

    return nil
  }))

  if err != nil {
    fmt.Println(err)
  }

  return nil
}

func Activate(ctxt *context.Context, t *target.Info) error {

	fmt.Println("ActivateTarget: ", t.TargetID.String())

  err := chromedp.Run(*ctxt, chromedp.ActionFunc(func(ctxt context.Context) error {
    err := target.ActivateTarget(t.TargetID).Do(ctxt)
    if err != nil {
      return err
    }

    return nil
  }))

  if err != nil {
    fmt.Println(err)
  }

  return nil
}

func ListTargets(ctxt *context.Context) []*target.Info {
	fmt.Println("listing targets")

  targets, err := chromedp.Targets(*ctxt)
  if err != nil {
    fmt.Println(err)
  }
  var out []*target.Info
  for _, v := range targets {
    fmt.Println("target: ", v.TargetID.String(), " type: ", v.Type, " url: ", v.URL)
    if v.Type != "page" {
      fmt.Println("target of type not page")
      continue
    }
    out = append(out, v)
  }
  return out
}
```

#### What did you expect to see?
Open two tabs.
List targets.
Close one of the targets

Get a marshaling error.

#### What did you see instead?
Same browser: true
Same tab: false
listing targets
target:  7179035D6A02E29E7BDE456BB3747821  type:  page  url:  about:blank
target:  91FED25305CADBF605FF5532394122D8  type:  page  url:  about:blank
CloseTarget:  91FED25305CADBF605FF5532394122D8
2019/07/03 20:47:42 ERROR: could not unmarshal event: parse error: syntax error near offset 0 of 'arams":{"s...'

and this hangs.

Thanks,
Allan

**Comment by mvdan** [comment] 2019-07-04 01:15
Could you confirm exactly what chromedp commit you're on?

**Comment by ag321123** [comment] 2019-07-04 01:23
How do you do that?

**Comment by mvdan** [comment] 2019-07-04 01:25
You're building against a specific version of chromedp - I'm asking what version that is. If you're on GOPATH, you can just cd to the chromedp directory and do a `git log -1`.

**Comment by ag321123** [comment] 2019-07-04 01:32
I did a go get -u github.com/chromedp/chromedp <http://github.com/chromedp/chromedp> to install chromedp.

Results of git log -1

commit e5acbe3f56d48fe699363d2ae2f6cefeda9269be (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel Martí <mvdan@mvdan.cc>
Date:   Thu Jun 27 10:56:13 2019 +0200

    don't panic on selectors if the frame isn't loaded
    
    This is possible if one uses page.Navigate directly, as it doesn't wait
    for the load to happen.
    
            panic: runtime error: invalid memory address or nil pointer dereference
            [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x890d17]
    
            goroutine 779 [running]:
            sync.(*RWMutex).RLock(...)
                    /home/mvdan/tip/src/sync/rwmutex.go:48
            github.com/chromedp/chromedp.(*Selector).run(0xc0005a8c00, 0xaa5d80, 0xc0004888a0, 0xc0006b86c0, 0xc000fb4420)
                    /home/mvdan/src/chromedp/sel.go:79 +0x137
            created by github.com/chromedp/chromedp.(*Selector).Do
                    /home/mvdan/src/chromedp/sel.go:55 +0x11e
    
    While at it, remove a few unnecessary Tasks wrappings.
    
    Fixes #404.

**Comment by mvdan** [comment] 2019-07-20 08:02
Thanks. I'll try to investigate what's going on. I seem to recall similar errors in the past.

**Comment by mvdan** [comment] 2019-07-20 08:28
I can reproduce the error. That's a data race that can be fixed. Here's a smaller program to reproduce it:

```
package main

import (
        "context"

        "github.com/chromedp/cdproto/target"
        "github.com/chromedp/chromedp"
)

func main() {
        ctx, cancel := chromedp.NewContext(context.Background())
        defer cancel()

        if err := chromedp.Run(ctx); err != nil {
                panic(err)
        }

        c1 := chromedp.FromContext(ctx)
        err := closeTarget(ctx, c1.Target.TargetID)
        if err != nil {
                panic(err)
        }
        println("done")
}

func closeTarget(ctx context.Context, t target.ID) error {
        err := chromedp.Run(ctx, chromedp.ActionFunc(func(ctx context.Context) error {
                _, err := target.CloseTarget(t).Do(ctx)
                if err != nil {
                        return err
                }
                return nil
        }))
        if err != nil {
                panic(err)
        }
        return nil
}
```

Even when it's fixed though, the hang is real - this is because you're closing the target manually. Instead, you should rely on context cancellation, which handles closing the target/page on its own.

You can't cancel a browser's first tab without also cancelling and closing the entire browser, and that's by design. Contexts are layered, and the first context holds both the browser and its initial tab.

So, is there a reason you're using `target.CloseTarget` directly, and not `cancel`?

**Comment by mvdan** [comment] 2019-08-15 12:49
Friendly ping @ag321123 - I'm still not sure if this is something to fix, or if we can simply forbid the usage of `target.CloseTarget`.

**Closed** 2019-08-28 15:59 UTC
Labels: needs info
