### ISSUE TITLE
How to open a website protected by Cloudflare?

### ISSUE THREAD

**Issue by HelloAllenZHU** [chromedp/chromedp#982] opened 2021-12-17 12:32 UTC
How to open a website protected by Cloudflare? such as [https://coinlist.co](https://coinlist.co), 

I just want to open [https://coinlist.co](https://coinlist.co) using Chromepd with `headless = true` flag, but Chrome prompts that "Chrome is being controlled by automated test software", and the chrome page blocks at the Cloudflare page. It seems like Cloudflare can detect the Chromedp.

**Comment by ZekeLu** [comment] 2021-12-18 05:59
Closing as duplicate of #875.

**Closed by ZekeLu** 2021-12-18 05:59 UTC
