### ISSUE TITLE
how to make chromedp undetectable

### ISSUE THREAD

**Issue by wubin1989** [chromedp/chromedp#441] opened 2019-07-25 08:26 UTC
#### What versions are you running?

<pre>
$ github.com/chromedp/chromedp v0.3.1
$ chrome browser 75.0.3770.142
$ go version go1.12 darwin/amd64
</pre>

#### What did you do? Include clear steps.
I want to crawl user comments from this page https://hotels.ctrip.com/hotel/436458.html?isFull=F#ctm_ref=hod_sr_lst_dl_n_1_1
As I know the website will detect whether a visit is from crawler or not, I should use chromedp with headless false mode and make chromedp as real browser completely.
here is my code: 
<pre>
allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), []chromedp.ExecAllocatorOption{
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.DisableGPU,
		chromedp.UserDataDir(dir),

		chromedp.NoSandbox,
		//chromedp.Headless,

		// After Puppeteer's default behavior.
		chromedp.Flag("disable-infobars", true),
		chromedp.Flag("excludeSwitches", "enable-automation"),
		chromedp.Flag("disable-background-networking", true),
		chromedp.Flag("enable-features", "NetworkService,NetworkServiceInProcess"),
		chromedp.Flag("disable-background-timer-throttling", true),
		chromedp.Flag("disable-backgrounding-occluded-windows", true),
		chromedp.Flag("disable-breakpad", true),
		chromedp.Flag("disable-client-side-phishing-detection", true),
		chromedp.Flag("disable-default-apps", true),
		chromedp.Flag("disable-dev-shm-usage", true),
		chromedp.Flag("disable-extensions", true),
		chromedp.Flag("disable-features", "site-per-process,TranslateUI,BlinkGenPropertyTrees"),
		chromedp.Flag("disable-hang-monitor", true),
		chromedp.Flag("disable-ipc-flooding-protection", true),
		chromedp.Flag("disable-popup-blocking", true),
		chromedp.Flag("disable-prompt-on-repost", true),
		chromedp.Flag("disable-renderer-backgrounding", true),
		chromedp.Flag("disable-sync", true),
		chromedp.Flag("force-color-profile", "srgb"),
		chromedp.Flag("metrics-recording-only", true),
		chromedp.Flag("safebrowsing-disable-auto-update", true),
		chromedp.Flag("enable-automation", true),
		chromedp.Flag("password-store", "basic"),
		chromedp.Flag("use-mock-keychain", true),
	}...)
</pre>

#### What did you expect to see?
I expect to see user comments display below 住客点评
![expect](https://user-images.githubusercontent.com/12456315/61858494-c0b94300-aef8-11e9-8450-ec7eee22aa8b.jpg)

#### What did you see instead?
below 住客点评 no user comment display
![result](https://user-images.githubusercontent.com/12456315/61858524-d3cc1300-aef8-11e9-8033-27f26118f2aa.jpg)

**Comment by mvdan** [comment] 2019-08-09 08:16
Sorry, but I don't see anything resembling comments or reviews in that page.

If you can reproduce this with a site that shows English, that would be helpful.

**Comment by steve0hh** [comment] 2019-08-10 16:05
Having this issue with recaptcha too. 
Tested on: https://patrickhlauke.github.io/recaptcha/

**Comment by kenshaw** [comment] 2019-08-10 22:41
`chromedp` works just the same as any other library that drives Chrome using the DevTools Protocol. Anything that, eg, `puppeteer` or Selenium or any other package is capable of doing, can be done using `chromedp`. It's a cat and mouse game trying to stay ahead of sites detecting scrapers, and is somewhat of a silly exercise. I'm closing this issue, because this "issue" comes down to a "how does one use the Chrome DevTools Protocol". The short answer is "you can never fully stop sites from detecting a scraper", and the long answer is "be more clever / faster than the other site."

**Closed by kenshaw** 2019-08-10 22:41 UTC
Labels: needs info
