### ISSUE TITLE
I want to find examples related to fetch.AuthChallenge, but I didn’t find them. Can you examples?

### ISSUE THREAD

**Issue by scc888** [chromedp/chromedp#832] opened 2021-05-26 02:24 UTC
```go
	chromedp.ListenTarget(ctx, func(ev interface{}) {
		go func() {
			switch ev := ev.(type) {
			case *fetch.EventAuthRequired:
				c := chromedp.FromContext(ctx)
				execCtx := cdp.WithExecutor(ctx, c.Target)
	
				 fetch.AuthChallenge{
					Source: fetch.AuthChallengeSourceServer,
					Origin: "",
					Scheme: "",
					Realm:  "",
				}

				err := fetch.ContinueRequest(ev.RequestID).Do(execCtx)
				if err != nil {
					log.Print(err)
				}
			}
		}()
	})
```

**Comment by ZekeLu** [comment] 2021-05-26 02:39
Duplicate of #831.

**Closed by ZekeLu** 2021-05-26 02:39 UTC
