### ISSUE TITLE
How to save the final HTML source code into a variable?

### ISSUE THREAD

**Issue by laker31** [chromedp/chromedp#1196] opened 2022-11-08 13:44 UTC
Hi,

I am trying to do the following, but do not understand how to do the last step. Can somebody give any tips?

1. Navigate to a certain webpage.
2. Sleep for 15 seconds (this should give enough time for all possible elements on the page to load).
3. Save the final HTML source code into a variable.

Thanks!

**Comment by ZekeLu** [comment] 2022-11-09 03:19
Duplicate of #921.

**Closed by ZekeLu** 2022-11-09 03:19 UTC
