### ISSUE TITLE
Run chrome headless and shutdown properly without errors?

### ISSUE THREAD

**Issue by airyy** [chromedp/chromedp#234] opened 2018-09-13 23:26 UTC
Hello,

I am having issues running chromedp in a wait group and pool. My tasks are not running and the chrome processes are not closing. I used the exact example here: https://github.com/chromedp/examples/blob/master/pool/main.go

This is an issue because I need the tasks to execute, as well as if I want to run again, I have to close them manually or I will get timeout errors.

Suggestions appreciated, thanks!

**Comment by sloppycoder** [comment] 2018-12-03 10:15
I had a similiar problem of chrome headless not closing properly. I use something like this as workaround:

func runWithChrome(taskFunc func(context.Context, *chromedp.CDP) error, chromeOption chromedp.Option) {
	var err error

	ctx, cancel := context.WithTimeout(context.Background(), 300 * time.Second)
	defer cancel()

	// create chrome instance
	var c *chromedp.CDP
	c, err := chromedp.New(ctx, chromeOption, chromedp.WithLog(log.Printf))

	// make sure Chrome is closed when exit
	defer func() {
		log.Printf("Shutdown chrome")
		// shutdown chrome
		err = c.Shutdown(ctx)
		if err != nil {
			log.Fatal(err)
		}

		// wait for chrome to finish
		// Wait() will hang on Windows and Linux with Chrome headless mode
		// we'll need to exit the program when this happens
		ch := make(chan error)
		go func() {
			c.Wait()
			ch <- nil
		}()

		select {
		case err = <-ch:
			log.Println("chrome closed")
		case <-time.After(10 * time.Second):
			log.Println("chrome didn't shutdown within 10s")
		}
	}()

	err = taskFunc(ctx, c)
	if err != nil {
		// don't use Fatal because we need to deter functions to run
		log.Printf("%v", err)
		return
	}
}

**Comment by mvdan** [comment] 2019-02-21 23:17
Duplicate of https://github.com/chromedp/chromedp/issues/81.

**Closed by mvdan** 2019-02-21 23:17 UTC
