### ISSUE TITLE
WaitReady response time unpredictable

### ISSUE THREAD

**Issue by zkl94** [chromedp/chromedp#436] opened 2019-07-17 17:43 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
v0.3.1 bd26d4c
$ google-chrome --version
Google Chrome 75.0.3770.100
$ go version
go version go1.12.7 linux/amd64
</pre>

#### What did you do? Include clear steps.

I am trying to simulate click behavior on some dropdown menu items in BMC remedy. These dropdowns are not normal \<select\>s and \<option\>s, they are customized \<div\>s controlled by a JS in the page.

Before I click the dropdown menu, the items do not exist in the dom. They are loaded and show up in dom after I click the dropdown menu.

I use `chromedp.Click` on the dropdown menu and `chromedp.WaitReady` to wait for the items to be ready. And then I `chromedp.Click` the item

#### What did you expect to see?

I expect that the WaitReady call return as soon as the items are loaded, and no error is thrown.

#### What did you see instead?

chromedp.WaitReady response time is not predictable. Sometimes it hangs for 2-3 secs and then returns. But sometimes it hangs forever and never returns, making my script stuck. If I add time.Sleep 5s between chromedp.Click and chromedp.WaitReady, the code will run without issue for days.

I think this is a similar issue as #168 but it was closed so I open this new one.

**Comment by mvdan** [comment] 2019-08-09 08:24
Do you have a Go program to reproduce this problem? I haven't seen anything like this ever since #168 was closed, so I don't know how to debug this.

Also, is there anything special about the page? Perhaps it uses iframes, or the dropdown is loaded via JS?

**Comment by mvdan** [comment] 2019-08-25 18:10
Sorry, but I can't debug or fix a bug I can't even reproduce. Closing for now.

**Closed by mvdan** 2019-08-25 18:10 UTC
Labels: needs info
