### ISSUE TITLE
panic: waited too long for page targets to show up

### ISSUE THREAD

**Issue by cai-peng** [chromedp/chromedp#346] opened 2019-05-17 12:33 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ chromium --version
$ go version
</pre>

#### What did you do?
```
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
)

func main() {
	actx, cancel := chromedp.NewExecAllocator(context.Background(), chromedp.WindowSize(40, 40))
	defer cancel()

	ctx, cancel := chromedp.NewContext(actx)
	defer cancel()

	var text string
	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://github.com/chromedp/chromedp"),
	); err != nil {
		panic(err)
	}
	fmt.Println(text)
}
```
#### What did you expect to see?
**panic: waited too long for page targets to show up**

#### What did you see instead?
NewExecAllocator without DefaultExecAllocatorOptions
This is a bug fix it like this
```
func NewExecAllocator(parent context.Context, opts ...ExecAllocatorOption) (context.Context, context.CancelFunc) {
	ctx, cancel := context.WithCancel(parent)
	- c := &Context{Allocator: setupExecAllocator(opts...)}
        + o := append(DefaultExecAllocatorOptions,opts...)
	+ c := &Context{Allocator: setupExecAllocator(o...)}

	ctx = context.WithValue(ctx, contextKey{}, c)
	cancelWait := func() {
		cancel()
		c.Allocator.Wait()
	}
	return ctx, cancelWait
}
```

**Comment by tmm1** [comment] 2019-05-18 01:08
Hi, your pasted code is not formatted correctly. Please use three backticks to enclose the code:

<pre>
```
code
```
</pre>

**Comment by mvdan** [comment] 2019-05-18 21:07
Is this a continuation of #341? Exactly like in that issue, the code you pasted works fine for me on v0.3.0.

Also, NewExecAllocator isn't buggy. If it hard-coded a number of options, it would be difficult to avoid using those default options. So if you want to use some extra options, you need to also specify the default options.

**Comment by cai-peng** [comment] 2019-05-19 09:07
Strange！ there is indeed an exception in my environment. I changed the environment of other developers and found that there is still the same problem. 

/:P-(

**Comment by mvdan** [comment] 2019-05-19 14:50
Well, I'm still not sure what the purpose of this issue is. I can't reproduce it, nor do I have enough information to try to, so I'm going to close it for now.

**Closed by mvdan** 2019-05-19 14:50 UTC
Labels: needs info
