### ISSUE TITLE
how upload file whitout submit button

### ISSUE THREAD

**Issue by zhangguanzhang** [chromedp/chromedp#433] opened 2019-07-13 12:49 UTC
#### What versions are you running?
the latest
 75.0.3770.100
1.12.6
</pre>

#### What did you do? Include clear steps.
upload file

--------
Clicking on the div will bring up the file selection window. After selecting the file, it will be uploaded automatically, instead of selecting the file and clicking the button to upload it.
the example is click the submit button to upload,can not did this type

**Comment by zhangguanzhang** [comment] 2019-07-13 14:16
the js use the `WebUploader` to upload, how could i upload file auto

**Comment by zhangguanzhang** [comment] 2019-07-13 14:32
code:
```
chromedp.SetUploadFiles(`#up-ready`, []string{`C:\Users\guanzhang\Desktop\Primitive Technology - Crossdraft kiln-RnvtXikwrIU.mp4`}, chromedp.ByID),
```
err:
```
2019/07/13 22:31:02 Node is not a file input element (-32000)
```

**Comment by kenshaw** [comment] 2019-07-13 19:55
Can you send the HTML of the page you're trying to use? `SendKeys` also sets the uploaded files. Please see the [upload example](https://github.com/chromedp/examples/blob/master/upload/main.go) in the examples repository.

**Comment by zhangguanzhang** [comment] 2019-07-14 06:51
```
uploadHTML = `<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>

<div id="picker">click me to choose file</div>

<script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.staticfile.org/webuploader/0.1.0/webuploader.html5only.min.js"></script>

<script>
    var uploader = WebUploader.create({
        auto: true,
        // 文件接收服务端。
        server: '/upload',

        // 选择文件的按钮。可选。
        // 内部根据当前运行是创建，可能是input元素，也可能是flash.
        pick: '#picker',

        // 不压缩image, 默认如果是jpeg，文件上传前会压缩一把再上传！
        resize: false
    });

</script>

</body>
</html>
```

**Comment by zhangguanzhang** [comment] 2019-08-04 07:25
It;s not question, I saw the cdp of the nodejs could do this

**Comment by mvdan** [comment] 2019-08-15 12:52
Well, this issue is phrased as a question, and you're stating a problem you're having with your code - so this is more of a question than a bug report. The example that @kenshaw linked to earlier works; have you tried that?

If you want us to debug this, please provide a small and self-contained `main.go` to reproduce the problem. Something like the HTML you pasted above with the relevant chromedp code.

**Comment by zhangguanzhang** [comment] 2019-08-19 07:44
It has no submit button, so don't need `chromedp.Click`
```
// Command upload is a chromedp example demonstrating how to upload a file on a
// form.
package main

import (
    "context"
    "flag"
    "fmt"
    "io/ioutil"
    "log"
    "net/http"
    "os"

    "github.com/chromedp/chromedp"
)

var (
    flagPort = flag.Int("port", 8544, "port")
)

func main() {
    flag.Parse()

    // get wd
    wd, err := os.Getwd()
    if err != nil {
        log.Fatal(err)
    }

    filepath := wd + "/main.go"

    // get some info about the file
    fi, err := os.Stat(filepath)
    if err != nil {
        log.Fatal(err)
    }

    // start upload server
    result := make(chan int, 1)
    go uploadServer(fmt.Sprintf(":%d", *flagPort), result)

    // create context
    ctx, cancel := chromedp.NewContext(context.Background())
    defer cancel()

    // run task list
    var sz string
    err = chromedp.Run(ctx, upload(filepath, &sz))
    if err != nil {
        log.Fatal(err)
    }

    log.Printf("original size: %d, upload size: %d", fi.Size(), <-result)
}

func upload(filepath string, sz *string) chromedp.Tasks {
    return chromedp.Tasks{
        chromedp.Navigate(fmt.Sprintf("http://localhost:%d", *flagPort)),
        chromedp.SendKeys(`input[type=file]`, filepath, chromedp.NodeVisible),
        //chromedp.Click(`input[name="submit"]`),
        chromedp.Text(`#result`, sz, chromedp.ByID, chromedp.NodeVisible),
    }
}

func uploadServer(addr string, result chan int) error {
    // create http server and result channel
    mux := http.NewServeMux()
    mux.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
        fmt.Fprintf(res, uploadHTML)
    })
    mux.HandleFunc("/upload", func(res http.ResponseWriter, req *http.Request) {
        f, _, err := req.FormFile("upload")
        if err != nil {
            http.Error(res, err.Error(), http.StatusBadRequest)
            return
        }
        defer f.Close()

        buf, err := ioutil.ReadAll(f)
        if err != nil {
            http.Error(res, err.Error(), http.StatusBadRequest)
            return
        }

        fmt.Fprintf(res, resultHTML, len(buf))

        result <- len(buf)
    })
    return http.ListenAndServe(addr, mux)
}

const (
    uploadHTML = `<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>

<div id="picker">click me to choose file</div>

<script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.staticfile.org/webuploader/0.1.0/webuploader.html5only.min.js"></script>

<script>
    var uploader = WebUploader.create({
        auto: true,
        // 文件接收服务端。
        server: '/upload',

        // 选择文件的按钮。可选。
        // 内部根据当前运行是创建，可能是input元素，也可能是flash.
        pick: '#picker',

        // 不压缩image, 默认如果是jpeg，文件上传前会压缩一把再上传！
        resize: false
    });

</script>

</body>
</html>`
    resultHTML = `<!doctype html>
<html>
<body>
  <div id="result">%d</div>
</body>
</html>
)

```

**Comment by mvdan** [comment] 2019-11-25 14:16
Sorry, but that program to reproduce your bug is pretty large, and seems to use heavy javascript files. I tried running in a non-headless Chrome browser, and it just crashes. I don't think there's anything we can debug here, because I don't even know where to start without spending large amounts of time investigating.

Do you have a simpler way to reproduce the bug? For example, under fifty lines of Go with no external javascript dependencies.

**Comment by zhangguanzhang** [comment] 2019-11-28 12:58
I think that the current front-end webpage will often cancel the submit button. My previous comments already have html for this scene.

**Comment by ysmood** [comment] 2020-03-04 11:07
@zhangguanzhang you can try to use [rod](https://github.com/ysmood/rod). It will work as expected, here's the example:

```go
package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"

	"github.com/ysmood/rod"
)

var (
	flagPort = flag.Int("port", 8544, "port")
)

func main() {
	flag.Parse()

	// get wd
	wd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	filepath := wd + "/main.go"

	// get some info about the file
	fi, err := os.Stat(filepath)
	if err != nil {
		log.Fatal(err)
	}

	// start upload server
	result := make(chan int, 1)
	go uploadServer(fmt.Sprintf(":%d", *flagPort), result)

	rod.New().Connect().
		Page(fmt.Sprintf("http://127.0.0.1:%d", *flagPort)).
		Element("input").
		SetFiles(filepath)

	log.Printf("original size: %d, upload size: %d", fi.Size(), <-result)
}

func uploadServer(addr string, result chan int) error {
	// create http server and result channel
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		fmt.Fprintf(res, uploadHTML)
	})
	mux.HandleFunc("/upload", func(res http.ResponseWriter, req *http.Request) {
		f, _, err := req.FormFile("file")
		if err != nil {
			http.Error(res, err.Error(), http.StatusBadRequest)
			return
		}
		defer f.Close()

		buf, err := ioutil.ReadAll(f)
		if err != nil {
			http.Error(res, err.Error(), http.StatusBadRequest)
			return
		}

		fmt.Fprintf(res, resultHTML, len(buf))

		result <- len(buf)
	})
	return http.ListenAndServe(addr, mux)
}

const (
	uploadHTML = `<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>

<div id="picker">click me to choose file</div>

<script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.staticfile.org/webuploader/0.1.0/webuploader.html5only.min.js"></script>

<script>
    var uploader = WebUploader.create({
        auto: true,
        server: '/upload',
        pick: '#picker',
        resize: false
    });

</script>

</body>
</html>`
	resultHTML = `<!doctype html>
<html>
<body>
  <div id="result">%d</div>
</body>
</html>`
)

```

**Comment by ZekeLu** [comment] 2021-05-13 09:53
@zhangguanzhang In fact, you just have a small issue in your code :joy: :

```diff
-chromedp.SendKeys(`input[type=file]`, filepath, chromedp.NodeVisible),
+chromedp.SendKeys(`input[type=file]`, filepath, chromedp.ByQuery),
```

The default query option for a query action is `chromedp.BySearch`. The selector is a css selector here, so you should use `chromedp.ByQuery`. The change is tested and it works.

Closing.

**Closed by ZekeLu** 2021-05-13 09:53 UTC
Labels: needs info, question
