### ISSUE TITLE
chrome failed to start:\n\xd5\xfd춬F\xd3Оg\xd3[\xc6\xf7\xb9\xa4\xd7\xf7\xebA\xb6\xce\xd6\xd0\xe9_\x86\xa2\xa1\xa3\r\n

### ISSUE THREAD

**Issue by driftboat** [chromedp/chromedp#1359] opened 2023-09-07 10:05 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
0.9.2
$ google-chrome --version
116.0.5845.180 
$ go version
1.20.4
```

#### What did you do? Include clear steps.

```go
 opts := append(chromedp.DefaultExecAllocatorOptions[:],
			chromedp.Flag("headless", false),
 
			chromedp.UserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"), //设置UserAgent

		)
		if len(chromepath) != 0 {
			opts = append(opts, chromedp.ExecPath(chromepath))
		}
		if len(userdataDir) != 0 {
			opts = append(opts, chromedp.UserDataDir(userdataDir))
		} else {
			appData, _ := os.UserCacheDir()
			ud := appData + "/Google/Chrome/User Data"
			opts = append(opts, chromedp.UserDataDir(ud))
		}
		allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
		defer cancel()

		// create context
		ctx, cancel := chromedp.NewContext(allocCtx)
		defer cancel()

		// headers := map[string]interface{}{
		// 	"Sec-Ch-Ua-Platform": "\"Windows\"",
		// 	"Sec-Ch-Ua":          "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\"",
		// }

		err := chromedp.Run(ctx,
			//network.SetExtraHTTPHeaders(network.Headers(headers)),
			chromedp.Navigate("https://www.google.com"),
		)
		if err != nil {
			logrus.Error(err)
		}
```

**Comment by driftboat** [comment] 2023-09-07 10:09
If I close all chrome browsers and then start the program, it will work fine. If I execute the program while chrome is open, this error will be reported.

**Comment by ZekeLu** [comment] 2023-09-08 02:06
Chrome works as designed. Closing as a duplicate of #1147.

**Closed by ZekeLu** 2023-09-08 02:06 UTC
