### ISSUE TITLE
`dom.GetDocument()` will make the browser change NodeIds and should not be called in user code

### ISSUE THREAD

**Issue by lmittmann** [chromedp/chromedp#762] opened 2021-03-01 15:46 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.6.5
$ google-chrome --version
Google Chrome 88.0.4324.96
$ go version
go version go1.16 linux/amd64
</pre>

#### What did you do? Include clear steps.

I am getting the raw html of a site using `chromedp.ActionFunc`. However, after running `chromedp.ActionFunc` any further tasks, like `chromedp.WaitVisible` or `chromedp.SendKeys` block forever. The example below will not terminate, only if the line `chromedp.WaitVisible("h1"),` is commented out, or moved above the `chromedp.ActionFunc` it finishes.

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/chromedp"
)

func main() {
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	var body string
	err := chromedp.Run(ctx,
		chromedp.Navigate("https://example.com"),
		chromedp.WaitReady("body"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			node, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return fmt.Errorf("could not get doc: %w", err)
			}

			body, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
			if err != nil {
				return fmt.Errorf("could not get html: %w", err)
			}
			return nil
		}),
		chromedp.WaitVisible("h1"), // <- this will block for ever
	)
	if err != nil {
		log.Fatalf("Failed to open site: %v", err)
	}

	log.Print(body)
}
```

#### What did you expect to see?

I expect to run further tasks in the browser after running an `chromedp.ActionFunc` task.

#### What did you see instead?

Task ran after `chromedp.ActionFunc` block forever.

**Comment by ZekeLu** [comment] 2021-03-02 11:23
## What's wrong?

According to my test, `dom.GetDocument().Do(ctx)` will cause the NodeIds in the browser to change, which will make those NodeIds stored in  `chromedp` stale. Which in turn will make `chremedp` out of order.

Here is the log that shows the NodeIds have been changed (just the interested entries are left):

```
2021/03/02 18:33:35 -> {"id":15,"sessionId":"2CE25C3047911DBCA12F308CD41C1AE4","method":"DOM.getDocument","params":{}}
2021/03/02 18:33:35 <- {"id":15,"result":{"root":{"nodeId":1,"backendNodeId":3,"nodeType":9,"nodeName":"#document","localName":"","nodeValue":"","childNodeCount":2,"children":[{"nodeId":2,"parentId":1,"backendNodeId":4,"nodeType":10,"nodeName":"html","localName":"","nodeValue":"","publicId":"","systemId":""},{"nodeId":3,"parentId":1,"backendNodeId":5,"nodeType":1,"nodeName":"HTML","localName":"html","nodeValue":"","childNodeCount":2,"children":[{"nodeId":4,"parentId":3,"backendNodeId":6,"nodeType":1,"nodeName":"HEAD","localName":"head","nodeValue":"","childNodeCount":5,"attributes":[]},{"nodeId":5,"parentId":3,"backendNodeId":7,"nodeType":1,"nodeName":"BODY","localName":"body","nodeValue":"","childNodeCount":1,"attributes":[]}],"attributes":[],"frameId":"418B15B13ECB3C8B5D2A5F377DAD8C07"}],"documentURL":"https://example.com/","baseURL":"https://example.com/","xmlVersion":""}},"sessionId":"2CE25C3047911DBCA12F308CD41C1AE4"}
2021/03/02 18:33:35 -> {"id":16,"sessionId":"2CE25C3047911DBCA12F308CD41C1AE4","method":"DOM.getDocument","params":{}}
2021/03/02 18:33:35 <- {"id":16,"result":{"root":{"nodeId":6,"backendNodeId":3,"nodeType":9,"nodeName":"#document","localName":"","nodeValue":"","childNodeCount":2,"children":[{"nodeId":7,"parentId":6,"backendNodeId":4,"nodeType":10,"nodeName":"html","localName":"","nodeValue":"","publicId":"","systemId":""},{"nodeId":8,"parentId":6,"backendNodeId":5,"nodeType":1,"nodeName":"HTML","localName":"html","nodeValue":"","childNodeCount":2,"children":[{"nodeId":9,"parentId":8,"backendNodeId":6,"nodeType":1,"nodeName":"HEAD","localName":"head","nodeValue":"","childNodeCount":5,"attributes":[]},{"nodeId":10,"parentId":8,"backendNodeId":7,"nodeType":1,"nodeName":"BODY","localName":"body","nodeValue":"","childNodeCount":1,"attributes":[]}],"attributes":[],"frameId":"418B15B13ECB3C8B5D2A5F377DAD8C07"}],"documentURL":"https://example.com/","baseURL":"https://example.com/","xmlVersion":""}},"sessionId":"2CE25C3047911DBCA12F308CD41C1AE4"}
```

You see that the the NodeIds  for the same `backendNodeId: 3` are different.

The behavior of  `DOM.getDocument` is weird, and it's  not documented explicitly. The most related information I can find on [Chrome DevTools Protocol document](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#type-Node) are:

> DOM.Node:  DOM interaction is implemented in terms of mirror objects that represent the actual DOM nodes. DOMNode is a base node mirror type.

> NodeId: Node identifier that is passed into the rest of the DOM messages as the nodeId. Backend will only push node with given id once. It is aware of all requested nodes and will only fire DOM events for nodes known to the client.

Since `chromedp` depends on `NodeId` badly, I think it should have a note to say that `dom.GetDocument()` should not be used directly. And according to https://github.com/puppeteer/puppeteer/pull/71#issuecomment-314599749, maybe we should  reconsider how to use the DOM domain in `chromedp`.

## A workaround

Back to the issue, in fact,  it's easy to get the raw html without running into this issue.  You just need to use `chromedp.OuterHTML`. Here are the changes  to your code:

```diff
 package main
 
 import (
    "context"
-   "fmt"
    "log"
 
-   "github.com/chromedp/cdproto/dom"
    "github.com/chromedp/chromedp"
 )
 
 func main() {
    ctx, cancel := chromedp.NewContext(context.Background())
    defer cancel()
 
    var body string
    err := chromedp.Run(ctx,
        chromedp.Navigate("https://example.com"),
        chromedp.WaitReady("body"),
-       chromedp.ActionFunc(func(ctx context.Context) error {
-           node, err := dom.GetDocument().Do(ctx)
-           if err != nil {
-               return fmt.Errorf("could not get doc: %w", err)
-           }
-
-           body, err = dom.GetOuterHTML().WithNodeID(node.NodeID).Do(ctx)
-           if err != nil {
-               return fmt.Errorf("could not get html: %w", err)
-           }
-           return nil
-       }),
-       chromedp.WaitVisible("h1"), // <- this will block for ever
+       chromedp.OuterHTML("html", &body, chromedp.ByQuery),
+       chromedp.WaitVisible("h1"),
    )
    if err != nil {
        log.Fatalf("Failed to open site: %v", err)
    }
 
    log.Print(body)
 }
```

BWT, maybe `chromedp.WaitReady` and `chromedp.WaitVisible` don't behave as you think. Please check the doc and the source code.

**Comment by ysmood** [comment] 2021-03-07 21:36
@ZekeLu Not just `DOM.getDocument`, read the doc of [DOM.getDocument](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-documentUpdated): "Fired when Document has been totally updated. Node ids are no longer valid."

> maybe we should reconsider how to use the DOM domain in chromedp.

Maybe you can copy the design from [Rod](https://github.com/go-rod/rod/) to Chromedp.

**Comment by ZekeLu** [comment] 2021-03-08 02:52
I think  you meant the `DOM.documentUpdated` event.  Yes, I have read that doc, and it has been handle by `chromedp`:

https://github.com/chromedp/chromedp/blob/e2970556e3d05f3259c464faeed1ec0e862f0560/target.go#L232-L254

And it handled it by calling `DOM.getDocument`, that's why the user should not call it again.

I think the problem is that is not documented that the call to `DOM.getDocument` will cause the node ids become invalid. And the name is a little misleading. The key is not to call `dom.GetDocument` in `chromedp` directly.

**Comment by ysmood** [comment] 2021-03-08 13:31
@ZekeLu Yes, the problem is the `t.frameMu` chromedp still can't 100% prevent the race condition. For example, if you query a node and get the node id, then the `DOM.documentUpdated` happens because the goroutine handles the event is blocked by some slow consumer, the node id will be invalid even the user has never called the `dom.GetDocument` directly.

That's why I say chromedp should follow a similar design about how to handle the remote node: using the object id, not the node id.

**Comment by ZekeLu** [comment] 2021-03-13 11:47
> the `DOM.documentUpdated` happens because the goroutine handles the event is blocked by some slow consumer

It's documented that the handler should avoid blocking at all costs.

https://github.com/chromedp/chromedp/blob/e2970556e3d05f3259c464faeed1ec0e862f0560/chromedp.go#L675-L678

Anyway, I got your point. The node id will become invalid. But if not caused by calling to `dom.GetDocument`, then it should be caused by page reloading or page navigation. In this case, the remote object id should become invalid too (I'm not sure about this. Please correct me if I'm wrong).

That said, I have taken a look into `Rod` and found many things to learn from. Next time when I have an issue which can not be addressed gracefully with `chromedp`, I will try `Rob`'s way.

Thank you very much!

**Comment by ysmood** [comment] 2021-03-13 12:49
@ZekeLu If you run actions after the page is loaded, then might be fine. There will be two `DOM.documentUpdated` for each navigation, it's still a mystery for me why it's not one, and you can run `DOM.querySelector` before the `DOM.documentUpdated` events. Also, there's no doc to say only page reloading or page navigation will trigger `DOM.documentUpdated`, maybe we should read the source code of chromium to understand the details.

**Comment by ZekeLu** [comment] 2021-05-12 09:12
It seems that there is nothing more to do now. Closing.

**Closed by ZekeLu** 2021-05-12 09:12 UTC

**Comment by larytet** [comment] 2021-05-23 04:11
`chromedp.OuterHTML("html", &body, chromedp.ByQuery),`

What happens if the page is not containing <HTML> tag?

**Comment by ZekeLu** [comment] 2021-05-23 04:52
If the page contains arbitrary content and you don't know the element to select in advance, then maybe you could try [Fetch.getResponseBody](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-getResponseBody).
