### ISSUE TITLE
how to use chromedp.UserDataDir

### ISSUE THREAD

**Issue by zlq1252** [chromedp/chromedp#1120] opened 2022-07-20 11:23 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
$ go version
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
import (
	"context"
	"github.com/chromedp/chromedp"
	"github.com/gin-gonic/gin"
	"test720/dp"
)
func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.NoDefaultBrowserCheck,                                  //不检查默认浏览器
		chromedp.Flag("headless", false),                                //开启图像界面,重点是开启这个
		chromedp.Flag("enable-automation", false),                       // 绕过自动化测试工具检测
		chromedp.Flag("disable-blink-features", "AutomationControlled"), // 也是绕过自动化测试工具检测
		chromedp.DisableGPU,
		chromedp.Flag(`disable-extensions`, false),
		chromedp.UserDataDir("D:\\testdata\\User Data"),
		chromedp.Flag("disable-sync", false),
		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"),
	)

	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)

	r := gin.Default()
	r.GET("/query", func(c *gin.Context) {
		dp.DpStart(allocCtx)
		c.JSON(200, gin.H{
			"message": "pong1",
		})
	})
	r.Run(":8086") // listen and serve on 0.0.0.0:8080
}
func DpStart(allocCtx context.Context) {

	var allNodes []*cdp.Node
	ctx, cancel := chromedp.NewContext(
		allocCtx,
		chromedp.WithLogf(log.Printf),
	)
	defer cancel()
	chromedp.Run(ctx,
		chromedp.Navigate("https://pan.baidu.com"),
		chromedp.Sleep(time.Second*1),
		chromedp.Nodes("/html/body/section/main/div/section/main/div/div[1]/div[3]/button", &allNodes),
	)
	fmt.Println("len(allNodes)==>", len(allNodes))
	if len(allNodes) == 1 {
		fmt.Println("登录")
		doLogin(ctx)
	} else {
		fmt.Println("无需登录")
	}
}
```

#### What did you expect to see?

I hope that when I request the query interface for the first time, I will be logged in after passing the judgment. When I successfully log in, the browser will automatically close. When I request the query interface for the second time, the browser can carry my previous login status, that is, Executed this code fmt.Println("No login required")
#### What did you see instead?
But when I successfully logged in, when I requested the query interface for the second time, I still asked me to log in the same as the first time, and did not bring the previous login status, so is my posture incorrect? Please correct me. Thank you

**Comment by ZekeLu** [comment] 2022-07-20 12:04
See #818.

**Comment by zlq1252** [comment] 2022-08-03 07:20
I added chromedp.Cancel(browserCtx) but still can't save the cookie normally. When I run it for the second time, the cookie is still abnormal. I feel that the program ends without saving UserData. How should I improve it?
```
func main() {
	test()
}

func test() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.NoDefaultBrowserCheck,                                  //不检查默认浏览器
		chromedp.Flag("headless", false),                                //开启图像界面,重点是开启这个
		chromedp.Flag("enable-automation", false),                       // 绕过自动化测试工具检测
		chromedp.Flag("disable-blink-features", "AutomationControlled"), // 也是绕过自动化测试工具检测
		chromedp.DisableGPU,
		chromedp.Flag(`disable-extensions`, false),
		chromedp.UserDataDir("C:\\taoUtils\\User Data3"),
		chromedp.UserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"),
	)

	allocatorCtx, allocatorCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	// 这取决于您将如何管理浏览器的生命周期，也许您不想在这里调用 allocatorCancel()
	defer allocatorCancel()

	browserCtx, browserCancel := chromedp.NewContext(allocatorCtx)
	// 这取决于您将如何管理浏览器的生命周期，也许您不想在这里调用 allocatorCancel()
	defer browserCancel()
	// 现在启动浏览器
	if err := chromedp.Run(browserCtx); err != nil {
		log.Fatal(err)
	}
	// 现在 browserCtx 可以直接使用了
	// 我将在这里省略超时上下文

	if err := chromedp.Run(browserCtx,
		chromedp.Navigate("https://shop108231385.taobao.com/search.htm?orderType=newOn_desc"),
		chromedp.ActionFunc(func(ctx context.Context) error {
			html := ""
			chromedp.Run(ctx, network.Enable(),
				chromedp.OuterHTML("html", &html),
				//chromedp.CaptureScreenshot(&buf),
			)
			fmt.Println(html)
			if strings.Contains(html, `登录`) || strings.Contains(html, `<div class="sufei-dialog sufei-dialog-kissy" style="display: block;">`) {
				fmt.Println("需要登录")
				err := chromedp.Run(browserCtx,
					chromedp.Navigate("https://login.taobao.com/member/login.jhtml?style=mini&newMini2=true&from=sm&full_redirect=false&redirectURL=https://shop108231385.taobao.com/search.htm?orderType=newOn_desc"),
					chromedp.WaitVisible(`//*[@id="fm-login-id"]`),
					chromedp.SendKeys(`//*[@id="fm-login-id"]`, "xxxxxxxx"),
					chromedp.SendKeys(`//*[@id="fm-login-password"]`, "xxxxxxxx"),
					chromedp.Sleep(1*time.Second),
					chromedp.Click(`//*[@id="login-form"]/div[4]/button`),
					chromedp.Sleep(time.Second*8),
				)
				if err != nil {
					fmt.Println("err==>")
				}
			} else {
				fmt.Println("无需登录")

			}
			//ioutil.WriteFile("2.png", buf, 0644)
			return nil
		}),
	); // tasks
	err != nil {
		fmt.Println("出错了")
		log.Fatal(err)
	}
	chromedp.Cancel(browserCtx)
}
```

**Comment by zlq1252** [comment] 2022-08-03 07:30
> 见#818。
I have posted a new question, please help to read it, thank you

**Comment by ZekeLu** [comment] 2022-08-03 10:05
I won't look into this issue because it requires to login to a third-party service. If you believe that it's a issue of  `chromedp.Cancel`, please create a self-contained demo to show that. You can create a self-contained demo based on https://github.com/chromedp/examples/blob/master/cookie/main.go.

**Comment by zlq1252** [comment] 2022-08-03 10:54
If I do not use chromedp.Cancel but replace chromedp.Cancel with time.Sleep(35 * time.Second), the cookie can be stored normally, and it can be used normally the next time it is started. The default time for the browser to store the cookie seems to be 30s

**Comment by ZekeLu** [comment] 2022-08-03 11:47
Can you clone the repository and run this test?

https://github.com/chromedp/chromedp/blob/a325ba9f11c323bbd30b9b0b5298ad7a04e13a65/chromedp_test.go#L672-L726

**Comment by zlq1252** [comment] 2022-08-04 05:24
sorry I can't run it ，This may be because I am a beginner in golang

**Comment by ZekeLu** [comment] 2022-08-28 01:04
Closing since there is not a self-contained reproducer without requiring to login a third-party service.

**Closed by ZekeLu** 2022-08-28 01:04 UTC
