### ISSUE TITLE
Have Cancel gracefully close the Browser

### ISSUE THREAD

**Issue by pmurley** [chromedp/chromedp#472] opened 2019-09-18 16:18 UTC
I am doing some work collecting code coverage data on Chromium (not JavaScript coverage, but coverage of the browser source/C++). In order for Chromium to correctly generate the output files containing this coverage data, I need it to close gracefully. I believe the DevTools Protocol `Browser.close()` would work fine.

1. My understanding is that when you cancel a context, the associated browser is closed with SIGKILL. Is that accurate?

2. If so, is there an easy way I can circumvent that to close the browser gracefully? I think that right now, [this if statement](https://github.com/chromedp/chromedp/blob/ff5b4fce079ec7e7e53fc16fd9f1b47569e9ed4b/browser.go#L166) is preventing it. Will there be unintended effects if I just remove that check?

**Comment by mvdan** [comment] 2019-09-20 12:16
Interesting; I didn't know there were use cases where gracefully closing down the entire browser was necessary. I assume gracefully closing down tabs (which is already handled) doesn't cut it for you?

The graceful closing of tabs doesn't happen for the original tab, because the browser can't be left with no tabs.

Your assumptions are correct, I think. We leave `os/exec` handle stopping the process on context cancellation, and it uses `os.Process.Kill`, which seems to just send `SIGKILL`.

I don't think we want `defer cancel()` to do this, for two reasons. First, most users won't need graceful shutdown, which could take extra time or give uninteresting errors. Second, the `cancel()` func alone can't provide any error, while a graceful shutdown needs to report an error; otherwise it's not graceful at all.

So I think the best option is to add this to the `chromedp.Cancel` API. It would send `Browser.close` to the browser, wait for it to report it's finished, and then cancel the underlying context and clean up any leftover resources. The context argument could be wrapped with a timeout too, if one wants to limit the amount of time given to Chrome to close gracefully:

```
// Give Chrome five seconds to shut down properly. After that, kill it.
chromedp.Cancel(context.WithTimeout(ctx, 5 * time.Second))
```

I'd still forbid direct use of `Browser.close` via `chromedp.Run`. If it's available via `chromedp.Cancel`, it doesn't make sense to also allow it via `Run`. We'd need extra code and tests to ensure it does the right thing and doesn't hang chromedp, and I just don't see the point :)

**Comment by pmurley** [comment] 2019-10-18 17:36
Understood -- I think the solution you propose would satisfy my use case. Unfortunately, I'm not able to submit a pull request right now, so no problem if it's not a priority. Thanks as always!

**Comment by pmurley** [comment] 2019-10-25 17:50
Okay, so I've been playing around with a little patch here, but I have a couple questions. First off, here's the updated `chromedp.Cancel` function I am using:

```
func Cancel(ctx context.Context) error {
	c := FromContext(ctx)
	if c == nil {
		return ErrInvalidContext
	}

	err := c.Browser.Execute(ctx, browser.CommandClose, nil, nil)
	if err != nil {
		return err
	}

	c.cancel()
	c.closedTarget.Wait()
	// If we allocated, wait for the browser to stop.
	if c.allocated != nil {
		<-c.allocated
	}
	return c.cancelErr
}
```

And here's the way I'm using it:
```
	err = chromedp.Cancel(context.withTimeout(ctx, 5 * time.Second))
	if err != nil {
		log.Log.Error(err)
	}

	// cancel()
```

First question: Is this basically what you had envisioned?

It seems to be working, but I get a weird error message immediately after the browser closes. Second question: Any idea what might be going on here?
```
2019/10/25 12:40:28 ERROR: could not unmarshal event: parse error: syntax error near offset 0 of 'argetId":"...'
```
Third question: You mentioned that you would still like to prohibit direct calls to `browser.Close()`, but I've had to remove the check that currently does this in `browser.go` to get this to work. Any thoughts on how to do that better?

Thanks as always!

**Comment by mvdan** [comment] 2019-11-27 13:33
Sorry I didn't respond to your comment above. We do work on chromedp in chunks, and sometimes it's hard to find the time to keep up with existing issues. I'll take a look at this today, as I've been fixing a number of other issues for a bugfix release.

**Comment by alanrothschild** [comment] 2019-12-10 20:29
Greetings - I put in a pull request based on pmurley's snippet - sadly I seem to have broken some of the tests - I will dig in more later tonight

**Comment by alanrothschild** [comment] 2019-12-10 22:14
No joy - I added a condition to only send browser close command if the number of pages is 1 but this feels wrong and some tests are still failing

**Comment by mvdan** [comment] 2019-12-10 22:17
@alanrothschild is there a particular reason you want to work on this? It's going to be tricky work to implement it properly, so I'd suggest that it's not a good place to start contributing to chromedp.

**Comment by alanrothschild** [comment] 2019-12-10 23:13
First, thank you @mvdan and all the chromedp contributors for an excellent solution.  I chose this issue because we have an internal tool that drives a non-headless browser and when it is cancelled it doesn't end up in a consistent state for subsequent runs.  We get the warnings about chrome not shutting down properly and cookies aren't consistently saved.  So I chose this issue because it impacted us and I wanted to pitch in, but yes it does seem like it's more challenging than it seemed at first glance.  If you have a different idea on how to tackle it (because I feel like what I've done might be off course), I am happy to try to help.

**Comment by mvdan** [comment] 2019-12-20 22:24
@pmurley @alanrothschild do either of you have a way to reliably test this? The feature is pretty much complete and sitting on my laptop, but I've failed to write a proper test on three different occasions.

First, I tried to somehow cause a "chrome didn't shut down properly" error, by reusing a data directory, but couldn't.

Then, I tried setting up a "beforeunload" js function, to print something to the console. Supposedly, if the tab and browser were closedgracefully, I should receive that console event. But nope.

What @pmurley initially talked about was code coverage from Chrome itself, so I assume I can't reuse that. If there is some chrome flag that does something before shutting down properly, that could be helpful too.

I'm hesitant to merge this feature without a proper way to test it. I really don't know if it works well, and without a test, it could break at any moment.

**Comment by alanrothschild** [comment] 2019-12-20 23:16
@mvdan the "chrome didn't shut down properly" occurs for me when I open a browser with headless=false, navigate to a page, cancel the context and then open the browser again with the same datadir

The code is almost exactly like what was reported here

https://github.com/chromedp/chromedp/issues/504

**Comment by miyajan** [comment] 2019-12-21 02:36
I reported #504. `time.Sleep` for 10 seconds or more was necessary to reproduce the issue. (but I don't know why)

**Comment by mvdan** [comment] 2019-12-23 09:29
Thanks @miyajan, I can actually see the error popup there when using a non-headless browser.

That's only half of the puzzle, though. In an automated test with a headless browser, how do we tell if the browser was closed gracefully or not? We can't rely on UI alerts, of course. The logs don't seem to show anything useful. The data directory of a new, blank browser that got killed is indeed different than a new, blank browser that got closed normally, but there isn't a single file or field we could look at. The main differences are in binary files.

If anyone has a short piece of chromedp code that would only work when the browser is closed gracefully, that would be very helpful to write a test for this.

**Comment by alanrothschild** [comment] 2019-12-25 18:48
@mvdan It looks like there is a file in the data directory named "Local State" - it's formatted as JSON

when the browser isn't closed gracefully, the value for "exited_cleanly" is false

{Local State}{user_experience_metrics}{stability}exited_cleanly=false

I haven't written a test yet but does this seem like what we are looking for?  If yes should I just parse the json file?

Thanks

**Comment by alanrothschild** [comment] 2019-12-28 15:08
Unfortunately - the "Local State" file doesn't exist when chrome is run in headless mode:(  I tried various switches but no luck

**Comment by alanrothschild** [comment] 2020-01-01 23:03
So here's a snippet that opens a browser, navigates to a url that sets a cookie, cancels the context and then opens a new browser, navigates to the same url and tests if same cookie is present.  It is present if I cleanly close the browser (by hand) - it seems not to be present if the context is cancelled

`package main

import (
	"context"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/chromedp/chromedp"
)

var (
	flagPort = flag.Int("port", 8544, "port")
)

func main() {
	flag.Parse()

	go cookieServer(fmt.Sprintf(":%d", *flagPort))

	dir, err := ioutil.TempDir("", "test")
	if err != nil {
		log.Fatal(err)
	}
	defer os.RemoveAll(dir)

	opts := []chromedp.ExecAllocatorOption{
		chromedp.UserDataDir(dir),
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Headless,
	}
	allocCtx, allocCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))

	err = chromedp.Run(ctx,
		chromedp.Navigate(fmt.Sprintf("http://localhost:%d/Set", *flagPort)),
	)
	if err != nil {
		log.Fatal(err)
	}

	cancel()
	allocCancel()

	allocCtx, allocCancel = chromedp.NewExecAllocator(context.Background(), opts...)
	defer allocCancel()
	ctx, cancel = chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))
	defer cancel()

	var res string
	err = chromedp.Run(ctx,
		chromedp.Navigate(fmt.Sprintf("http://localhost:%d/Test", *flagPort)),
		chromedp.EvaluateAsDevTools("document.cookie", &res),
	)
	if err != nil {
		log.Fatal(err)
	}

	if res == "cookie1=value1" {
		fmt.Println("cookie saved")
	} else {
		fmt.Println("cookie not saved")
	}
}

// cookieServer sets a cookie
func cookieServer(address string) error {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(responseWriter http.ResponseWriter, request *http.Request) {
		if request.RequestURI == "/Set" {
			http.SetCookie(responseWriter, &http.Cookie{
				Name:    "cookie1",
				Value:   "value1",
				Expires: time.Now().AddDate(0, 0, 1),
			})
			fmt.Fprintf(responseWriter, "SET COOKIE")
		} else {
			fmt.Fprintf(responseWriter, "OK")
		}
	})
	return http.ListenAndServe(address, mux)
}
`

**Comment by mvdan** [comment] 2020-01-06 07:42
@alanrothschild thanks, using cookies for this purpose is pretty clever if it really breaks when using non-graceful closes. I'll give it a try.

**Comment by mvdan** [comment] 2020-01-12 08:00
Thank you both for the patience. It took another couple of hours of fiddling with the test and the code, but I finally got a version that's reliable with a test.

**Closed** 2020-01-12 07:59 UTC

**Comment by mvdan** [comment] 2020-01-16 13:13
It seems like everyone is happy with the solution here, so I'm closing @alanrothschild's PR. Thanks again for the help coming up with the test code.

**Comment by mvdan** [comment] 2020-05-21 20:21
I have good and bad news. The bad news is that this code had a channel race; see all the recent CI failures, and the commit message above. The good news is that, after some debugging, I was able to track it down. Please update if you use this feature, as otherwise the code isn't really doing a safe and graceful shutdown.
