### ISSUE TITLE
How to send an ideographic space?

### ISSUE THREAD

**Issue by lyekumchew** [chromedp/chromedp#903] opened 2021-08-25 07:14 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.4
$ google-chrome --version
92.0.4515.159
$ go version
go version go1.17 darwin/amd64
```

#### What did you do? Include clear steps.
```go
chromedp.SendKeys(`input[name="name"]`, "　", chromedp.ByQuery, chromedp.NodeVisible)
```

#### What did you expect to see?
It will send an ideographic space to the input box.

#### What did you see instead?
It sends nothing.

Besides, the ideographic space is [U+3000](https://util.unicode.org/UnicodeJsps/character.jsp?a=3000) in Unicode.

**Comment by ZekeLu** [comment] 2021-08-25 09:14
Please try `chromedp.SetValue` or `input.InsertText`. Closing as duplicate of #567.

**Closed by ZekeLu** 2021-08-25 09:14 UTC
