### ISSUE TITLE
Is its possible to do someting with content area. Such as, Put  page number inside the content area

### ISSUE THREAD

**Issue by komgrip** [chromedp/chromedp#1128] opened 2022-07-27 04:02 UTC
Can i do someting with content area. Such as, Put  page number inside the content area

#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.8.2
$ google-chrome --version
Version 103.0.5060.114 (Official Build)
$ go version
go version go1.18.2 windows/amd64
```

#### What did you do? Include clear steps.

```
chromedp.ActionFunc(func(ctx context.Context) error {
			buf, _, err := page.PrintToPDF().
				WithPrintBackground(false).
				WithPreferCSSPageSize(false).
				WithScale(1).
				WithDisplayHeaderFooter(true).
				WithPaperWidth(8.27).
				WithPaperHeight(11.69).
				WithLandscape(false).
				WithMarginTop(0.7).
				WithMarginRight(0).
				WithMarginBottom(0.7).
				WithMarginLeft(0).
				WithHeaderTemplate(" ").
				WithFooterTemplate(" ").
				Do(ctx)
			if err != nil {
				return err
			}
			*res = buf
			return nil
		})
```

#### What did you expect to see?
I want to put  page number inside the content area

#### What did you see instead?
I dont how to customize with a content area

**Comment by ZekeLu** [comment] 2022-07-27 04:13
Duplicate of #1112.

**Closed** 2022-07-27 04:13 UTC
