### ISSUE TITLE
Headless Chrome hangs on Wait() after shutdown

### ISSUE THREAD

**Issue by tscs37** [chromedp/chromedp#81] opened 2017-06-26 19:00 UTC
When using the `--headless` flag using the Wait() method hangs the process after calling Shutdown()

```
import (
	"context"
	"fmt"
	cdp "github.com/knq/chromedp"
)

type BrowserPage struct {
	URL     *url.URL
	Chrome  *cdp.CDP
	Context context.Context
	Cancel  func()
}

func (b BrowserPage) Close() {
	if err := b.Chrome.Shutdown(b.Context); err != nil {
		fmt.Println("Error on shutdown:", err)
	}
	if err := b.Chrome.Wait(); err != nil {
		fmt.Println("Error while waiting for chrome to termiante:", err)
	}
	b.Cancel()
}
```

This happens on Chrome Version 59.0.3071.109 (Official Build) (64-bit) on Arch Linux

**Comment by vially** [comment] 2017-06-29 15:45
I've been affected by this as well. It seems that headless chrome doesn't quit when all the tabs are closed. You have to manually send the SIGTERM signal to the chrome headless process for it to quit.

**Comment by pwaller** [comment] 2017-06-29 16:22
I've also encountered this. There is [this telling comment here](https://github.com/knq/chromedp/blob/fa151e8cf57be2f7cdb3f9b8bf4011d4f015e66c/runner/runner.go#L220-L227) in the `Shutdown` method:

```go
	// osx applications do not automatically exit when all windows (ie, tabs)
	// closed, so send SIGTERM.
	//
	// TODO: add other behavior here for more process options on shutdown?
	if runtime.GOOS == "darwin" && r.cmd != nil && r.cmd.Process != nil {
		return r.cmd.Process.Signal(syscall.SIGTERM)
	}
```

**Comment by vially** [comment] 2017-06-29 16:29
Yes, I've seen that code too. It seems it's currently only executed on OS X. I think it should be changed to be run on headless too. But I guess the tricky part is detecting if it's headless or not.

**Comment by pwaller** [comment] 2017-06-29 16:34
My impression of the codebase is that it was made prior to `--headless` being a thing, requiring some funky setup involving docker containers to get it to work. I've also submitted #76 which makes it work somewhat out of the box - it would be great if you could check it out and provide feedback.

**Comment by kenshaw** [comment] 2017-07-01 13:36
There's no funky docker containers involved. Development on this project started December 25th, 2016. First public release was Jan 24th, 2017. It was developed specifically for `headless_shell`. At least on linux, the reason it may not be exiting immediately is due to locking issues. The OSX aspect is special, because when Chrome runs on OSX it doesn't actually "exit" the process, which is part of the way that OSX deals with windows.

**Comment by stephencheng** [comment] 2017-08-24 06:19
what's the resolution on this?

if apply the same piece of code similar to osx's:

	if runtime.GOOS == "darwin" && r.cmd != nil && r.cmd.Process != nil {
		return r.cmd.Process.Signal(syscall.SIGTERM)
	}


Then this will result in exit code 1 which is not expected

**Comment by yohcop** [comment] 2018-02-22 22:57
This issue was closed, but was there a fix? It still doesn't appear to be fixed for me.

**Comment by daltonfury42** [comment] 2018-06-11 13:01
@kenshaw The issue is still happening. What is a fix?

**Comment by mvdan** [comment] 2019-02-21 23:16
Not sure why this was closed, and there are a few duplicates open. Reopening for now.

**Comment by ideea** [comment] 2019-03-11 14:25
any fix expected here?

**Comment by mvdan** [comment] 2019-03-11 21:06
Have you tried master after https://github.com/chromedp/chromedp/pull/276 got merged? The latest release includes that commit.

**Comment by ideea** [comment] 2019-03-12 08:52
i have macos, still the same.

**Comment by mvdan** [comment] 2019-03-13 11:27
Well, the good news is that the upcoming refactored v2 completely overhauls how Chrome is started and stopped, so I believe this problem should not exist in that new design.

In the meantime, if anyone figures out the root of the problem and a fix for the current chromedp, I'll be happy to review a patch.

**Comment by ideea** [comment] 2019-03-13 13:15
and when it will be released? :) now cause of this i need to postpone my project

**Comment by mvdan** [comment] 2019-03-13 13:17
See https://github.com/chromedp/chromedp/issues/280; I don't want to give an ETA on a stable version. The master branch is stable and for the most part works. If you encounter issues, it should be possible to work around them with a bit of hacking; I don't think there's reason to postpone any projects.

**Comment by mvdan** [comment] 2019-04-02 11:07
The refactor branch has been merged into master, so I'm going to close this issue as fixed. We'll probably release an alpha soon. Until then, feel free to use a commit from master; all tests pass, and we're experimenting with it ourselves, so it should be pretty stable.

**Closed by mvdan** 2019-04-02 11:07 UTC
