### ISSUE TITLE
Waiting for a command from the user

### ISSUE THREAD

**Issue by spaumx** [chromedp/chromedp#1133] opened 2022-08-07 11:06 UTC
#### What versions are you running?

github.com/chromedp/chromedp v0.8.3

#### What did you do? Include clear steps.

I didn't because I don't know how

#### What did you expect to see?
How can I make it so that at startup 1 browser opens and waits for a command through the console or REST API, and performs the actions I need.

**Comment by ZekeLu** [comment] 2022-08-08 03:46
See #1132

**Comment by spaumx** [comment] 2022-08-08 17:08
> See #1132

Probably you didn't understand me

**Comment by ZekeLu** [comment] 2022-08-14 05:07
Duplicate of #1132. Please reopen with more information if you don't agree.

**Closed by ZekeLu** 2022-08-14 05:07 UTC
