### ISSUE TITLE
Iframe doesn't work 2023

### ISSUE THREAD

**Issue by charleslana** [chromedp/chromedp#1381] opened 2023-10-10 12:24 UTC
Hi, was the project abandoned?
This example no longer works in 2023, has anyone managed to click inside an iframe? in 2023, it doesn't work. Example is below

https://github.com/chromedp/chromedp/issues/983#issuecomment-1755268219

**Comment by 31702160136** [comment] 2023-10-10 23:53
我也遇到了这个情况，在iframe里无法点击

**Comment by ZekeLu** [comment] 2023-10-13 15:50
This project is actively maintained.

The purpose of the demo in https://github.com/chromedp/chromedp/issues/983#issuecomment-1755268219 is to show that it does not work because the behavior is by design.

I will close this issue because it does not contain anything new. Please file a new issue and fill the issue template if your issue is not a duplicate of #983.

@31702160136 please check the [chromedp.FromNode](https://pkg.go.dev/github.com/chromedp/chromedp#FromNode) option if what you need is to click in an iframe. See also this test: https://github.com/chromedp/chromedp/blob/f3439ed67c88f7424e9fdd4a3fe780c03f260d44/nav_test.go#L242-L271

**Comment by 31702160136** [comment] 2023-10-13 15:51
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed by ZekeLu** 2023-10-13 15:50 UTC
