### ISSUE TITLE
can't login google with headless mode, run on server

### ISSUE THREAD

**Issue by toannd96** [chromedp/chromedp#996] opened 2022-01-18 11:04 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
Chromium 97.0.4692.71
$ go version
go version go1.17.3 linux/amd64
```

#### What did you do? Include clear steps.

when I signin to my google account at https://accounts.google.com on my local desktop
I use flags

```
opts := append(chromedp.DefaultExecAllocatorOptions[:],
chromedp.Flag("headless", false),
chromedp.Flag("enable-automation", false),
chromedp.Flag("remote-debugging-port", "9222"),
)
```

then i can login, without being warned that the browser is not secure.
Currently, I want to put it on the server to run, but I can't use flag
chromedp.Flag("headless", true)

how do i get it running on the server without chrome browser ?
my code 
```
func loginTask() (context.Context, context.CancelFunc) {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", false),
		chromedp.Flag("enable-automation", false),
		chromedp.Flag("remote-debugging-port", "9222"),
	)
	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
	ctx, cancel := chromedp.NewContext(allocCtx, chromedp.WithLogf(log.Printf))

	// Login google
	googleTask(ctx)

	return ctx, cancel
}

func googleTask(ctx context.Context) {
	email := "//*[@id='identifierId']"
	password := "//*[@id='password']/div[1]/div/div[1]/input"
	buttonEmailNext := "//*[@id='identifierNext']/div/button"
	buttonPasswordNext := "//*[@id='passwordNext']/div/button/span"

	task := chromedp.Tasks{
		chromedp.Navigate(googleSignin),
		chromedp.SendKeys(email, ""),
		chromedp.Sleep(3 * time.Second),

		chromedp.Click(buttonEmailNext),
		chromedp.Sleep(3 * time.Second),

		chromedp.SendKeys(password, ""),
		chromedp.Sleep(3 * time.Second),

		chromedp.Click(buttonPasswordNext),
		chromedp.Sleep(3 * time.Second),
	}

	if err := chromedp.Run(ctx, task); err != nil {
		log.Fatal(err)
	}
}

func main() {
    ctx, cancel := loginTask()
    defer cancel()
}
```
####  What did you expect to see?
Then i can login, without being warned that the browser is not secure.
Currently, I want to put it on the server ubuntu to run, but I can't use flag
chromedp.Flag("headless", true)

#### What did you see instead?
how do i get it running on the server ubuntu without chromium browser ?

**Comment by ZekeLu** [comment] 2022-01-19 04:42
1. When Chrome is running in headless mode, its  `user-agent` string contains `HeadlessChrome`. I guess that's why it does not work. If  that's true, you don't have to use the `chromedp.Flag("headless", false)`; instead, you can use the `chromedp.UserAgent` option to change the `user-agent` string directly.
2. As of now, `chromedp.Headless` is in `chromedp.DefaultExecAllocatorOptions`. So most of the time, you don't need `chromedp.Flag("headless", true)`
3. If you run your app in a container, the image [chromedp/headless-shell](https://github.com/chromedp/docker-headless-shell)  is recommended.

**Comment by dactoankmapydev** [comment] 2022-01-19 06:34
i try to leave ```chromedp.Flag("headless", false)```
and add ```chromedp.UserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36")```
but on my local i get no success response when i successfully login google account

**Comment by zlq1252** [comment] 2022-05-23 04:25
> 我尝试删除`chromedp.Flag("headless", false)` 和添加`chromedp.UserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36")` ，但在我的本地我没有登录谷歌帐户 @ZekeLu

hello bro, is this problem solved?

**Comment by HudsonSilva83** [comment] 2022-07-07 03:13
Alguma solução?

**Comment by Kle0s** [comment] 2022-10-23 07:03
Has someone managed to solve this issue?

**Comment by BlackSinny** [comment] 2022-10-23 09:00
i also has current problem ....
has someone can help me
In my mac os , i use headless mode ,code not word yet,but i change it to false ,all code are right...

**Comment by toannd96** [comment] 2023-01-18 03:45
can i help me ?

**Comment by ZekeLu** [comment] 2023-01-26 02:03
I have taken a screenshot with the following demo:

<details>
<summary>demo</summary>

```go
package main

import (
	"context"
	"flag"
	"log"
	"os"
	"time"

	"github.com/chromedp/chromedp"
)

var (
	email string
)

func main() {
	flag.StringVar(&email, "email", "", "user name")
	flag.Parse()

	if email == "" {
		log.Fatal("Please provide the email.")
	}

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.UserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"),
	)
	ctx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	var buf []byte

	if err := chromedp.Run(ctx,
		chromedp.Navigate("https://accounts.google.com/"),
		chromedp.SendKeys("#identifierId", email, chromedp.ByQuery),
		chromedp.Sleep(3*time.Second),

		chromedp.Click("#identifierNext > div > button", chromedp.ByQuery),
		chromedp.Sleep(3*time.Second),

		chromedp.CaptureScreenshot(&buf),
	); err != nil {
		log.Fatal(err)
	} else {
		if err := os.WriteFile(time.Now().Format(time.RFC3339)+".png", buf, 0644); err != nil {
			log.Fatal(err)
		}
	}
}
```
</details>

And here is the screenshot:
![2023-01-25T15:00:09Z](https://user-images.githubusercontent.com/1063615/214737570-ac1112c3-61e9-4030-9266-94c73e1a93d3.png)

That means google has enabled bot detection. For such kind of issue, you should try other projects that focus on preventing bot detection. For example, [puppeteer-extra-plugin-stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth). I think the issue https://github.com/berstend/puppeteer-extra/issues/668 is the same as this one. I have tested that solution. Unfortunately, it does not work any more.

I'm sorry but I'm going to close this issue because it's not the purpose of `chromedp` to fight with bot detection.

Duplicate of #877.

**Closed by ZekeLu** 2023-01-26 02:03 UTC

**Comment by agilebean** [comment] 2024-07-22 00:01
@ZekeLu is right that the google login rejects bots.
However, you can try the following settings to disable it:
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

# configure headless browser
    chrome_options = Options()
    # # TRICKY: disable Google bot prevention
    chrome_options.add_argument("--disable-web-security")
    chrome_options.add_argument("--allow-running-insecure-content")
    chrome_options.add_argument("--whitelisted-ips [your ip address]")
    chrome_options.add_argument('--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"')
chrome_options.add_argument(f"--header=Authorization: Bearer {service_account_token}")
    driver = webdriver.Chrome(options=chrome_options)
```
