### ISSUE TITLE
How to get all pages included popup (not newContext)

### ISSUE THREAD

**Issue by tuwibu** [chromedp/chromedp#1394] opened 2023-11-12 03:50 UTC
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
<!--replace this line with the output-->
$ google-chrome --version
<!--replace this line with the output-->
$ go version
<!--replace this line with the output-->
```

#### What did you do? Include clear steps.

```go
put your source code here
```

##### For example: 
When I click on login, it opens a popup, I want to know how to switch the page to that popup
That popup is generated from the website's behavior, not the chromedp code
[https://galxe.com/](https://galxe.com/)
==> login ==> discord or twitter or metamask

**Comment by ZekeLu** [comment] 2023-11-13 07:36
Closing as duplicate of #815.

**Closed by ZekeLu** 2023-11-13 07:36 UTC
