### ISSUE TITLE
NewTarget requires local runner instead of allowing remote instance

### ISSUE THREAD

**Issue by jmhodges** [chromedp/chromedp#244] opened 2018-11-04 06:36 UTC
This is really nice software, btw.

I'm connecting to a chromedp/headless-shell container instance and I can't seem to allocate or set a target on my `CDP`'s from the `CDP.NewTarget` function call. It calls `CDP.newTarget` and that has this line:

```
	cl := c.r.Client(opts...)
```

That throws a panic because `c.r` is nil when `chromedp.New` was created with `		chromedp.WithURL` and no runner from a local executable.

Puppeteer has a `createIncognitoBrowserContext` and a `createBrowserContext` that handles this stuff nicely. It'd be cool to get a similar set of functionality without digging into `cdproto` itself.

**Comment by jmhodges** [comment] 2018-11-06 02:17
Hrm, trying to get this functionality with 

```
		chromedp.ActionFunc(func(ctx context.Context, h cdp.Executor) error {
			browserID, err := target.CreateBrowserContext().Do(ctx, h)
			if err != nil {
				return fmt.Errorf("error during CreateBrowserContext: %s", err)
			}
```

gets a "Not allowed." error back from CreateBrowserContext. I'm not sure how to fix that. Any ideas?

**Comment by jmhodges** [comment] 2018-11-06 02:47
Hrm, even `CDP.NewTarget` just times out. Strange.

**Comment by bl-nero** [comment] 2018-12-05 14:40
We have just crashed against exactly the same issue after Chrome 71 upgrade, only with the JS client. The issue is probably not with the client library, but with the protocol implementation itself.

**Comment by mvdan** [comment] 2019-04-04 19:22
@jmhodges we've reworked the API and internal design for the upcoming v0.2 in master. Could you clarify what you're trying to do? I assume you're trying to use chromedp with a chrome that's already running on a container?

It could also help if you showed how you'd do this with puppeteer, as we can probably learn from their API design.

**Comment by jmhodges** [comment] 2019-04-04 22:02
Ah, I think I was testing out specific versions of Chrome to find the version that first triggered some bug. It was trickier to get the various builds on macOS than it was to get working containers or something. Or maybe I was checking to see if it happened in Linux when it was/wasn't in macOS? Or maybe it was trying to get the incognito sessions API working so I didn't have to boot a new chrome process for each individual test?

It's been a 6 months and I stopped trying chromedp because of this, so the details have fallen out of my memory.

**Comment by jmhodges** [comment] 2019-04-04 22:02
I genuinely don't remember! Sorry!

**Comment by mvdan** [comment] 2019-04-07 11:47
Thanks for the reply. If it helps, the new API uses an interface to "allocate" browsers, and we'll add an allocator which starts Docker containers with specific versions of headless Chromium. So that should be easier soon enough.

The API you're talking about in this issue is now gone, and I don't think there's an actionable bug here, so I'm going to close this for now. Thanks!

**Closed by mvdan** 2019-04-07 11:47 UTC
Labels: needs info
