### ISSUE TITLE
chromedp keep opening tabs when screenshoting

### ISSUE THREAD

**Issue by shelld3v** [chromedp/chromedp#808] opened 2021-05-02 09:43 UTC
#### What versions are you running?

Latest chromedp (using `import ("github.com/chromedp/chromedp")`) + latest golang version (`go1.16.3 linux/amd64`) + latest Chromium (installed yesterday)

#### What did you do? Include clear steps.

See full code here: https://github.com/shelld3v/aquatone/blob/master/agents/url_screenshotter.go

Short:

```go
func (a *URLScreenshotter) screenshotPage(p *core.Page) {
	filePath := fmt.Sprintf("screenshots/%s.png", p.BaseFilename())

	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(*a.session.Options.ScreenshotTimeout)*time.Millisecond)
	defer cancel()

	ctx, cancel = a.execAllocator(ctx)
	defer cancel()

	ctx, cancel = chromedp.NewContext(ctx)
	defer cancel()

	chromedp.ListenTarget(ctx, func(ev interface{}) {
		if _, ok := ev.(*page.EventJavascriptDialogOpening); ok {
			a.session.Out.Debug("%s Error: alert box found\n", a.ID)
			a.session.Stats.IncrementScreenshotFailed()
			a.session.Out.Error("%s: screenshot failed: alert box popped up\n", p.URL)
			return
		}
	})


	var pic []byte
	var res interface{}

	if err := chromedp.Run(ctx, chromedp.Tasks{
		chromedp.Navigate(p.URL),
		chromedp.Sleep(time.Duration(*a.session.Options.ScreenshotDelay)*time.Millisecond),
		chromedp.CaptureScreenshot(&pic),
		chromedp.EvaluateAsDevTools(`window.alert = window.confirm = window.prompt = function (txt){return txt}`, &res),
	}); err != nil {
		a.session.Out.Debug("%s Error: %v\n", a.ID, err)
		a.session.Stats.IncrementScreenshotFailed()
		a.session.Out.Error("%s: screenshot failed: %s\n", p.URL, err)
		return
	}

	if err := ioutil.WriteFile(filePath, pic, 0700); err != nil {
		a.session.Out.Debug("%s Error: %v\n", a.ID(), err)
		a.session.Stats.IncrementScreenshotFailed()
		a.session.Out.Error("%s: screenshot failed: %s\n", p.URL, err)
		return
	}

	a.session.Stats.IncrementScreenshotSuccessful()
	a.session.Out.Info("%s: %s\n", p.URL, Green("screenshot successful"))
	p.ScreenshotPath = filePath
	p.HasScreenshot = true
}
```

I use this code to screenshot pages, but whenever it tries to screenshot a page, a new tab of Chromium will be opened, and then closed right after the screenshot finished.

#### What did you expect to see?

No tab opened, only a terminal with a flood of `[URL]: screenshot successful`

#### What did you see instead?

Noisy tabs

**Comment by ZekeLu** [comment] 2021-05-02 11:03
@shelld3v the `go.mod` file in your repository shows that you're using `chromedp@v0.5.3`, which is a little outdated. It looks like that you haven't push your latest source code to your repository. And your repository contains something else, which makes it a little hard to reproduce the issue.

Can you provide a minimal demo based on https://github.com/chromedp/examples/blob/master/emulate/main.go to reproduce the issue?

**Comment by shelld3v** [comment] 2021-05-02 11:08
Hi, can I ask what `EmulateViewport()` is? Set the thumbnail size?

**Comment by ZekeLu** [comment] 2021-05-02 11:12
https://github.com/chromedp/chromedp/blob/6a53e09ea7a4fcdc30615bcd9a00b12b2a0c1c0f/emulate.go#L16-L25

**Comment by shelld3v** [comment] 2021-05-02 11:22
Hi, is there anyway I can set the screenshot resolution?

**Comment by ZekeLu** [comment] 2021-05-02 11:32
I think `chromedp.EmulateViewport` is what you need. If you meant the compression quality, then you should check `https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot`.

I suggest you to read the docs carefully and do some tests yourself.

**Comment by shelld3v** [comment] 2021-05-02 11:42
I meant the thumbnail resolution (AxB pixels)

Btw, about the test code, why don't you install my tool for testing?

```
go get github.com/shelld3v/aquatone
mkdir test
echo http://example.com | aquatone -out test
cd test/screenshots
```

then open the image

**Comment by shelld3v** [comment] 2021-05-02 11:45
Probably `chromedp.EmulateViewport` is what I need

**Comment by ZekeLu** [comment] 2021-05-02 13:11
I checked your recent commits in your repository, it seems that you have figured out what's wrong (you don't set it to run in headless mode). Congratulations!

BTW, you can construct the allocator options like this:

```go
opts := append(chromedp.DefaultExecAllocatorOptions[:],
	// put your customized options below
	chromedp.UserAgent("xxxx"),
	// or overwrite the default options
	chromedp.Flag("headless", false),
)
```

Since your issue has been addressed, I'm closing this issue. Feel free to reopen it if I'm wrong.

**Closed by ZekeLu** 2021-05-02 13:11 UTC

**Comment by shelld3v** [comment] 2021-05-02 13:16
Yeah
