### ISSUE TITLE
"context canceled" error when running within an IDE

### ISSUE THREAD

**Issue by GoLover** [chromedp/chromedp#364] opened 2019-05-27 09:39 UTC
#### What versions are you running?

Golang version : 1.11.5

#### What did you do? Include clear steps.
i just wanted to use chromedp in back-end application.
i run this code thousand of times and in line `err := chromedp.Run(ctx,tasks(usrcrd))` error will be set to `context canceled`.

my source code is : 
```
package main

import (
	"context"
	"fmt"
	"github.com/chromedp/chromedp"
	"log"
	"net/http"
	"time"
)

type userCred struct {
	Username string
	Password string
}
func tasks(cred userCred) chromedp.Tasks {
	username := `'` + cred.Username + `'`
	password := `'` + cred.Password + `'`
	var inter interface{}
	return chromedp.Tasks{
		chromedp.Navigate(`https://news.ycombinator.com/submit`),
		chromedp.Sleep(5 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('acct')[1].value =`+username, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('pw')[1].value =`+password, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.querySelector("input[value='create account']").click()`, &inter, chromedp.EvalAsValue),
	}
}
func hndlr (w http.ResponseWriter, r *http.Request) {
	var usrcrd userCred
	usrcrd.Username = "test";
	usrcrd.Password = "test";
	ctx , _ := chromedp.NewContext(context.Background())
	err := chromedp.Run(ctx,tasks(usrcrd))
	if err != nil {
		log.Fatal(err) // Context canceled here
	}
	_,_ = fmt.Fprintf(w, "Fine")

}
func main() {
	http.HandleFunc("/",hndlr)
	_ = http.ListenAndServe("0.0.0.0:8080",nil)
}
```

just send a GET request to localhost:8080 and `hndlr` handler will handle your request.

#### What did you expect to see?
i expect to see fine message instead of this.
why context canceled? is there any race condition ?

#### What did you see instead?
program terminated with error message : `context canceled`

**Comment by mvdan** [comment] 2019-05-27 12:17
As with all the times I've tried before, I can't reproduce this. I just get other errors with curl. I'll leave this issue open, but there's nothing I can do if I can't reproduce whatever this problem is.

**Comment by GoLover** [comment] 2019-05-27 12:20
use any browser instead using curl !
you can try open this URL in any browser => http://localhost:8080

**Comment by mvdan** [comment] 2019-05-27 12:24
Calm down. I am using curl because you previously told me to.

Nevertheless, the same thing happens with Chrome:

```
$ go run f.go
2019/05/27 13:22:03 unexpected end of JSON input
exit status 1
```

You seem driven to keep opening the same issue over and over again, so I'm not sure what you want me to do here. I'll leave it open for another week and then close it, unless someone wants to spend the time trying to guess what's going on here.

**Comment by GoLover** [comment] 2019-05-27 12:30
do you use this code i share in current issue? issue number 364.
sorry for my bad English at all.
i will be thanking you if you help me fixing this.

**Comment by mvdan** [comment] 2019-05-27 12:41
Yes.

**Comment by movsb** [comment] 2019-05-27 13:04
I got the same result as mvdan.

```
$ go run t.go
2019/05/27 21:03:07 unexpected end of JSON input
exit status 1
```

**Comment by GoLover** [comment] 2019-05-27 13:17
ops !
i just test my code with Goland IDE debugger.
in debug mode i received context canceled error.
in run mode i received unexpected end of JSON !
i can't understand what's really happen?

**Comment by movsb** [comment] 2019-05-27 13:21
Is this exactly the code that you run in ide? I don't see any deadline context set.

**Comment by GoLover** [comment] 2019-05-27 13:31
I exactly run this.
In Debug mode : context canceled.
In Running mode : Unexpected end of JSON input.
It's really weird.

**Comment by mvdan** [comment] 2019-05-27 16:21
You don't seem to be the only one; see #344. I don't use an IDE, so I can't help. My guess would be that the Go code can't properly execute Chrome from within the IDE.

**Comment by GoLover** [comment] 2019-05-27 19:28
without IDE it returns an error about Unexpected end of JSON input.
like your problem in running with `go run sample.go`.

**Comment by rnd** [comment] 2019-05-28 04:21
@GoLover which version of chromedp and chrome did you use?

**Comment by GoLover** [comment] 2019-05-28 04:57
last version of chromedp and chrome 74.0.3729.169

**Comment by rnd** [comment] 2019-05-28 08:27
i can reproduce this locally

```
	return chromedp.Tasks{
		chromedp.Navigate(`https://news.ycombinator.com/submit`),
		chromedp.Sleep(5 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('acct')[1].value =`+username, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.getElementsByName('pw')[1].value =`+password, &inter, chromedp.EvalAsValue),
		chromedp.Sleep(1 * time.Second),
		chromedp.EvaluateAsDevTools(`document.querySelector("input[value='create account']").click()`, &inter, chromedp.EvalAsValue),
	}
```
any reason why do you use EvaluateAsDevTools to set the value? 
you can use chromedp.SetValue or even chromedp.SendKey to set this input value.

if you insist to use EvaluateAsDevTools please use []byte instead of interface.
Read the doc of Evaluate to understand what this method do.
https://godoc.org/github.com/chromedp/chromedp#Evaluate

**Comment by GoLover** [comment] 2019-05-28 13:59
when i use this code with net/http and wrapping a http handler on it it makes unexpected end of JSON without IDE , and with IDE debug mode it returns context canceled

**Comment by rnd** [comment] 2019-05-29 03:17
i didn't use IDE so i cannot reproduce that.

As the JSON error i've explain it on my previous comment, please try that first.

**Comment by kenshaw** [comment] 2019-06-17 07:36
I can't reproduce this, no matter what.

Here's my rewritten version:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

type Credential struct {
	Username string
	Password string
}

func (c Credential) loginTasks() chromedp.Tasks {
	return chromedp.Tasks{
		chromedp.Navigate(`https://news.ycombinator.com/submit`),
		chromedp.ActionFunc(func(ctx context.Context) error {
			script := fmt.Sprintf(`document.getElementsByName('acct')[1].value = %q;`+"\n", c.Username)
			script += fmt.Sprintf(`document.getElementsByName('pw')[1].value = %q;`, c.Password)
			log.Printf(">>> script:\n%s\n<<<script", script)
			_, exp, err := runtime.Evaluate(script).Do(ctx)
			if err != nil {
				return err
			}
			if exp != nil {
				return exp
			}
			return nil
		}),
		chromedp.Click(`document.querySelector("input[value='create account']")`, chromedp.ByJSPath),
	}
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := chromedp.NewContext(context.Background(), chromedp.WithDebugf(log.Printf))
		defer cancel()

		c := Credential{
			Username: "test",
			Password: "test",
		}

		err := chromedp.Run(ctx, c.loginTasks())
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintf(w, "worked!")
	})

	log.Fatal(http.ListenAndServe(":8080", mux))
}
```
There were problems with your previous implementation. Instead of trying to figure out where the problem was, I just simply rewrote from scratch.

My guess with the `context canceled` error you're getting, it's probably because Chrome is exhausting some kind of resource limit that's being clamped down by the IDE (memory, time limit, ...) and killing Chrome. We're working on a way to better expose any errors that the running Chrome process returns to standard out/error, but until then, please try running your code directly.

I'm going to close this issue for now, as it's not reproducible on my end (nor on Dan/Randy's end). There should be a new release of `chromedp` within the next two weeks (the API will still be the same). Please look for that release, and then try your original code with `chromedp` then. If it still occurs, hopefully then you can share more of the captured errors/output reported by `chromedp`.

**Closed by kenshaw** 2019-06-17 07:36 UTC
Labels: needs info, question
