### ISSUE TITLE
chromedp does not work under headless mode

### ISSUE THREAD

**Issue by schrodingerscat0224** [chromedp/chromedp#213] opened 2018-07-13 22:01 UTC
Hi,

I am trying to create a program with chromedp that performs multiple actions on a webpage to download some files. It works perfectly when I do not use headless option. But it does not do the job under the headless mode. Below is the code
`c, err := chromedp.New(ctx, chromedp.WithRunnerOptions(
		runner.HeadlessPathPort("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", 9222),
		runner.Flag("headless", true),
		runner.Flag("disable-gpu", true),
		runner.Flag("no-first-run", true),
		runner.Flag("no-default-browser-check", true)))`

Below is the error I got
<img width="1018" alt="screen shot 2018-07-13 at 3 02 24 pm" src="https://user-images.githubusercontent.com/29590951/42715900-da2b50b8-86ad-11e8-8e58-76f60efd5e14.png">

I have removed the c.ShutDown() and c.Wait(). still got no luck. Really appreciate if any help.

**Comment by kenshaw** [comment] 2018-07-14 00:39
Chrome is a complicated beast. Usually the `operation on node X` errors are due to Chrome's behavior occurring differently when headless, and is due to a number of reasons: certain JavaScripts don't execute properly and/or fail, the DOM finishes rendering too fast (or later than expected), causing timing issues in waiting for things. This has a large number of knock-down effects that cannot really be generalized here, as they are different for every webpage that exists. There is a new version of `chromedp` coming shortly, that aims to fix some of these issues (as it tracks from the source network events, and not the page events), and help with debugging these issues in the future. Until that's generally available, I can only make recommendations on how you can work around this:

1) Use `time.Sleep` (or `chromedp.Sleep`) liberally throughout your task hierarchies, waiting for pages to finish rendering prior to trying to determine if a node exists
2) Increase the timeout (needs to be done manually at the moment, in the `chromedp` source)
3) Not really a fix, but a recommendation for debugging: try connecting in headless directly using DevTools, and see what is happening exactly. `chromedp-proxy` can help with this to record / proxy the session. You might be surprised that the DOM state is not in the state that you're expecting.

**Comment by kenshaw** [comment] 2018-07-14 03:33
@schrodingerscat0224 ah -- I think I read over the part about downloading files in your original issue. So, my apologies -- I've actually never used Chrome/headless_shell for downloading files, and am not entirely sure how to accomplish that (however, I know fundamentally it's possible).

Am I correct in assuming, that in standard Chrome you were clicking "download" and/or relying on Chrome's auto-download feature for saving files? If so, it's worth mentioning that retrieving files using Chrome's download mechanism is not a robust mechanism to rely on. My understanding of the CDP, is that one must monitor the `Network.*` events and capture file data that way. As of today, this isn't  possible with `chromedp`, as we do not expose those events in any kind of usable API. The upcoming rewrite of `chromedp` will have better ways of handling this, as it is monitoring / managing `Network.*` events.

**Comment by schrodingerscat0224** [comment] 2018-07-14 03:45
@kenshaw got it, thank you. Do you have any idea about any other libraries that I can use to do this job for now, please?

**Comment by kenshaw** [comment] 2018-07-14 03:51
@schrodingerscat0224 you're going to have this same issue with any library -- the issue is, I believe, with using Chrome in headless mode. You'll need to record the `Network.*` events, and then manually write the data to a file. There might be a command-line switch that enables auto-downloads or some-such, but I'm not aware of one if there is. There are at least 3 other Go packages for working with CDP browsers, one of them might have a solution that works out of the box for you, but if there is, I'm not aware of one.

**Comment by mvdan** [comment] 2019-02-21 16:44
Seems like this discussion ended a while ago, so I'm closing the issue.

**Closed by mvdan** 2019-02-21 16:44 UTC
