### ISSUE TITLE
Lost Page when using 0.5.2 

### ISSUE THREAD

**Issue by molon** [chromedp/chromedp#490] opened 2019-10-14 08:10 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
$ google-chrome --version
$ go version
</pre>

github.com/chromedp/chromedp v0.5.2-0.20191014072212-f3844ad73979
chrome version 77.0.3865.90
go version go1.13 darwin/amd64

#### What did you do? Include clear steps.
```
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	// create context
	ctx, cancel := chromedp.NewExecAllocator(
		context.Background(),
		append(chromedp.DefaultExecAllocatorOptions[:],
			chromedp.Flag("headless", false),
			chromedp.Flag("enable-automation", false),
		)...)
	defer cancel()

	ctx, _ = chromedp.NewContext(ctx, chromedp.WithDebugf(func(f string, v ...interface{}) {
		log.Printf(f, v...)
	}))
        // TIPS: Please use a real account to test.
	username := `xxxxx`
	password := `yyyyy`

	emailSel := `//input[@id="email"]`
	passSel := `//input[@id="password"]`
	nextSel := `//button[@id='btnNext']`
	loginSel := `//button[@id='btnLogin']`
	hasLoginSel := `//section[@id="contents"]`
	if err := chromedp.Run(
		ctx,
		chromedp.Navigate(`https://www.paypal.com/myaccount/summary/`),
		chromedp.SetValue(emailSel, username, chromedp.NodeVisible),
		chromedp.Sleep(1*time.Second),
		chromedp.Click(nextSel, chromedp.NodeVisible),
		chromedp.WaitNotVisible(nextSel),
		chromedp.Sleep(1*time.Second),
		chromedp.SendKeys(passSel, password, chromedp.NodeVisible),
		chromedp.Sleep(1*time.Second),
		chromedp.Click(loginSel, chromedp.NodeVisible),
                // TIPS: Block forever when using 0.5.2, But not 0.4.2
		chromedp.WaitVisible(hasLoginSel),
	); err != nil {
		log.Fatal(err)
	}
}
```
After research, I found that below:

If I remove this code to avoid Deleting The Page. Everything will be ok.
```
if m.Method == cdproto.EventTargetDetachedFromTarget {
				if _, ok := pages[m.SessionID]; !ok {
					b.errf("executor for %q doesn't exist", m.SessionID)
				}
				b.dbgf("Session %v Detached!", m.SessionID)
				delete(pages, m.SessionID)
			}
```

Then we can found that it is not suitable for using `Target.detachedFromTarget`  as a basis to delete Page.
```
2019/10/14 16:01:15.260048 <- {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"EDA37429F4C791C72574D6B32E668CAB","type":"worker","title":"https://www.recaptcha.net/recaptcha/api2/webworker.js?hl=zh-HK&v=xw1jR43fRSpRG88iDviKn3qM","url":"https://www.recaptcha.net/recaptcha/api2/webworker.js?hl=zh-HK&v=xw1jR43fRSpRG88iDviKn3qM","attached":false,"browserContextId":"CEDAA7A7D75016249CBD1A93A22D03F8"}},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
2019/10/14 16:01:15.260426 <- {"method":"Target.detachedFromTarget","params":{"sessionId":"161922FD5EF8157969D6191823BD76CC","targetId":"EDA37429F4C791C72574D6B32E668CAB"},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
2019/10/14 16:01:15.264162 <- {"method":"Target.targetDestroyed","params":{"targetId":"EDA37429F4C791C72574D6B32E668CAB"},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
2019/10/14 16:01:15.273373 <- {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"A137268106E827A36D6FE8736E046EB1","type":"page","title":"https://www.paypal.com/auth/validatecaptcha","url":"https://www.paypal.com/auth/validatecaptcha","attached":true,"browserContextId":"CEDAA7A7D75016249CBD1A93A22D03F8"}},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
......
......
......
2019/10/14 16:01:18.322153 -> {"id":1208,"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6","method":"DOM.performSearch","params":{"query":"//section[@id=\"contents\"]"}}
2019/10/14 16:01:18.324159 <- {"id":1208,"result":{"searchId":"1000050374.1004","resultCount":1},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
......
2019/10/14 16:01:18.993582 <- {"method":"Page.loadEventFired","params":{"timestamp":144867.275776},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
2019/10/14 16:01:18.993658 <- {"method":"Page.frameStoppedLoading","params":{"frameId":"A137268106E827A36D6FE8736E046EB1"},"sessionId":"12F5025D89B76EE78502B91E5EA8ABC6"}
```

But it's ok when using 0.4.2. it's interesting.

**Comment by kenshaw** [comment] 2019-10-14 10:49
Any chance you can connect this in a debugger, and let us know "where" it's hanging? My guess is that if you actually ran this to a connected session, you'd see that the `contents` element isn't appearing, so `WaitVisible` never returns.

Also, it's worth noting, you can simplify this:
```go
chromedp.NewContext(ctx, chromedp.WithDebugf(log.Printf))
```

**Comment by molon** [comment] 2019-10-14 11:35
Thanks for your quick reply.
I said it was available in another version. So I confirm it appears.
And with my research, I confirm the performSearch method has not returns. The reason is can’t get the corresponding page  in the browser msg loop although the result has returned. Then I found the page has deleted when receive detachedFromTarget event. But with the log you can see although detachedFromTarget has received, the session is still alive.
Sorry for pool english.
Honestly, I don't know how to use debugger you said. If there is a tutorial link, I would love to help solve the problem.

**Comment by jseriff** [comment] 2019-10-25 03:44
I'm experiencing the same issue - it appears the problem is that the detachedFromTarget comes in, but its not targeted at the root frame for the page.  So, chromedp deletes the page object, when it should probably just delete the impacted frame.  This causes all future messages to not be processed, and chromedp will just timeout waiting for a message it will never process.

**Comment by jseriff** [comment] 2019-10-25 12:23
To be more specific, I believe the block here: 
https://github.com/chromedp/chromedp/blob/1a34c61f78475a292abe24eba22464e71a912838/browser.go#L290

Should deserialize the targetId, and check it against the page's current frame. If they do not match, the code should delete the referenced frame from the page, but not delete the page itself.

**Comment by mvdan** [comment] 2019-11-06 21:27
@jseriff thanks for the investigation. Could you provide us with a link or HTML page we could use to reproduce the problem, please? That will allow us to debug it better, and write a test alongside a fix.

**Comment by jseriff** [comment] 2019-11-06 21:42
Unfortunately, i do not.  The page I was experiencing the issue on was on a site that required credentials.  From a quick look at what was going on, it seemed related to iframes coming and going while the page was still rendering - likely due to some form of SSO.

**Comment by mvdan** [comment] 2019-11-25 14:51
Hm, I don't think the suggestion above of filtering `EventTargetDetachedFromTarget` is correct. Detaching from a target means detaching from an entire tab, not a single iframe. Iframes being deleted should be `*page.EventFrameDetached`.

I tried to replicate this with buttons to add and delete iframes, but I couldn't get chromedp to hang. Not sure what else to try.

If this is a regression, it's probably from our rewrite to use the new "flattened" devtools protocol. We had to refactor bits of the codebase, so it's entirely possible we introduced a bug. It's hard to spot it if I can't see it, though.

**Comment by mvdan** [comment] 2019-11-25 15:03
Hm, I was able to reproduce the issue with Paypal, and it seems to be related to some iframe shenanigans with google's recaptcha. At least now I can see there's a bug.

**Comment by mvdan** [comment] 2019-11-25 16:24
I'm pretty sure that the bug is fixed with the commit above; see its message and diff for details.

I was only able to reproduce the paypal hang once, as future runs simply skipped the iframe with Google's recaptcha. So I'm not 100% positive that the issue is fixed. If you still encounter it, please let me know.

**Closed** 2019-11-25 16:24 UTC
