### ISSUE TITLE
intercept network responses while page loading

### ISSUE THREAD

**Issue by maxjust** [chromedp/chromedp#163] opened 2018-01-08 08:33 UTC
Hi, can you please provide a simple network response interceptions example, because old (listed below) code is not working anymore.  cdptypes.Handler is not exist, Executor present instead, but I cant understand how to use it for intercept network responses.

```
cdp.Tasks{
    cdp.ActionFunc(func(ctxt context.Context, h cdptypes.Handler) error {
        go func() {
            echan := h.Listen(cdptypes.EventNetworkRequestWillBeSent, cdptypes.EventNetworkLoadingFinished)
            for d := range echan {
                switch d.(type) {
                case *network.EventRequestWillBeSent:
                    req := d.(*network.EventRequestWillBeSent)
                    if strings.HasSuffix(req.Request.URL, "/data_I_want.js") {
                        reqId1 = req.RequestID
                    } else if strings.HasSuffix(req.Request.URL, "/another_one.js") {
                        reqId2 = req.RequestID
                    }
                case *network.EventLoadingFinished:
                    res := d.(*network.EventLoadingFinished)
                    var data []byte
                    var e error
                    if reqId1 == res.RequestID {
                        data, e = network.GetResponseBody(reqId1).Do(ctxt, h)
                    } else if reqId2 == res.RequestID {
                        data, e = network.GetResponseBody(reqId2).Do(ctxt, h)
                    }
                    if e != nil {
                        panic(e)
                    }
                    if len(data) > 0 {
                        fmt.Printf("=========data: %+v\n", string(data))
                    }
                }
            }
        }()
        return nil
    }),
    cdp.Navigate(url),
    ...
}
```

**Comment by tianburg** [comment] 2018-06-25 10:53
@MaxJust 

I can not find : cdptypes.Handler   

the function signature should be cdp.Executor 

> chromedp.ActionFunc(func(ctxt context.Context, h cdp.Executor) error

**Comment by mvdan** [comment] 2019-02-21 23:22
The title is an almost exact duplicate of https://github.com/chromedp/chromedp/issues/131.

**Closed by mvdan** 2019-02-21 23:22 UTC
