### ISSUE TITLE
Poll survive navigation

### ISSUE THREAD

**Issue by troyk** [chromedp/chromedp#890] opened 2021-08-02 00:00 UTC
The [docs](https://github.com/chromedp/chromedp/blob/v0.7.4/poll.go#L112) for Poll state not surviving navigation is intended, however we scrape a few sites (behind a paywall) that do some funky page loads with redirects after an initial click to submit and we need to wait around for it to finish and sniff some js.  The following code seems to be working and this issue is to gauge interest in a PR to add as a PollOption or simply document how it can be done for the next person searching.

```go
func WaitForJS(expression string, res interface{}, opts ...chromedp.PollOption) chromedp.ActionFunc {
	return func(ctx context.Context) error {
		pollfn := chromedp.Poll(expression, res, opts...)
		log.Println("WaitForJS", expression)
	retry:
		err := pollfn.Do(ctx)
		if err != nil && err.Error() == "Execution context was destroyed. (-32000)" {
			log.Println("WaitForJS", "retry", err.Error())
			// chromedp.Evaluate updates the context with the new Execution context.  Not sure if there is 
			// a cleaner way; without this call, the subsequent/retry poll call will error: Cannot find context with specified id 
			jsfn := chromedp.Evaluate("1==1", nil)
			err := jsfn.Do(ctx)
			if err != nil {
				return fmt.Errorf("unable to exec 1==1 dummy script to init new context: %w", err)
			}
			goto retry
		}
		return err
	}
}
```

**Comment by ZekeLu** [comment] 2021-08-02 10:30
I did not make it survive navigation because I could not find an easy way to do it (without making the implementation complicated). W.R.T. this concrete use case, maybe it's better to implement it like this:

1. navigate to the page (`chromedp.Navigate`)
2. wait for the click action to complete: `chromedp.RunResponse(chromedp.Click(query))` (see https://github.com/chromedp/chromedp/issues/651#issuecomment-653769905)
3. call `chromedp.Poll`

> chromedp.Evaluate updates the context with the new Execution context.

I don't think this statement is correct. But I don't understand why `chromedp.Evaluate` will do the trick too. Can you provide a demo so that I can look into it?

**Comment by troyk** [comment] 2021-08-04 06:57
@ZekeLu thanks for looking into this, I've tried to get "error: Cannot find context with specified id" to reproduce with the following code to no avail.  One thing I did notice is I am calling .Do in a loop, not sure if that is supported or not.   The code I'm using that works is below, feel free to close this issue and I can reopen when and if I'm able to reproduce.  

Is adding an option to survive navigations doable?

```go
/* Tests to show Poll can not retry without first calling chromedp.Evaluate
 * https://github.com/chromedp/chromedp/issues/890

*/

package chromedp_test

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/chromedp/chromedp"
)

func PollSurvive(expression string, res interface{}, opts ...chromedp.PollOption) chromedp.Action {
	return chromedp.ActionFunc(func(ctx context.Context) error {
		retries := 0
	retry:
		err := chromedp.Poll(expression, res, opts...).Do(ctx)
		if err != nil && strings.Contains(err.Error(), "(-32000)") {
			fmt.Println("retry", err.Error())
			retries++
			if retries > 2 {
				chromedp.Run(ctx, chromedp.Evaluate("window.stopreloading=true", nil))
			}
			goto retry
		}
		return err
	})
}

// This is working as well, need to debug further with live sites and determine what is causing
// the error: Cannot find context with specified id
func PollSurviveFail(expression string, res interface{}, opts ...chromedp.PollOption) chromedp.Action {
	return chromedp.ActionFunc(func(ctx context.Context) error {
		pollfn := chromedp.Poll(expression, res, opts...)
		retries := 0
	retry:
		err := pollfn.Do(ctx) // calling Do in the retry
		if err != nil && strings.Contains(err.Error(), "(-32000)") {
			fmt.Println("retry", err.Error())
			// second retry will be error: Cannot find context with specified id
			// uncomment the code below and somehow we get an execution context again, and this works as well
			// jsfn := chromedp.Evaluate("1==1", nil)
			// err := jsfn.Do(ctx)
			// if err != nil {
			// 	return fmt.Errorf("unable to exec 1==1 dummy script to init new context: %w", err)
			// }
			retries++
			if retries > 2 {
				chromedp.Run(ctx, chromedp.Evaluate("window.stopreloading=true", nil))
			}
			goto retry
		}
		return err
	})
}

func TestPollOnNav(t *testing.T) {
	// create a test server to serve a page that reloads itself on a timer
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_, _ = fmt.Fprint(w, `
	<html lang="en"><body><h1>Test</h1></body>
	<script> window.setTimeout(function(){ location.reload(); }, 600); </script>
	</html>
	`,
		)
	}))
	defer ts.Close()
	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// no error
	err := chromedp.Run(ctx,
		chromedp.Navigate(ts.URL),
		PollSurvive(`!(typeof stopreloading === "undefined")`, nil),
	)
	fmt.Println("Poll error: ", err)

	// no error
	err = chromedp.Run(ctx,
		chromedp.Navigate(ts.URL+"?ts=1"),
		PollSurviveFail(`!(typeof stopreloading === "undefined")`, nil),
	)
	fmt.Println("Poll error: ", err)

}
```

**Comment by ZekeLu** [comment] 2021-08-04 09:08
> Is adding an option to survive navigations doable?

It's okay to do the retry in the user code. But I can not think of a user case that it helps to put the retry into the library (like I said before, for your use case, it's better to call `chromedp.Poll` after the click action).

> The code I'm using that works is below, feel free to close this issue and I can reopen when and if I'm able to reproduce.

Let's leave this issue open for another week. I will close it if we still can not reproduce the "Cannot find context with specified id" error then.

**Closed** 2021-09-10 04:56 UTC
