### ISSUE TITLE
Unable to click on a button of type `input`

### ISSUE THREAD

**Issue by farzadmf** [chromedp/chromedp#584] opened 2020-03-14 04:18 UTC
#### What versions are you running?

<pre>
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.5.3

$ google-chrome --version
# In my Manjaro Linux, I ran: google-chrome-stable --version
Google Chrome 80.0.3987.132 

$ go version
go version go1.14 linux/amd64

</pre>

#### What did you do? Include clear steps.
I'm trying to automate Microsoft login. The thing I have was working before, but all of a sudden, it's not anymore.

I have this code:
```go
func callLogin() {
    // ...
    ctx, cancel = context.WithTimeout(ctx, 15 * time.Second)
    defer cancel()

    ctx, cancel = chromedp.NewContext(
        ctx,
        cdp.WithLogf(log.Printf),
    )
    err := chromedp.Run(
        ctx,
        login(url, user, pass),
    )
    // ...
}

func login(url, user, pass string) chromedp.Tasks {
    return []chromedp.Action{
        chromedp.Navigate(url),
        // This button is available on the Website I'm automating; it initiates a Microsoft login flow
        chromedp.Click("#windowsLiveId", chromedp.NodeVisible),
        chromedp.SendKeys("#i0116", user, chromedp.NodeVisible),
        chromedp.Click("#idSIButton9"), // <--- *****
        chromedp.Sleep(1 * time.Second),
        chromedp.SendKeys("#i0118", pass, chromedp.NodeVisible),
        chromedp.Click("#idSIButton9", chromedp.NodeVisible),
    }
}
```

#### What did you expect to see?
Login should be successfully finished. The line I indicated seems to be the troublesome line here: if I run `chromedp` in a non-headless mode, I see that it enters the username and just sits there, it seems like it's ignoring the `Click` to be done on button `#idSIButton9`)

Moreover, in the non-headless mode, if I manually click on the button, the login happens as expected (meaning that the second `Click` on the same button actually happens)

I tried to add `chromedp.NodeVisible` to that `Click`, but it doesn't seem to change anything

This is a screenshot I took with non-headless mode, highlighting the HTML for the button:
![image](https://user-images.githubusercontent.com/5768792/76674748-ff376700-6588-11ea-8586-45762a9643c8.png)

#### What did you see instead?
I think the answer to this question is also in what I described above.

Also, as I mentioned above, it was working fine before (a couple of months ago), but when I came back to it to run it again, doesn't seem to work anymore

---

UPDATE: seems like doing something like `chromedp.Click("#idSIButton9", chromedp.ByID)` solves the issue. Can you please tell me what's happening here and what I'm not understanding here, because I'm very confused about this

**Comment by mvdan** [comment] 2020-04-17 16:21
Duplicate of https://github.com/chromedp/chromedp/issues/440, I'm pretty sure.

**Closed by mvdan** 2020-04-17 16:21 UTC
